### DISCUSSION TITLE
Trivy not discovered by Prometheus with ServiceMonitor

### DISCUSSION THREAD

**Discussion by JoeSpiral** [aquasecurity/trivy-operator#1667] [Help & Support]
I have installed the Trivy Operator and it is not being discovered by my Prometheus ServiceMonitor.  I am using kube-prometheus-stack and have other services like ArgoCD that have been discovered without issue.  I see the Trivy serviceMonitor in k9s as well.  Any insight would be appreciated.  Below is my Trivy values config:
```
service:
  headless: true
  metricsPort: 80
  # -- annotations added to the operator's service
  annotations: {}

# -- Prometheus ServiceMonitor configuration -- to install the trivy operator with the ServiceMonitor
# you must have Prometheus already installed and running. If you do not have Prometheus installed, enabling this will
# have no effect.
serviceMonitor:
  # -- enabled determines whether a serviceMonitor should be deployed
  enabled: true
  # -- The namespace where Prometheus expects to find service monitors
  namespace: "default"
  # -- Interval at which metrics should be scraped. If not specified Prometheus’ global scrape interval is used.
  interval: ~
  # -- Additional annotations for the serviceMonitor
  annotations: {}
  # -- Additional labels for the serviceMonitor
  labels: {}
  # -- HonorLabels chooses the metric’s labels on collisions with target labels
  honorLabels: true
  # -- EndpointAdditionalProperties allows setting additional properties on the endpoint such as relabelings, metricRelabelings etc.
  endpointAdditionalProperties: {}
```
