### DISCUSSION TITLE
Internal Twirp error??

### DISCUSSION THREAD

**Discussion by Zeratoxx** [aquasecurity/trivy-operator#1698] [Help & Support]
Hi,

What does `internal twirp error: failed to do request: Post \"http://trivy-service:4954/twirp/trivy.cache.v1.Cache/MissingBlobs\": EOF\n` mean? When does this error accur?

When it comes to the scan jobs for vulnerablities, the trivy-operator logs the error message above.

Helm Chart that gets used:
```yaml
chart: trivy-operator
repoURL: https://aquasecurity.github.io/helm-charts/
targetRevision: 0.19.1
```

The Operator runs in `ClientServer` mode, a trivy server is running.
