### DISCUSSION TITLE
no vulnerabilityreports and sbomreports with RKE2

### DISCUSSION THREAD

**Discussion by sylvainOL** [aquasecurity/trivy-operator#1765] [Help & Support] [answered]
Hello, 
I'm using RKE2 and I'm trying to make trivy operator to work on it.
I've got many questions and I'm doing a thread per questions ^_^:

here's the values.yaml that I'm giving (I'm using trivy operator chart version `0.20.1` which uses version `0.18.1` of operator):

<details>

```yaml
---
excludeNamespaces: "{{ .Release.Namespace }}"
image:
  pullPolicy: Always

nodeCollector:
  volumes:
    - hostPath:
        path: /var/lib/rancher/rke2/server/db
      name: var-lib-etcd
    - hostPath:
        path: /var/lib/kubelet
      name: var-lib-kubelet
    - hostPath:
        path: /var/lib/kube-scheduler
      name: var-lib-kube-scheduler
    - hostPath:
        path: /var/lib/kube-controller-manager
      name: var-lib-kube-controller-manager
    - hostPath:
        path: /etc/systemd
      name: etc-systemd
    - hostPath:
        path: /lib/systemd
      name: lib-systemd
    - hostPath:
        path: /var/lib/rancher/rke2/server/
      name: etc-kubernetes
    - hostPath:
        path: /etc/cni/net.d/
      name: etc-cni-netd

operator:
  builtInTrivyServer: true
  clusterComplianceEnabled: true
  clusterSbomCacheEnabled: true
  exposedSecretScannerEnabled: true
  logDevMode: true
  metricsClusterComplianceInfo: true
  metricsImageInfo: true
  metricsVulnIdEnabled: true
  sbomGenerationEnabled: true
  scanJobTimeout: 5m
  # no need to stress the cluster when it is reconciling
  scanJobsConcurrentLimit: 3
  scanJobsRetryDelay: 120s
  scanNodeCollectorLimit: 3
  vulnerabilityScannerReportTTL: 48h

podAnnotations:
  proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'

podSecurityContext:
  runAsGroup: 10000
  runAsUser: 10000
  seccompProfile:
    type: RuntimeDefault

resources:
  limits:
    ephemeral-storage: 100Mi
    memory: 512Mi
  requests:
    cpu: 50m
    ephemeral-storage: 100Mi
    memory: 512Mi

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true

serviceAccount:
  annotations: {}
  create: true
  name: "trivy-operator"

trivy:
  # renovate: datasource=docker
  imageRef: docker.io/aquasec/trivy:0.48.2
  resources:
    limits:
      ephemeral-storage: 100Mi
      memory: 1Gi
    requests:
      cpu: 100m
      ephemeral-storage: 100Mi
      memory: 512Mi
  storageClassName: hdd

trivyOperator:
  scanJobPodTemplateContainerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
  scanJobPodTemplatePodSecurityContext:
    runAsGroup: 10000
    runAsUser: 10000
    seccompProfile:
      type: RuntimeDefault
  scanJobTolerations:
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      key: CriticalAddonsOnly
      value: "true"
```

</details>

I've also tried with `sbomGenerationEnabled` and `clusterSbomCacheEnabled` set to `false`.

I'm waiting a little bit and I see this kind of lines in logs:

```
trivy-operator-77cff8df8b-dtnnv trivy-operator 2024-01-12T06:58:09Z	DEBUG	reconciler.vulnerabilityreport	Getting workload from cache	{"kind": "CronJob", "name": {"name":"harbor-robot-login-test","namespace":"harbor-test"}, "workload": "harbor-robot-login-test"}
```

but nothing happens (no scan is triggered and not custom resources is created):

```console
$ kubectl get vulnerabilityreports --all-namespaces -o wide
No resources found
```

What am I missing in your opinion?

thanks!
