### DISCUSSION TITLE
How to set taints for scan-vulnerabilityreport Pods?

### DISCUSSION THREAD

**Discussion by Brzozova** [aquasecurity/trivy-operator#1781] [Development]
Hi! This is how I configured taints using Helm Charts in values.yaml

```
trivy-operator:
  tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
```
I thought after deploying this change I will see taints in each Pod deployed in trivy-system which are trivy-operator and all scan-vulnerabilityreport.

However looks like it only had an impact on trivy-operator Pod:
```
Tolerations:                 kubernetes.azure.com/scalesetpriority=spot:NoSchedule
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
```

scan-vulnerabilityreport Pods looks like this:
```
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
```

As scan-vulnerabilityreport are quite busy, I would like to add taints to them as well. 
Is there a way to do it?
