### DISCUSSION TITLE
Operator metrics endpoint doesnt's show trivy_image metrics

### DISCUSSION THREAD

**Discussion by networkandcode** [aquasecurity/trivy-operator#1960] [Help & Support]
Hi I tried installing trivy operator with helm with the values:
```
trivy:
  ignoreUnfixed: true
```

When I tried port fowarding the pod and access the metrics I could not see metrics that start with. trivy_image*... could you pl. tell where I could access this. I tried joining the slack channel, but it only allows specific email domains.

<img width="1298" alt="image" src="https://github.com/aquasecurity/trivy-operator/assets/30622440/fdfb9298-eee4-4084-bed7-0dfe198e8457">

**Comment by xRTRx** [comment]
Set `operator.metricsImageInfo` to `true`.

**Reply by networkandcode** [reply]
tried it, still not coming.. this is the values file:
```
operator:
  metricsImageInfo: true
  metricsInfraAssessmentInfo: true
service:
  annotations:
    prometheus.io/scrape: "true"
serviceMonitor:
  enabled: true
trivy:
  ignoreUnfixed: true
```

I can now see trivy_infraassessmets_* but not trivy_image_*
<img width="1314" alt="image" src="https://github.com/aquasecurity/trivy-operator/assets/30622440/f4e12a6a-8769-4ebe-9b0c-e09fbc41379a">
<img width="1182" alt="image" src="https://github.com/aquasecurity/trivy-operator/assets/30622440/e388dc3b-3fa3-42fd-ae08-ae7114a2f3e0">

**Comment by chen-keinan** [comment]
@networkandcode are you getting other vulnerability_image metrics ?

**Reply by networkandcode** [reply]
I don't see anything starting with trivy_image*

**Comment by chen-keinan** [comment]
@networkandcode can you please share you configuration (config maps / values.yaml)

**Reply by networkandcode** [reply]
@chen-keinan this is the values file
```
operator:
  metricsImageInfo: true
  metricsInfraAssessmentInfo: true
service:
  annotations:
    prometheus.io/scrape: "true"
serviceMonitor:
  enabled: true
trivy:
  ignoreUnfixed: true
```
