### DISCUSSION TITLE
Exclude master-node

### DISCUSSION THREAD

**Discussion by Halogenmake** [aquasecurity/trivy-operator#2015] [Help & Support]
Good day, I have installed Trivy-Operator 0.19.4 on my cluster. There are 3 master nodes in the cluster, and I would like to prevent the "scan-vulnerabilityreport-*****" jobs from running on these nodes. How can I do this?

**Comment by chen-keinan** [comment]
@Halogenmake the  easy is adding [taints](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) to this nodes, so scan-jobs will not schedule to it

**Comment by Halogenmake** [comment]
@chen-keinan The problem is that although taints are set on these nodes, the jobs are still being launched on them.

**Reply by chen-keinan** [reply]
this is strange, have you set up [toleration](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L231) for scan-job ?

**Reply by Halogenmake** [reply]
No, I am using Helm to install Trivy-operator and specify additional parameters like this; 

```
trivy:
  command: filesystem

trivyOperator:
  scanJobPodTemplateContainerSecurityContext:
    # For filesystem scanning, Trivy needs to run as the root user
    runAsUser: 0

#trivyOperator:
#  scanJobNodeSelector:
#    magnum.openstack.org/role: worker

operator:
  scanJobsConcurrentLimit: 5
  scannerReportTTL: "120h"

nodeSelector:
  magnum.openstack.org/role: worker

```
however, the jobs are still being launched on master nodes.
