### DISCUSSION TITLE
When are Scans triggered in ClientServer Mode?

### DISCUSSION THREAD

**Discussion by kimdre** [aquasecurity/trivy-operator#2175] [Help & Support]
Hi, I set the operator to use `builtInTrivyServer: true`.
After the deployment and startup of the trivy-operator and trivy-server pods nothing really happens. When or how do vulnerability scans for get triggered in this mode?

**Comment by kimdre** [comment]
@chen-keinan Could you please help me out here? Am I missing something? 😅

**Reply by chen-keinan** [reply]
- scan-jobs should be spined on `trivy-system` namespace.
- `trivy-server` is statefulset running on `trivy-system` namespace as well,  it purpose is the provide vulnerability data matching

so when a scan-job is running and it detect the installed components it ask from `trivy-server` for vulnerability information on the installed components

**Reply by kimdre** [reply]
Huh weird. 
I never see any scans running by the operator and no scan pods starting.
Isn't it enough to just set  `builtInTrivyServer` to `true` and wait for the operator to start scan pods like in the standalone mode?

**Reply by chen-keinan** [reply]
if you run:
```sh
kubectl get pods -n trivy-system
```
do you see trivy-opeator and trivy-server pods ?

**Reply by kimdre** [reply]
I use a different name for the namespace but yes, I see them. 

```yaml
$ kubectl get pods -n trivy-operator
NAME                             READY   STATUS    RESTARTS   AGE
trivy-operator-ddc798dbc-hj6l4   1/1     Running   0          16h
trivy-server-0                   1/1     Running   0          16h
```

But the operator never runs any image scans.

**Reply by chen-keinan** [reply]
do you see any errors in trivy-operator logs?

**Reply by chen-keinan** [reply]
have you excluded/target namespaces in config ?

**Reply by kimdre** [reply]
> do you see any errors in trivy-operator logs?

Nope, only info messages: https://gist.github.com/kimdre/d8dce232c9225335304582995f011837

> have you excluded/target namespaces in config ?

Yes, I set `targetNamespaces` to a couple of namespaces including trivy-operator itself.

**Reply by chen-keinan** [reply]
can you unset targetNamespaces and see if it related ?

**Reply by kimdre** [reply]
Does not seem like that is the cause.
The operator still runs no image scans. The only thing it does it creates ConfigAuditReports, but the operator did this before aswell with targetNamespace set.

**Reply by chen-keinan** [reply]
have you tried to deploy a new resource to cluster , can you please share your configmaps ?

**Reply by kimdre** [reply]
I deployed a service with a new version but no scans were triggered.

These are the values I use:

```yaml
targetNamespaces: "**redacted**,trivy-operator" # comma-separated list
excludeNamespaces: "" # comma-separated list

compliance:
  cron: "0 */6 * * *"

operator:
  builtInTrivyServer: true
  valuesFromSecret: proxy-secrets
  infraAssessmentScannerEnabled: false
  scanJobsConcurrentLimit: 1

trivy:
  slow: true
  severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
  valuesFromSecret: proxy-secrets
  resources:
    requests:
      cpu: 100m
      memory: 100M
    limits:
      cpu: 500m
      memory: 500M
  server:
    resources:
      requests:
        cpu: 200m
        memory: 512M
      limits:
        cpu: 1
        memory: 1Gi
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      privileged: false
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault

trivyOperator:
  scanJobPodTemplateContainerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    seccompProfile:
      type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  privileged: false
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
```
