### DISCUSSION TITLE
Help pulling trivy-db and java-db from private registry

### DISCUSSION THREAD

**Discussion by ctdfo** [aquasecurity/trivy-operator#2344] [Help & Support]
We are trying to pull the trivy-db and java-db from a private registry. To note,  we are running in `ClientServer` mode. 

We already allowed Trivy Operator to access private registries via the Helm chart value `privateRegistryScanSecretsNames`. However, when setting `dbRegistry` and `javaDbRegistry` we tried setting the `dbRepositoryUsername` and `dbRepositoryPassword` via an External Secret but we get errors in both trivy-operator and trivy-server saying that the databases cannot be downloaded (we also set `trivy.existingSecret` to false). 

We also tried setting directly the `TRIVY_USERNAME` and `TRIVY_PASSWORD` values via an External Secret trivy-server was able to pull from the trivy-db (but the trivy-client was not able to pull from java-db).

**Comment by Patrick2402** [comment]
Hi, i also spent several hours on finding solution how to pull trivy-db and java-db. trivy-db from private repository works great but as i checked pulling java-db for now its impossible. 

i hope they will add this functionality asap. 
the only way is to allow specific domains in security rules.

**Comment by tom1299** [comment]
I would appreciate this feature as well, as I have the exact same problem. I looked at the scan job and it seems that the init container that downloads the normal db has the `TRIVY_USERNAME` and `TRIVY_PASSWORD` set as env vars. Hence download works;
```yaml
  initContainers:
  - args:
    - --cache-dir
    - /tmp/trivy/.cache
    - image
    - --download-db-only
    - --db-repository
    - artifactory.devops.telekom.de/ghcr.io.docker/aquasecurity/trivy-db
    command:
    - trivy
    ....
    - name: TRIVY_USERNAME
      valueFrom:
        secretKeyRef:
          key: trivy.dbRepositoryUsername
          name: trivy-operator-trivy-config
          optional: true
    - name: TRIVY_PASSWORD
      valueFrom:
        secretKeyRef:
          key: trivy.dbReposito	ryPassword
          name: trivy-operator-trivy-config
          optional: true
 ```
 Yet the main container does not. I was also wondering whether there is the possibility to use different credentials for downloading the `java-db`.
