### DISCUSSION TITLE
Trivy-Operator helmchart does not allow adding labels for serviceaccount

### DISCUSSION THREAD

**Discussion by butenhoff-encoway** [aquasecurity/trivy-operator#2389] [Help & Support]
Hello, im currently trying to deploy trivy inside our AKS Cluster and im using a managed aks registry.
Given the following documentation, the service account needs the label:
- azure.workload.identity/use: "true"
The helmchart does not offer any way to add any label to the serviceaccount, as can be seen here:
https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/templates/serviceaccount.yaml

Am I overlooking anything or is this a bug / oversight in the helmchart?

**Comment by c-ianniello** [comment]
It also seems that the service account must be created with these fields, otherwise the operator is not able to connect to the registry with aks cluster (using workload identity)

Still now is not possible to add labels via the helm chart

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-operator
  namespace: trivy-system
  labels:
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/version: 0.16.0
    azure.workload.identity/use: 'true'
    k8slens-edit-resource-version: v1
  annotations:
    azure.workload.identity/client-id: xxx
    azure.workload.identity/tenant-id: xxxx
    
    ```
