### DISCUSSION TITLE
how to cache images so they are not pulled over and over from repository

### DISCUSSION THREAD

**Discussion by travis-jorge** [aquasecurity/trivy-operator#2419] [Help & Support]
I have noticed if i deploy the same application 10 times and 10 pods are created it is pulling that application image from the image repository 10 times. Is it possible to cache the image and then for the subsequent pods only scan from the cache or ignore the scan because it was already done once before.

**Comment by sumeyya58** [comment]
Yes! that's the exact same problem I am facing with trivy-operator

**Comment by tom1299** [comment]
One thing that might enable caching (although I haven't tried it yet) is to set the `imageScanCacheDir` to a different value and use custom scan job volumes and volume mounts to use a persistent volume. That way scan jobs would all use the same cache which should reduce the number of image downloads:
```yaml
# -- imageScanCacheDir the flag to set custom path for trivy image scan `cache-dir` parameter.
# Only applicable in image scan mode.
imageScanCacheDir: "/tmp/trivy/.cache"

# -- scanJobCustomVolumesMount add custom volumes mount to the scan job
scanJobCustomVolumesMount: []
#  - name: var-lib-etcd
#    mountPath: /var/lib/etcd
#    readOnly: true

# -- scanJobCustomVolumes add custom volumes to the scan job
scanJobCustomVolumes: []
#  - name: var-lib-etcd
#    hostPath:
#    path: /var/lib/etcd
```
