### DISCUSSION TITLE
How to skip k8s cluster image scanning using the helm chart values?

### DISCUSSION THREAD

**Discussion by CyberHippo** [aquasecurity/trivy-operator#2572] [Help & Support]
Hello,
Is it possible to disable the trivy kubernetes image scanning [as mentioned in the docs](https://trivy.dev/latest/docs/target/kubernetes/#skip-images) using the charts values?
I tried to add an extra environment variable as follows but it did not work:
```yaml
  extraEnv:
    - name: TRIVY_SKIP_IMAGES
      value: "true"
```
