### DISCUSSION TITLE
Reduce internet traffic

### DISCUSSION THREAD

**Discussion by AvdeevArtem** [aquasecurity/trivy-operator#2574] [Help & Support]
Hello. I use trivy-operator and it uses a lot of outbound traffic to internet because every time when scan job runs it ALWAYS updating vulnerability database. I read Readme in https://github.com/aquasecurity/trivy-db repo and I saw that it automatically update vulnerability database in trivy-db image(this [workflow](https://github.com/aquasecurity/trivy-db/blob/main/.github/workflows/cron.yml#L37-L120) does it).
trivy-operator in my configuration is in a standalone mode. For reducing outbound traffic I've already cached image `public.ecr.aws/aquasecurity/trivy-db:2` on my nodes and use VPC Endpoint to ECR(This is AWS feature to reduces internet traffic)
Is it possible not to update vulnerability db every time?(I can't override it [there](https://github.com/aquasecurity/trivy-operator/blob/aabc9abce2fa98d48f1f4f6e63425b6e7eb6c46b/pkg/plugins/trivy/filesystem.go#L136)

trivy-operator version - `[v0.26.1](https://github.com/aquasecurity/trivy-operator/releases/tag/v0.26.1)`
kubernetes version - `1.32`
trivy version - `0.62.1`
command for scanning - `filesystem` (it's reduce outbound traffic neither, because scan job run exactly where it detected new image and use node images local cache)

This is scan job init container logs.
```
scan-vulnerabilityreport-58cd6b6f75-s7s4c 2025-05-28T05:29:01.286214913Z 2025-05-28T05:29:01Z	INFO	[vulndb] Need to update DB
scan-vulnerabilityreport-58cd6b6f75-s7s4c 2025-05-28T05:29:01.286272324Z 2025-05-28T05:29:01Z	INFO	[vulndb] Downloading vulnerability DB...
scan-vulnerabilityreport-58cd6b6f75-s7s4c 2025-05-28T05:29:01.286279414Z 2025-05-28T05:29:01Z	INFO	[vulndb] Downloading artifact...	repo="public.ecr.aws/aquasecurity/trivy-db:2"
scan-vulnerabilityreport-58cd6b6f75-s7s4c 2025-05-28T05:29:13.264834920Z 13.02 MiB / 64.37 MiB [------------>________________________________________________] 20.23% ? p/s ?25.73 MiB / 64.37 MiB [------------------------>____________________________________] 39.97% ? p/s ?37.17 MiB / 64.37 MiB [----------------------------------->_________________________] 57.75% ? p/s ?48.42 MiB / 64.37 MiB [------------------------------------>___________] 75.23% 60.10 MiB p/s ETA 0s57.42 MiB / 64.37 MiB [------------------------------------------>_____] 89.21% 60.10 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 60.10 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 57.93 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 57.93 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 57.93 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 54.19 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 54.19 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 54.19 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 50.70 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 50.70 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 50.70 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 47.43 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 47.43 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 47.43 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 44.37 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 44.37 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 44.37 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 41.50 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 41.50 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 41.50 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 38.83 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 38.83 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 38.83 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 36.32 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 36.32 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 36.32 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 33.98 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 33.98 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 33.98 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 31.79 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 31.79 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 31.79 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 29.73 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 29.73 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 29.73 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 27.82 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 27.82 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 27.82 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 26.02 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 26.02 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 26.02 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 24.34 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 24.34 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 24.34 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 22.77 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 22.77 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 22.77 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 21.30 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 21.30 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 21.30 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------->] 100.00% 19.93 MiB p/s ETA 0s64.37 MiB / 64.37 MiB [---------------------------------------------------] 100.00% 5.93 MiB p/s 11s2025-05-28T05:29:13Z	INFO	[vulndb] Artifact successfully downloaded	repo="public.ecr.aws/aquasecurity/trivy-db:2"

```
Can you give me advice how to reduce outbound traffic for that?
if it updates trivy-db every 6 hours why we should download db every time?
Thank you!

**Comment by simar7** [comment]
hi @AvdeevArtem - thanks for the question. I think we need to rethink the strategy of how the db is used today. As you mentioned it's redownloaded each time, which is quite wasteful as the DB doesn't update more than every 6 hours.

@afdesk and I will think about potential ways to solve this. We can keep this discussion open to discuss that.

**Reply by simar7** [reply]
cc @itaysk

**Reply by afdesk** [reply]
I have another idea. 
there is a way to create a custom OCI registry and push artifacts there by CronJob.

something like it (didn't test it yet):
<details>
<summary>demo helm chart</summary>

```yaml
apiVersion: v2
name: oci-artifact-sync
description: Deploys a private OCI registry and syncs external OCI artifacts into it
version: 0.1.0
appVersion: "1.0"
---
# values.yaml
registry:
  image: registry:2
  port: 5000

cronjob:
  schedule: "0 */6 * * *"
  orasImage: ghcr.io/oras-project/oras:latest
  artifacts:
    - ghcr.io/aquasecurity/trivy-db:2
    - ghcr.io/aquasecurity/trivy-java-db:1
---
# templates/registry-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: {{ .Values.registry.image }}
          ports:
            - containerPort: {{ .Values.registry.port }}
---
# templates/registry-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  type: ClusterIP
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: {{ .Values.registry.port }}
---
# templates/artifact-sync-cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: artifact-sync
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: oras
              image: {{ .Values.cronjob.orasImage }}
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  mkdir -p /tmp/artifacts
                  cd /tmp/artifacts
                  {{- range .Values.cronjob.artifacts }}
                  oras pull {{ . }}
                  name_tag=$(basename {{ . }})
                  oras push registry:{{ $.Values.registry.port }}/synced-artifacts/$name_tag .
                  {{- end }}
          restartPolicy: OnFailure

```
</details>
