### DISCUSSION TITLE
Trivy-operator v0.9.0 Released!

### DISCUSSION THREAD

**Discussion by chen-keinan** [aquasecurity/trivy-operator#779] [Announcements]
## 🧾 NSA Kubernetes hardening compliance ☑️
You can now use Trivy-operator to scan your Kubernetes cluster for compliance with the NSA Kubernetes hardening guide. Compliance granularity can be controlled using the familiar `reportType: summary|all` field in [clusterComplianceReport.spec](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/specs/nsa-1.0.yaml#L13)  the `clusterComplianceReport.status` will be updated with report finding :
```yaml
apiVersion: aquasecurity.github.io/v1alpha1
kind: ClusterComplianceReport
metadata:
  name: nsa
spec:
  compliance:
    controls:
    - checks:
      - id: AVD-KSV-0012
      description: Check that container is not running as root
      id: "1.0"
      name: Non-root containers
      severity: MEDIUM
    - checks:
      - id: AVD-KSV-0014
      description: Check that container root file system is immutable
      id: "1.1"
      name: Immutable container file systems
      severity: LOW
    id: "0001"
    relatedResources:
    - https://www.nsa.gov/Press-Room/News-Highlights/Article/Article/2716980/nsa-cisa-release-kubernetes-hardening-guidance/
    title: nsa
    version: "1.0"
  cron: '* * * * *'
  reportType: summary
status:
  summaryReport:
    controlCheck:
    - id: "1.0"
      name: Non-root containers
      severity: MEDIUM
      totalFail: 8
    - id: "1.1"
      name: Immutable container file systems
      severity: LOW
      totalFail: 7
  totalCounts:
    failCount: 12
    passCount: 15
  updateTimestamp: "2022-12-05T12:21:30Z"
...
```
for more details : [compliance NSA report 
](https://aquasecurity.github.io/trivy-operator/v0.9.0/compliance/nsa-1.0/)
- Add support for fs scan in client/server mode (#750) 
- Remove Trivys own ns from the exclude list (#752)

 
## Notable fixes 
* fix: close connection on health check (#762)
* fix: reduce server healthz calls (#763)
