### DISCUSSION TITLE
ArgoCD Trivy Operator Report Access

### DISCUSSION THREAD

**Discussion by MT5W4FLOP80** [aquasecurity/trivy-operator#888] [Help & Support]
Hi! 

I am testing out different Docker and Kubernetes security scanning tools and I came across Trivy Operator. I deployed Trivy Operator as a HELM package via ArgoCD. The deployment in my sandbox environment was successful, however I do not understand on how I can access the scan reports when Trivy Operator is deployed via ArgoCD. Would you be able to give me some pointers? I had a look at the documentation at https://aquasecurity.github.io/trivy/dev/tutorials/kubernetes/gitops/, however I didn't understand on how I can retrieve the scan results. Ideally I would like to retrieve reports periodically and post the results via Slack alerts. 

Thank you!

**Comment by chen-keinan** [comment]
@MT5W4FLOP80 there are various options :
1.  `kubectl get vulnerabilityreports --all-namespaces -o wide` (same for [other reports](https://aquasecurity.github.io/trivy-operator/v0.10.2/docs/vulnerability-scanning/))
2. via [grafana](https://aquasecurity.github.io/trivy-operator/v0.10.2/tutorials/grafana-dashboard/)  and [metrics](https://aquasecurity.github.io/trivy-operator/v0.10.2/tutorials/integrations/metrics/)
3. [lens-extension](https://aquasecurity.github.io/trivy-operator/v0.10.2/tutorials/integrations/lens/)
4. [webhook](https://aquasecurity.github.io/trivy-operator/v0.10.2/tutorials/integrations/webhook/)

**Comment by MT5W4FLOP80** [comment]
Hi @chen-keinan! 

Thank you for your response. 

My understanding is that when a webhook config is set then trivy-operator automatically posts the results in JSON format to the URL specified in the webhook configuration. I specified the webhook in the config as shown below, however I did not receive anything on the listening port.

1. Is it possible that my configuration below is incorrect and lacks some parameters? 
2. Also, another question is how can I manually trigger trivy-operator scans when trivy-operator is deployed as Helm package via ArgoCD in Amazon EKS? I am a bit confused when the scans are actually ran in this configuration. When I deployed trivy locally it seemed straightforward since I had access to the kubctl.
3. I also have a question regarding scan reports, my understanding is that the CRDs below should contain scan findings, is that correct? To test the trivy-operator tool, I specified some fake credentials in the helm package configuration of another application within the same K8s cluster, however it seems that trivy-operator did not identify fake creds as exposed credentials. Is my understanding correct that findings are documented in the CRDs below and is my assumption correct that credentials in the HELM configuration would also be picked up by trivy-operator?

![image](https://user-images.githubusercontent.com/103582751/216064770-e8344f79-db6b-47f5-8196-f99c45b5a774.png)


```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: trivy-operator
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.10.2
    helm:
      values: |
        trivy:
          ignoreUnfixed: true
        operator:
          OPERATOR_WEBHOOK_BROADCAST_URL: "http://example.com/trivy/webhook"
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

```

Thank you for your responses!
