### ISSUE TITLE
support honor ephemeral-storage for scan jobs

### ISSUE THREAD

**Issue by 1337andre** [aquasecurity/trivy-operator#1001]
I missed configs like `trivy.resources.requests.ephemeral-storage` or `trivy.resources.limits.ephemeral-storage` to adjust ephemeral-storage for scan jobs.

it would be nice, if scan jobs would honor ephemeral-storage
e.g.
```
    resources:
      limits:
        cpu: 500m
        ephemeral-storage: 300Mi
        memory: 2048M
      requests:
        cpu: 100m
        ephemeral-storage: 300Mi
        memory: 512M
```

I have tried this by my self, but my go skills and test env is to bad :/
https://github.com/1337andre/trivy-operator/commit/6369908ed71a18abe8c41a93e64fc6c013249603
