### ISSUE TITLE
Trivy-operator creates a large number of node-collector pods

### ISSUE THREAD

**Issue by giovannirco** [aquasecurity/trivy-operator#1012]
**What steps did you take and what happened:**

After installing the chart it began creating a lot of `node-collector` pods, in my 40 node cluster within the first 15 minutes there were already more than 1000 pods scheduled, some terminating, some erroring with OutOfCpu, the problem is that with the rate of pods being scheduled I didnt have much time to investigate and had to delete the chart, I couldnt find logs for the node collector pods but I did see the following on the operator logs:
```
{"level":"error","ts":"2023-02-27T16:21:39Z","msg":"Reconciler error","controller":"job","controllerGroup":"batch","controllerKind":"Job","Job":{"name":"node-collector-f4867b9b4","namespace":"trivy-operator"},"namespace":"trivy-operator","name":"node-collector-f4867b9b4","reconcileID":"9f8456b0-3636-4f7c-8c1d-36c3bf3428ec","error":"getting logs: container \"node-collector\" in pod \"node-collector-f4867b9b4-27ldr\" is terminated","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235"}
```

the vulnerability scans works fine for me and this is what I am looking for so I deployed the chart with the following values and it also started scheduling node-collector pods
```
operator:
  # configAuditScannerEnabled the flag to enable configuration audit scanner
  configAuditScannerEnabled: false
  # rbacAssessmentScannerEnabled the flag to enable rbac assessment scanner
  rbacAssessmentScannerEnabled: false
  # infraAssessmentScannerEnabled the flag to enable infra assessment scanner
  infraAssessmentScannerEnabled: false
```

Here is the deployment manifest helm installed:
```
# Source: trivy-operator/charts/trivy-operator/templates/deployment.yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: trivy-operator
    namespace: trivy-operator
    labels:
      helm.sh/chart: trivy-operator-0.11.1
      app.kubernetes.io/name: trivy-operator
      app.kubernetes.io/instance: trivy-operator
      app.kubernetes.io/version: "0.11.1"
      app.kubernetes.io/managed-by: Helm
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app.kubernetes.io/name: trivy-operator
        app.kubernetes.io/instance: trivy-operator
    template:
      metadata:
        labels:
          app.kubernetes.io/name: trivy-operator
          app.kubernetes.io/instance: trivy-operator
      spec:
        serviceAccountName: trivy-operator
        automountServiceAccountToken: true
        containers:
          - name: "trivy-operator"
            image: "ghcr.io/aquasecurity/trivy-operator:0.11.1"
            imagePullPolicy: IfNotPresent
            env:
              - name: OPERATOR_NAMESPACE
                value: trivy-operator
              - name: OPERATOR_TARGET_NAMESPACES
                value: ""
              - name: OPERATOR_EXCLUDE_NAMESPACES
                value: ""
              - name: OPERATOR_TARGET_WORKLOADS
                value: "pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,job"
              - name: OPERATOR_SERVICE_ACCOUNT
                value: "trivy-operator"
              - name: OPERATOR_LOG_DEV_MODE
                value: "false"
              - name: OPERATOR_SCAN_JOB_TIMEOUT
                value: "5m"
              - name: OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT
                value: "10"
              - name: OPERATOR_SCAN_JOB_RETRY_AFTER
                value: "30s"
              - name: OPERATOR_BATCH_DELETE_LIMIT
                value: "10"
              - name: OPERATOR_BATCH_DELETE_DELAY
                value: "10s"
              - name: OPERATOR_METRICS_BIND_ADDRESS
                value: ":8080"
              - name: OPERATOR_METRICS_FINDINGS_ENABLED
                value: "true"
              - name: OPERATOR_METRICS_VULN_ID_ENABLED
                value: "false"
              - name: OPERATOR_HEALTH_PROBE_BIND_ADDRESS
                value: ":9090"
              - name: OPERATOR_VULNERABILITY_SCANNER_ENABLED
                value: "true"
              - name: OPERATOR_VULNERABILITY_SCANNER_SCAN_ONLY_CURRENT_REVISIONS
                value: "true"
              - name: OPERATOR_SCANNER_REPORT_TTL
                value: "24h"
              - name: OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED
                value: "false"
              - name: OPERATOR_RBAC_ASSESSMENT_SCANNER_ENABLED
                value: "false"
              - name: OPERATOR_INFRA_ASSESSMENT_SCANNER_ENABLED
                value: "false"
              - name: OPERATOR_CONFIG_AUDIT_SCANNER_SCAN_ONLY_CURRENT_REVISIONS
                value: "true"
              - name: OPERATOR_EXPOSED_SECRET_SCANNER_ENABLED
                value: "true"
              - name: OPERATOR_WEBHOOK_BROADCAST_URL
                value: ""
              - name: OPERATOR_WEBHOOK_BROADCAST_TIMEOUT
                value: "30s"
              - name: OPERATOR_PRIVATE_REGISTRY_SCAN_SECRETS_NAMES
                value: "{}"
              - name: OPERATOR_ACCESS_GLOBAL_SECRETS_SERVICE_ACCOUNTS
                value: "true"
              - name: OPERATOR_BUILT_IN_TRIVY_SERVER
                value: "false"
              - name: TRIVY_SERVER_HEALTH_CHECK_CACHE_EXPIRATION
                value: "10h"
              - name: OPERATOR_MERGE_RBAC_FINDING_WITH_CONFIG_AUDIT
                value: "false"
            ports:
              - name: metrics
                containerPort: 8080
              - name: probes
                containerPort: 9090
            readinessProbe:
              httpGet:
                path: /readyz/
                port: probes
              initialDelaySeconds: 5
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            livenessProbe:
              httpGet:
                path: /healthz/
                port: probes
              initialDelaySeconds: 5
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 10
            resources:
              {}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              privileged: false
              readOnlyRootFilesystem: true
        securityContext:
          {}
```

I am not sure what could be causing this behaviour and im seeking help for troubleshooting,

**What did you expect to happen:**
The operator would spawn just the necessary pods and if for some reason it couldnt create a node-collector pod it would wait n seconds to try to create a new pod for that workload.

**Anything else you would like to add:**

If I can get just the vulnerability scan working I can go ahead with the most important part of the testing im doing with trivy-operator, but setting `OPERATOR_INFRA_ASSESSMENT_SCANNER_ENABLED = false` didnt do the trick for me

It is worth mentioning the I am also running Cilium v1.12 on this cluster but there are no network policies deployed for trivy-operator namespace and vulnerability reports can work fine and generate reports, I think other scans too and just the infra scan that seems to the having this bug. I just dont know where to get useful info about what is happening

**Environment:**

trivy-operator chart version 0.11.1
Kubernetes version v1.23.14-eks-ffeb93d
