### ISSUE TITLE
imagepullsecrets not used by scan-vulnerabilityreport

### ISSUE THREAD

**Issue by yp28** [aquasecurity/trivy-operator#1036]
**What steps did you take and what happened:**
We have trivy-operator running in our cluster, installed using Helm with the following configuration:
```yaml
operator:
  logDevMode: true
  webhookBroadcastURL: http://postee.postee.svc.cluster.local:8082
  privateRegistryScanSecretsNames: {"development": "docker-credentials"}
trivy:
  ignoreUnfixed: true
```
We have the following `dockerconfigjson`:
```yaml
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXR...FU9In19fQ==
kind: Secret
metadata:
  name: docker-credentials
  namespace: development
type: kubernetes.io/dockerconfigjson
```
That we know is correct, because it is used by our workloads:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: workload
  namespace: development
...
spec:
  containers:
...
    image: docker.io/company/image:6.0
...
  imagePullSecrets:
  - name: docker-credentials
...
```
But we're hitting this error:
```json
{"level":"error","ts":"2023-03-09T09:49:13Z","logger":"reconciler.scan job","msg":"Scan job container","job":"trivy-system/scan-vulnerabilityreport-66d5c89796","container":"log-elastic-status","status.reason":"Error","status.message":"2023-03-09T09:49:11.757Z\t\u001b[31mFATAL\u001b[0m\timage scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:\n\t* unable to inspect the image (docker.io/company/image:bdb69ed23e67efe1cce72e994ad859cc5e44f0d4-dev): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\t* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory\n\t* containerd socket not found: /run/containerd/containerd.sock\n\t* GET https://index.docker.io/v2/company/image/manifests/bdb69ed23e67efe1cce72e994ad859cc5e44f0d4-dev: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:company/image Type:repository]]\n\n\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:254\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:79\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/reconcile/reconcile.go:102\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235"}
```

**What did you expect to happen:**
I would expect the scan job would use the `docker-credentials` secret in the `development` namespace. 

**Anything else you would like to add:**
We've also tried omitting the `privateRegistryScanSecretsNames` configuration in Helm, expecting it would take the `imagePullSecrets` from the workload configuration itself, but with the same results.

**Environment:**
- Trivy-Operator version (use `trivy-operator version`): 0.12.0
- Kubernetes version (use `kubectl version`): v1.24.6
- Cloud provider: Azure AKS
