### ISSUE TITLE
Helm Chart: impossible to set resource requests/limits for Trivy

### ISSUE THREAD

**Issue by d-mankowski-synerise** [aquasecurity/trivy-operator#1044]
**What steps did you take and what happened:**

In the Helm Chart [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/deploy/helm#trivy-configuration) there are fields `trivy.resources.xxx` indicating, that these are configurable. However, the values for resources are [hardcoded](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/templates/trivy-server.yaml#L112) and cannot be set via Helm chart.

In my `values.yml` I have set:

```yaml
trivy:
  tag: 0.38.2
  mode: ClientServer
  serverURL: http://trivy-service.trivy-operator:4954
  serverInsecure: true
  ignoreUnfixed: true
  additionalVulnerabilityReportFields: "Target,Class"
  timeout: "5m0s"
  slow: false
  resources:
    requests:
      cpu: 350m
      memory: 300Mi
    limits:
      cpu: 600m
      memory: 512Mi
```

and yet

```text
$ k describe pod trivy-server-0 | grep Limits -A5
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:      200m
      memory:   512Mi
```

**What did you expect to happen:**

Resources are set like in `values.yml`

**Anything else you would like to add:**

N/A

**Environment:**

- Trivy-Operator version (use `trivy-operator version`):  `{"level":"info","ts":"2023-03-11T19:52:11Z","logger":"main","msg":"Starting operator","buildInfo":{"Version":"0.12.0","Commit":"55d41886e47630757c0a97e824f8b0b79c0d7176","Date":"2023-03-05T09:19:10Z","Executable":""}}`
- Kubernetes version (use `kubectl version`): 1.23.15
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): N/A
