### ISSUE TITLE
TRIVY_INSECURE never set in ClientServer FS mode

### ISSUE THREAD

**Issue by bgoareguer** [aquasecurity/trivy-operator#1048]
**What steps did you take and what happened:**

I run trivy-operator with the following values.yaml:
```yaml
trivy:
  mode: "ClientServer"
  command: "rootfs"
  serverURL: "https://trivy.myorg"
  serverInsecure: "true"
```

**What did you expect to happen:**

I expected to see the `TRIVY_INSECURE` set in all Trivy scan jobs.

But the `TRIVY_INSECURE` is never set and the logs show the following error:
```
2023-03-13T10:32:08.455Z  FATAL  rootfs scan error: scan error: scan failed: failed analysis: failed to store blob (sha256:a8d85f6ca50ff00173c412bb2ca8b945ce29c1c7c0808650a410d40df94a6eff) in cache: unable to store cache on the server: twirp error internal: failed to do request: Post "https://trivy.myorg/twirp/trivy.cache.v1.Cache/PutBlob": x509: certificate signed by unknown authority
```

**Environment:**

- Trivy-Operator version: 0.12.0
- Kubernetes version: 1.25.6
- OS: Ubuntu 20.04
