### ISSUE TITLE
[Helm] unable to download database

### ISSUE THREAD

**Issue by PaulusTM** [aquasecurity/trivy-operator#1062]
**What steps did you take and what happened:**

After the installation via Helm, the Trivy server is unable to chmod the downloaded database.
`FATAL    failed to download vulnerability DB: database download error: download error: failed to download: chmod /home/scanner/.cache/trivy/db/trivy.db: operation not permitted`

**What did you expect to happen:**

Download of database and store it in the PVC mount.

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.12.1
- Kubernetes version (use `kubectl version`): AKS - 1.24.9 

I've add an init container to chown to the right container user:
```yaml
initContainers:
  - name: pvc-chowner
    image: alpine:3.12.0
    command: ["chown", "-R", "65534:65534", "/home/scanner/.cache"]
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      runAsNonRoot: false
      readOnlyRootFilesystem: false
      capabilities:
        drop:
          - ALL
        add:
          - CHOWN
    volumeMounts:
      - mountPath: /home/scanner/.cache
        name: data
```

**Comment by chen-keinan** [comment]
@PaulusTM can you please share the `cm` ?

**Comment by PaulusTM** [comment]
**trivy-operator**
```yaml
apiVersion: v1
data:
  configAuditReports.scanner: Trivy
  node.collector.imageRef: ghcr.io/aquasecurity/node-collector:0.0.5
  report.recordFailedChecksOnly: "true"
  scanJob.compressLogs: "true"
  scanJob.nodeSelector: '{"agentpool":"monitoring"}'
  scanJob.podTemplateContainerSecurityContext: '{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":true}'
  scanJob.tolerations: '[{"effect":"NoSchedule","key":"pool_type","operator":"Equal","value":"monitoring"}]'
  trivy.serverURL: http://trivy-service.trivy-system:4954
  vulnerabilityReports.scanner: Trivy
kind: ConfigMap
metadata:
  creationTimestamp: "2023-03-14T16:28:43Z"
  labels:
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/version: 0.12.1
    argocd.argoproj.io/instance: trivy-operator-in-cluster
    helm.sh/chart: trivy-operator-0.12.1
  name: trivy-operator
  namespace: trivy-system
```

**trivy-operator-trivy-config**
```yaml
apiVersion: v1
data:
  TRIVY_CACHE_DIR: /home/scanner/.cache/trivy
  TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db
  TRIVY_DEBUG: "false"
  TRIVY_LISTEN: 0.0.0.0:4954
  TRIVY_SKIP_UPDATE: "false"
  trivy.additionalVulnerabilityReportFields: ""
  trivy.command: image
  trivy.dbRepository: ghcr.io/aquasecurity/trivy-db
  trivy.dbRepositoryInsecure: "false"
  trivy.ignoreUnfixed: "true"
  trivy.mode: ClientServer
  trivy.repository: ghcr.io/aquasecurity/trivy
  trivy.resources.limits.cpu: 500m
  trivy.resources.limits.memory: 500M
  trivy.resources.requests.cpu: 100m
  trivy.resources.requests.memory: 100M
  trivy.serverURL: http://trivy-service.trivy-system:4954
  trivy.severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
  trivy.slow: "true"
  trivy.supportedConfigAuditKinds: Workload,Service,Role,ClusterRole,NetworkPolicy,Ingress,LimitRange,ResourceQuota
  trivy.tag: 0.38.2
  trivy.timeout: 5m0s
  trivy.useBuiltinRegoPolicies: "true"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-03-14T16:28:43Z"
  labels:
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/version: 0.12.1
    argocd.argoproj.io/instance: trivy-operator-in-cluster
    helm.sh/chart: trivy-operator-0.12.1
  name: trivy-operator-trivy-config
  namespace: trivy-system
```
