### ISSUE TITLE
Wrong AWS region is used when defining a Mirror for an ECR registry repository

### ISSUE THREAD

**Issue by rodrigorfk** [aquasecurity/trivy-operator#1064]
**What steps did you take and what happened:**

I'm trying to use the mirroring capability of the trivy operator to map an ECR registry from one region to another, the reason for that is because I'm using [ECR private image replication](https://docs.aws.amazon.com/AmazonECR/latest/userguide/replication.html), which allows us to pull the image from the same region of the Kubernetes cluster and save with outbound traffic on ECR.

I've deployed the operator with the following helm values:
```yaml
trivy:
  registry:
    mirror:
      "000000000000.dkr.ecr.us-east-1.amazonaws.com": "000000000000.dkr.ecr.eu-west-1.amazonaws.com"
```

And then I've created a deployment with a pod spec as following:
```yaml
containers:
  - name: some-container
    image: 000000000000.dkr.ecr.us-east-1.amazonaws.com/my-app:1.0.0
```

**What did you expect to happen:**

I would expect the mirror to work as intended, and the ECR image to be pulled from the `eu-west-1` region. The mapping of the mirroring is working fine and the  image URL is being changed to the desired region, however the `AWS_REGION` environment variable on the scan job spec was incorrectly defined as `eu-east-1` instead of `eu-west-1`, which breaks the AWS ECR auth performed by trivy, 

**Anything else you would like to add:**

Looking into the source code, the issue is because the `CheckAwsEcrPrivateRegistry` function is being called [here](https://github.com/aquasecurity/trivy-operator/blob/v0.12.1/pkg/plugins/trivy/plugin.go#L797) before the mirroring logic [here](https://github.com/aquasecurity/trivy-operator/blob/v0.12.1/pkg/plugins/trivy/plugin.go#L847), meaning the ECR region logic is looking to the original `c.Image` instead of looking for the `optionalMirroredImage`

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): `0.12.1`
- Kubernetes version (use `kubectl version`): `EKS 1.24`
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 13.2.1
