### ISSUE TITLE
vulnerabilityScannerEnabled parameter doesn't work

### ISSUE THREAD

**Issue by Wyifei** [aquasecurity/trivy-operator#1090]
What steps did you take and what happened:

Helm chart values:
```
operator:
    vulnerabilityScannerEnabled: false
    infraAssessmentScannerEnabled: false
    rbacAssessmentScannerEnabled: false
    vulnerabilityScannerScanOnlyCurrentRevisions: false
fullnameOverride: "${env}-trivy-operator"
trivyOperator:
    vulnerabilityReportsPlugin: ""
```
Trivy opeartor still try to scan the container image even if set vulnerabilityScannerEnabled to false.
![image](https://user-images.githubusercontent.com/65744961/226814093-24157db1-0361-471e-80ec-d8a30cc45eab.png)

What did you expect to happen:
If vulnerabilityScannerEnabled is false, trivy opeartor should stop to scan the container image.

Anything else you would like to add:

[Miscellaneous information that will assist in solving the issue.]

Environment:

Trivy-Operator version (use trivy-operator version): 0.12.1
Kubernetes version (use kubectl version): 1.2.4
OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Amazon Linux2
