### ISSUE TITLE
Metrics endpoint not working

### ISSUE THREAD

**Issue by javixeneize** [aquasecurity/trivy-operator#1098]
Hi

I am trying to integrate trivy operator with grafana, following this guide

https://aquasecurity.github.io/trivy-operator/v0.11.0/tutorials/grafana-dashboard/

Everything is installed, but when forwarding the port, and accessing to localhost:5000/metrics, i have this error

kubectl port-forward service/trivy-operator -n trivy-system 5000:80

Forwarding from 127.0.0.1:5000 -> 80
Forwarding from [::1]:5000 -> 80
Handling connection for 5000
Handling connection for 5000
E0324 16:46:48.604981   23838 portforward.go:407] an error occurred forwarding 5000 -> 80: error forwarding port 80 to pod c51e2125f38ac3db6bf6957fb77069e06d72ff66090c89c4968fe0a88c8e0668, uid : failed to execute portforward in network namespace "/var/run/netns/cni-ade3c652-f609-1a4a-81b9-92fa4ca30853": failed to connect to localhost:80 inside namespace "c51e2125f38ac3db6bf6957fb77069e06d72ff66090c89c4968fe0a88c8e0668", IPv4: dial tcp4 127.0.0.1:80: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found
E0324 16:46:48.605451   23838 portforward.go:233] lost connection to pod

On the same hand, in prometheus, under targets, trivy operator data is not available there.

Any idea what could be the problem?

Thanks

**Comment by chen-keinan** [comment]
@javixeneize to test it with the tutorial I'll have to remove the headless setting 
`kubectl edit service trivy-operator -n trivy-system` and remove the following `clusterIP: None`

or 
`kubectl delete service trivy-operator -n trivy-system`

and deploy this service: 
```yaml
apiVersion: v1
kind: Service
metadata:
  name: trivy-operator
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/version: "0.12.1"
    app.kubernetes.io/managed-by: kubectl
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 80
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator

```
