### ISSUE TITLE
Trivy server doesn't honour http(s) proxy configuration given in helm chart

### ISSUE THREAD

**Issue by sylvainOL** [aquasecurity/trivy-operator#1145]
**What steps did you take and what happened:**

we run trivy operator behind a proxy and use trivy server in order to speed up things.
But config of proxy in trivy operator is not really given to trivy server when using helm.
value is given in configmap but not used.
adding it via env make it work

**What did you expect to happen:**

to be able to use trivy server behind a proxy

**Anything else you would like to add:**

here's an example of the override file:

```yaml
operator:
  builtInTrivyServer: true
  clusterComplianceEnabled: true
  exposedSecretScannerEnabled: true
  metricsVulnIdEnabled: true
  scanJobTimeout: 5m
  # no need to stress the cluster when it is reconciling
  scanJobsConcurrentLimit: 3
  scanJobsRetryDelay: 120s
  vulnerabilityScannerReportTTL: 48h

trivyOperator:
  # scan jobs only communicate with the outside world and the scan container
  # tries to reach docker repos before istio-proxy is ready
  scanJobAnnotations: "sidecar.istio.io/inject=false"
  scanJobPodTemplatePodSecurityContext:
    runAsGroup: 10000
    runAsUser: 10000
  scanJobTolerations:
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      key: CriticalAddonsOnly
      value: "true"

trivy:
  httpProxy: http://my-proxy.corp:3128/
  httpsProxy: http://my-proxy.corp:3128/
  noProxy: so,many,stuff
```

**Environment:**

- Trivy-Operator version (use `trivy-operator version`):  `ghcr.io/aquasecurity/trivy-operator:0.12.1`
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.11+rke2r1", GitCommit:"0f75679e3346160939924550fd3591462a4afec6", GitTreeState:"clean", BuildDate:"2023-02-28T20:43:36Z", GoVersion:"go1.19.6 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}`
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): N/A
