### ISSUE TITLE
Add selectorLabels support to operator and scan-jobs

### ISSUE THREAD

**Issue by humpalu** [aquasecurity/trivy-operator#1203]
**What steps did you take and what happened:**

I add the selectorLabels block in the Values.yaml.

```
selectorLabels:
  app.kubernetes.io/managed-by: "ourteam"
  ourteam/environment: "development"
  ourteam/cost-center: "123456"
  app.kubernetes.io/name: trivy
```

**What did you expect to happen:**

The labels above will be visible on the deployed pods and deployments

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.13.0 Helm version
- Kubernetes version (use `kubectl version`): 1.25.5
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): ?
