### ISSUE TITLE
Vulnerability reports are recreated during controller restart if Image mirroring is used

### ISSUE THREAD

**Issue by rodrigorfk** [aquasecurity/trivy-operator#1204]
**What steps did you take and what happened:**

Let's image that I want to use the fourth option to access private registries as documented [here](https://aquasecurity.github.io/trivy-operator/v0.13.2/tutorials/private-registries/#fourth-option-define-secrets-through-trivy-operator-configuration).

So, I would deploy the operator with the following helm values:
```yaml
operator:
  privateRegistryScanSecretsNames:
    "trivy-operator": "my-registry-auth"
trivy:
  registry:
    mirror:
      "index.docker.io": "mirror.io"
```
The `my-registry-auth` secret would be of type `kubernetes.io/dockerconfigjson` and would contain the following data in `.dockerconfigjson` key:
```json
{
  "auths": {
    "mirror.io": {
      "auth": "dXNlcjE6cGFzczEyMw=="
    }
  }
}
```
And then I've created a deployment with a pod spec as following:
```yaml
containers:
  - name: nginx
    image: nginx:1.16
```

**What did you expect to happen:**

The operator is correctly creating a job to pull the image through the mirror, this behaviour was fixed in #1066 and since then is working fine, however there is one issue with the `podSpecHash` stored in the `VulnerabilityReports` object, instead of storing the hash for the original pod spec, the one stored is for the pod spec with the modified mirroring image, therefore, if the controller is restarted, the internal cache will be empty and the operator will assume there was a change in the pod spec because the store hash does not match with the original pod spec and will schedule another scan for the image, which is unnecessary.

**Anything else you would like to add:**
This issue is only reproduced in you are using image mirroring.

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Trivy-Operator version (use trivy-operator version): 0.13.2
Kubernetes version (use kubectl version): EKS 1.24
OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 13.2.1
