### ISSUE TITLE
Job has reached the specified backoff limit

### ISSUE THREAD

**Issue by rlex** [aquasecurity/trivy-operator#1256]
**What steps did you take and what happened:**

Installed trivy-operator, jobs started appearing, but they crash with "Job has reached the specified backoff limit"
Since job disappears instantly, i can't check logs, and even if i open it during scan progress, there is either nothing or some base64 looking block. It will be nice if i can debug what causes it or how to solve it. Tried with standalone, tried with clientserver, image and filesystem scanning. 

One of scanner had following in logs:

```
2023-06-01T13:45:19.023Z	FATAL	image scan error: scan error: unable to initialize a scanner: unable to initialize the remote docker scanner: 4 errors occurred:
	* unable to inspect the image (10.121.0.9:5000/kube-state-metrics/kube-state-metrics:v2.8.2): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
	* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
	* containerd socket not found: /run/containerd/containerd.sock
	* GET http://10.121.0.9:5000/v2/kube-state-metrics/kube-state-metrics/manifests/v2.8.2: MANIFEST_UNKNOWN: manifest unknown; map[Tag:v2.8.2]
```

Might be related to a fact that k3s uses non-standard containerd socket path?

So far my vulnerabilityreports is empty: 

```
❯ kubectl get vulnerabilityreports --all-namespaces -o wide
No resources found
```

**What did you expect to happen:**

Jobs should complete 

**Anything else you would like to add:**

values:
```
      - operator:
          replicas: 2
          scanJobsConcurrentLimit: 10
          vulnerabilityScannerScanOnlyCurrentRevisions: true
          configAuditScannerScanOnlyCurrentRevisions: true
          scanJobTTL: 5m
          scanJobTimeout: 10m
          builtInTrivyServer: true
          logDevMode: true
      - trivy:
          mode: ClientServer
          command: filesystem
          storageClassName: longhorn
          ignoreUnfixed: true
          slow: true
#          registry:
#            mirror:
#              "docker.io": 10.121.0.9:5000
      - excludeNamespaces: kube-system,trivy-system,renovate
      - trivyOperator:
          scanJobNodeSelector:
            node-role.kubernetes.io/worker: "true"
#          scanJobPodTemplateSecurityContext:
#            runAsUser: 1000
#            runAsGroup: 1000
#            runAsNonRoot: true
      - serviceMonitor:
          enabled: true
      - nodeSelector:
          node-role.kubernetes.io/master: "true"
      - podSecurityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
```

**Environment:**

- Trivy-Operator version (use `trivy-operator version`):
```
2023-06-01T14:50:18Z    INFO    main    Starting operator       {"buildInfo": {"Version":"0.13.2","Commit":"6aad0cce58c40d2634dd1150b186ef123bb83202","Date":"2023-04-27T05:37:42Z","Executable":""}}
```
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2+k3s1", GitCommit:"213d7ad499e166290872f51c63d8eaa2f1fe78b3", GitTreeState:"clean", BuildDate:"2023-05-26T22:14:11Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by chen-keinan** [comment]
@rlex did you got errors on the operator side ?

**Comment by rlex** [comment]
Kyverno is in audit mode, it doesn't actually block anything yet.
It seems setting trivy.timeout to 10m0s helped alot, but i still can't get info about jobs since they get deleted as soon as get completed

**Comment by chen-keinan** [comment]
are you getting any reports at all ? for example can you try this one :
```
kubectl get configauditreports --all-namespaces -o wide
```

**Comment by rlex** [comment]
Yes, config audits are there. Not getting image reports, though

**Comment by chen-keinan** [comment]
are the images stored in public or private registry ?

**Comment by rlex** [comment]
public only

**Comment by chen-keinan** [comment]
do you mind sharing you configmaps : `trivy-operator` and `trivy-operator-trivy-config` ?

**Comment by rlex** [comment]
operator:
```
apiVersion: v1
data:
  compliance.failEntriesLimit: "10"
  configAuditReports.scanner: Trivy
  node.collector.imageRef: ghcr.io/aquasecurity/node-collector:0.0.6
  nodeCollector.volumeMounts: '[{"mountPath":"/var/lib/etcd","name":"var-lib-etcd","readOnly":true},{"mountPath":"/var/lib/kubelet","name":"var-lib-kubelet","readOnly":true},{"mountPath":"/var/lib/kube-scheduler","name":"var-lib-kube-scheduler","readOnly":true},{"mountPath":"/var/lib/kube-controller-manager","name":"var-lib-kube-controller-manager","readOnly":true},{"mountPath":"/etc/systemd","name":"etc-systemd","readOnly":true},{"mountPath":"/lib/systemd/","name":"lib-systemd","readOnly":true},{"mountPath":"/etc/kubernetes","name":"etc-kubernetes","readOnly":true},{"mountPath":"/etc/cni/net.d/","name":"etc-cni-netd","readOnly":true}]'
  nodeCollector.volumes: '[{"hostPath":{"path":"/var/lib/etcd"},"name":"var-lib-etcd"},{"hostPath":{"path":"/var/lib/kubelet"},"name":"var-lib-kubelet"},{"hostPath":{"path":"/var/lib/kube-scheduler"},"name":"var-lib-kube-scheduler"},{"hostPath":{"path":"/var/lib/kube-controller-manager"},"name":"var-lib-kube-controller-manager"},{"hostPath":{"path":"/etc/systemd"},"name":"etc-systemd"},{"hostPath":{"path":"/lib/systemd"},"name":"lib-systemd"},{"hostPath":{"path":"/etc/kubernetes"},"name":"etc-kubernetes"},{"hostPath":{"path":"/etc/cni/net.d/"},"name":"etc-cni-netd"}]'
  report.recordFailedChecksOnly: "true"
  scanJob.compressLogs: "true"
  scanJob.nodeSelector: '{"node-role.kubernetes.io/worker":"true"}'
  scanJob.podTemplateContainerSecurityContext: '{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":true}'
  trivy.serverURL: http://trivy-service.trivy-system:4954
  vulnerabilityReports.scanner: Trivy
```

trivy:
```
apiVersion: v1
data:
  TRIVY_CACHE_DIR: /home/scanner/.cache/trivy
  TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db
  TRIVY_DEBUG: "false"
  TRIVY_LISTEN: 0.0.0.0:4954
  TRIVY_SKIP_UPDATE: "false"
  trivy.additionalVulnerabilityReportFields: ""
  trivy.command: image
  trivy.dbRepository: ghcr.io/aquasecurity/trivy-db
  trivy.dbRepositoryInsecure: "false"
  trivy.ignoreUnfixed: "true"
  trivy.javaDbRepository: ghcr.io/aquasecurity/trivy-java-db
  trivy.mode: ClientServer
  trivy.repository: ghcr.io/aquasecurity/trivy
  trivy.resources.limits.cpu: 500m
  trivy.resources.limits.memory: 500M
  trivy.resources.requests.cpu: 100m
  trivy.resources.requests.memory: 100M
  trivy.serverURL: http://trivy-service.trivy-system:4954
  trivy.severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
  trivy.slow: "true"
  trivy.supportedConfigAuditKinds: Workload,Service,Role,ClusterRole,NetworkPolicy,Ingress,LimitRange,ResourceQuota
  trivy.tag: 0.40.0
  trivy.timeout: 10m0s
  trivy.useBuiltinRegoPolicies: "true"
```

I tried both FS and image scanning, currently on image.
