### ISSUE TITLE
No warnings or failed cis benchmarks

### ISSUE THREAD

**Issue by yanehi** [aquasecurity/trivy-operator#1306]
**What steps did you take and what happened:**
I get different results for CIS benchmarks when I use kube-bench and the trivy operator.

When I run the built-in scanner of the trivy-operator for cis benchmarks I don't get failed checks. All 116 checks are successful, although I know that one or the other should at least throw a warning.

Prometheus output via Servicemonitor
````
trivy_cluster_compliance{container="trivy-operator", description="CIS Kubernetes Benchmarks", endpoint="metrics",  job="trivy-operator", service="trivy-operator", status="Pass", title="CIS Kubernetes Benchmarks v1.23"} 116
````

Also in the clustercompliance resource I can see that no checks fail:
````
kubectl clustercompliancereports cis -o yaml 
````

When I run the kube-bench job in the same cluster and context, I get the expected warnings and errors for the cis benchmarks.

```
kubectl apply -f https://raw.githubusercontent.com/aquasecurity/kube-bench/main/job.yaml
kubectl kube-bench-<id> -f
```

**What did you expect to happen:**
I expect to get the same warnings and errors for the CIS benchmarks. Regardless of which scanner I use for this.

**HELM Values:**

```
resources:
  limits:
    cpu: 150m
    memory: 100M
trivy:
  ignoreUnfixed: true
  mode: ClientServer
operator:
  configAuditScannerEnabled: false
  vulnerabilityScannerReportTTL: "86400s"
  vulnerabilityScannerScanOnlyCurrentRevisions: true
  rbacAssessmentScannerEnabled: false
  infraAssessmentScannerEnabled: false
  exposedSecretScannerEnabled: false
compliance:
  reportType: all
  # for test purposes currently set every minute 
  cron: "* * * * *"
serviceMonitor:
  enabled: true
```

**Environment:**
- Trivy-Operator (HELM Cart version): `0.14.1`
- Trivy-Operator (Image version):`ghcr.io/aquasecurity/trivy-operator:0.14.1`
- Kubernetes version: `v1.23.7`
- OS: Linux

**Comment by chen-keinan** [comment]
@yanehi when you getting the report with the following command , do you see fail test or warn ?
`kubectl clustercompliancereports cis -o yaml `

**Comment by tibuntu** [comment]
Hi @chen-keinan I am in the same team as @yanehi. Unfortunately we do not.

**Comment by chen-keinan** [comment]
> Hi @chen-keinan I am in the same team as @yanehi. Unfortunately we do not.

why you expect for it to threw warning ?

**Comment by tibuntu** [comment]
Not sure if I understand you correctly. According to the results of kube-bench we have ~10 checks in the CIS scan that are not passing. Shouldn't the trivy operator detect the same results?

Checks with same IDs as in the kube-bench CIS scan are shown as passing when performed by the operator.

**Comment by chen-keinan** [comment]
> 
> Checks with same IDs as in the kube-bench CIS scan are shown as passing when performed by the operator.

checks that are `failing` or you get `warning` ?

**Comment by chen-keinan** [comment]
I see that `infraAssessmentScannerEnabled` has been disabled , it should be `true` , compliance reports are produced from infra assessment checks

**Comment by tibuntu** [comment]
@chen-keinan 

This is the summary of the kube-bench job:
```
== Summary policies ==
0 checks PASS
0 checks FAIL
30 checks WARN
0 checks INFO

== Summary total ==
21 checks PASS
4 checks FAIL
35 checks WARN
0 checks INFO
```

One of the failing checks is:
```
[FAIL] 2.2 Ensure that the --client-cert-auth argument is set to true (Automated)
```

The same check passes in the report generated by trivy-operator:

```
    - id: "2.2"
      name: Ensure that the --client-cert-auth argument is set to true
      severity: CRITICAL
      totalFail: 0
```

this is the CIS scan summary of the trivy-operator:
```
status:
  summary:
    passCount: 116
```

If I am not mistaken we had `infraAssessmentScannerEnabled` set to `true` at some point. But it caused no difference.

**Comment by chen-keinan** [comment]
@tibuntu do you mind perform another test with  `infraAssessmentScannerEnabled=true` ?  it will not work without it.
also you could check the `clusterInfraAssessmentReport` produce data.

**Comment by tibuntu** [comment]
Sure thing!

I've updated the relevant Helm values:

```
      operator:
        configAuditScannerEnabled: false
        vulnerabilityScannerReportTTL: "86400s"
        vulnerabilityScannerScanOnlyCurrentRevisions: true
        rbacAssessmentScannerEnabled: false
        infraAssessmentScannerEnabled: true
        exposedSecretScannerEnabled: false
      compliance:
        reportType: all
        cron: "* * * * *"
```

CIS result is unchanged:
```
  summary:
    passCount: 116
  updateTimestamp: "2023-06-18T08:11:00Z"
```

I have seen the `node-collector-*` pods when testing the functionality on Friday, however this time no such pod was created. But I can see that the operator has started the related worker:

```
{"level":"info","ts":"2023-06-18T08:09:36Z","msg":"Starting workers","controller":"infraassessmentreport","controllerGroup":"aquasecurity.github.io","controllerKind":"InfraAssessmentReport","worker count":1}
```

**Comment by tibuntu** [comment]
Btw. the Kubernetes version initially reported by @yanehi is not correct. The cluster we are using to test the functionality was recently updated to `v1.25.6`

**Comment by chen-keinan** [comment]
> ClusterInfraAssessmentReport

what is the output of this command : 
```
kubectl get clusterinfraassessmentreport -o wide 
```

**Comment by tibuntu** [comment]
For some reason it simply doesn't exist:

```
> kubectl get clusterinfraassessmentreport -o wide
No resources found
```

```
> kubectl get clusterinfraassessmentreport
No resources found
```

same for the infraassesmentreport
```
> kubectl get infraassessmentreport -A
No resources found
```

Just to provide as much details as possible, these are all environment variables set on the trivy-operator deployment:

```
        - name: OPERATOR_NAMESPACE
          value: security
        - name: OPERATOR_TARGET_NAMESPACES
        - name: OPERATOR_EXCLUDE_NAMESPACES
          value: kube-system,kube-public,kube-node-lease,ingress-nginx
        - name: OPERATOR_TARGET_WORKLOADS
          value: pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,job
        - name: OPERATOR_SERVICE_ACCOUNT
          value: trivy-operator
        - name: OPERATOR_LOG_DEV_MODE
          value: "false"
        - name: OPERATOR_SCAN_JOB_TTL
        - name: OPERATOR_SCAN_JOB_TIMEOUT
          value: 5m
        - name: OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT
          value: "10"
        - name: OPERATOR_CONCURRENT_NODE_COLLECTOR_LIMIT
          value: "1"
        - name: OPERATOR_SCAN_JOB_RETRY_AFTER
          value: 30s
        - name: OPERATOR_BATCH_DELETE_LIMIT
          value: "10"
        - name: OPERATOR_BATCH_DELETE_DELAY
          value: 10s
        - name: OPERATOR_METRICS_BIND_ADDRESS
          value: :8080
        - name: OPERATOR_METRICS_FINDINGS_ENABLED
          value: "true"
        - name: OPERATOR_METRICS_VULN_ID_ENABLED
          value: "false"
        - name: OPERATOR_HEALTH_PROBE_BIND_ADDRESS
          value: :9090
        - name: OPERATOR_VULNERABILITY_SCANNER_ENABLED
          value: "true"
        - name: OPERATOR_VULNERABILITY_SCANNER_SCAN_ONLY_CURRENT_REVISIONS
          value: "true"
        - name: OPERATOR_SCANNER_REPORT_TTL
          value: 24h
        - name: OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED
          value: "false"
        - name: OPERATOR_RBAC_ASSESSMENT_SCANNER_ENABLED
          value: "false"
        - name: OPERATOR_INFRA_ASSESSMENT_SCANNER_ENABLED
          value: "true"
        - name: OPERATOR_CONFIG_AUDIT_SCANNER_SCAN_ONLY_CURRENT_REVISIONS
          value: "true"
        - name: OPERATOR_EXPOSED_SECRET_SCANNER_ENABLED
          value: "false"
        - name: OPERATOR_METRICS_EXPOSED_SECRET_INFO_ENABLED
          value: "false"
        - name: OPERATOR_WEBHOOK_BROADCAST_URL
        - name: OPERATOR_WEBHOOK_BROADCAST_TIMEOUT
          value: 30s
        - name: OPERATOR_SEND_DELETED_REPORTS
          value: "false"
        - name: OPERATOR_PRIVATE_REGISTRY_SCAN_SECRETS_NAMES
          value: '{}'
        - name: OPERATOR_ACCESS_GLOBAL_SECRETS_SERVICE_ACCOUNTS
          value: "true"
        - name: OPERATOR_BUILT_IN_TRIVY_SERVER
          value: "false"
        - name: TRIVY_SERVER_HEALTH_CHECK_CACHE_EXPIRATION
          value: 10h
        - name: OPERATOR_MERGE_RBAC_FINDING_WITH_CONFIG_AUDIT
          value: "false"
        - name: OPERATOR_CLUSTER_COMPLIANCE_ENABLED
          value: "true"
```

additional variables from the `trivy-operator` ConfigMap:

```
  compliance.failEntriesLimit: "10"
  node.collector.imageRef: ghcr.io/aquasecurity/node-collector:0.0.6
  nodeCollector.volumeMounts: '[{"mountPath":"/var/lib/etcd","name":"var-lib-etcd","readOnly":true},{"mountPath":"/var/lib/kubelet","name":"var-lib-kubelet","readOnly":true},{"mountPath":"/var/lib/kube-scheduler","name":"var-lib-kube-scheduler","readOnly":true},{"mountPath":"/var/lib/kube-controller-manager","name":"var-lib-kube-controller-manager","readOnly":true},{"mountPath":"/etc/systemd","name":"etc-systemd","readOnly":true},{"mountPath":"/lib/systemd/","name":"lib-systemd","readOnly":true},{"mountPath":"/etc/kubernetes","name":"etc-kubernetes","readOnly":true},{"mountPath":"/etc/cni/net.d/","name":"etc-cni-netd","readOnly":true}]'
  nodeCollector.volumes: '[{"hostPath":{"path":"/var/lib/etcd"},"name":"var-lib-etcd"},{"hostPath":{"path":"/var/lib/kubelet"},"name":"var-lib-kubelet"},{"hostPath":{"path":"/var/lib/kube-scheduler"},"name":"var-lib-kube-scheduler"},{"hostPath":{"path":"/var/lib/kube-controller-manager"},"name":"var-lib-kube-controller-manager"},{"hostPath":{"path":"/etc/systemd"},"name":"etc-systemd"},{"hostPath":{"path":"/lib/systemd"},"name":"lib-systemd"},{"hostPath":{"path":"/etc/kubernetes"},"name":"etc-kubernetes"},{"hostPath":{"path":"/etc/cni/net.d/"},"name":"etc-cni-netd"}]'
  report.recordFailedChecksOnly: "true"
  scanJob.compressLogs: "true"
  scanJob.podTemplateContainerSecurityContext: '{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":true}'
  vulnerabilityReports.scanner: Trivy
```

**Comment by chen-keinan** [comment]
> For some reason it simply doesn't exist:
> 
> ```
> > kubectl get clusterinfraassessmentreport -o wide
> No resources found
> ```
> 
> ```
> > kubectl get clusterinfraassessmentreport
> No resources found
> ```
> 
> same for the infraassesmentreport
> 
> ```
> > kubectl get infraassessmentreport -A
> No resources found
> ```
> 


you should have something, it explain why compliance report do no show infra data 

btw: are you running on managed cluster (cloud) or on prem?

I suggest to do another simple test , perform the following , lets clean up env and start fresh 

1. uninstall trivy-operator via helm
2. delete all CRD
```
kubectl delete crd vulnerabilityreports.aquasecurity.github.io
kubectl delete crd exposedsecretreports.aquasecurity.github.io
kubectl delete crd configauditreports.aquasecurity.github.io
kubectl delete crd clusterconfigauditreports.aquasecurity.github.io
kubectl delete crd rbacassessmentreports.aquasecurity.github.io
kubectl delete crd infraassessmentreports.aquasecurity.github.io
kubectl delete crd clusterrbacassessmentreports.aquasecurity.github.io
kubectl delete crd clustercompliancereports.aquasecurity.github.io
kubectl delete crd clusterinfraassessmentreports.aquasecurity.github.io
kubectl delete crd clusterconfigauditreports.aquasecurity.github.io
``
3. install operator with default values

**Comment by tibuntu** [comment]
That was a good idea it seems :) 

1. Deleted the current trivy-operator release via ArgoCD
2. Removed all CRDs
```
customresourcedefinition.apiextensions.k8s.io "vulnerabilityreports.aquasecurity.github.io" deleted
customresourcedefinition.apiextensions.k8s.io "exposedsecretreports.aquasecurity.github.io" deleted
customresourcedefinition.apiextensions.k8s.io "configauditreports.aquasecurity.github.io" deleted
customresourcedefinition.apiextensions.k8s.io "clusterconfigauditreports.aquasecurity.github.io" deleted
customresourcedefinition.apiextensions.k8s.io "rbacassessmentreports.aquasecurity.github.io" deleted
customresourcedefinition.apiextensions.k8s.io "infraassessmentreports.aquasecurity.github.io" deleted
customresourcedefinition.apiextensions.k8s.io "clusterrbacassessmentreports.aquasecurity.github.io" deleted
customresourcedefinition.apiextensions.k8s.io "clustercompliancereports.aquasecurity.github.io" deleted
customresourcedefinition.apiextensions.k8s.io "clusterinfraassessmentreports.aquasecurity.github.io" deleted
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "clusterconfigauditreports.aquasecurity.github.io" not found
```

3. Installed the operator manually via helm
```
helm install trivy-operator --namespace security aqua/trivy-operator --version 0.14.1
```

Now several `node-collector-*` pods showed up, e.g.: `node-collector-8b6cf59b6-zx46z`

I see lots of `infraAssesmentReports`:
```
> kubectl get infraassessmentreport -A
NAMESPACE     NAME                                                         SCANNER   AGE
kube-system   cronjob-backup-etcd                                          Trivy     91s
kube-system   pod-kube-apiserver-k8s-cp-01.test.bit.adacor.host            Trivy     105s
kube-system   pod-kube-apiserver-k8s-cp-02.test.bit.adacor.host            Trivy     2m14s
kube-system   pod-kube-apiserver-k8s-cp-03.test.bit.adacor.host            Trivy     2m6s
kube-system   pod-kube-controller-manager-k8s-cp-01.test.bit.adacor.host   Trivy     95s
kube-system   pod-kube-controller-manager-k8s-cp-02.test.bit.adacor.host   Trivy     101s
kube-system   pod-kube-controller-manager-k8s-cp-03.test.bit.adacor.host   Trivy     2m20s
kube-system   pod-kube-scheduler-k8s-cp-01.test.bit.adacor.host            Trivy     91s
kube-system   pod-kube-scheduler-k8s-cp-02.test.bit.adacor.host            Trivy     115s
kube-system   pod-kube-scheduler-k8s-cp-03.test.bit.adacor.host            Trivy     110s
kube-system   service-kube-prometheus-stack-kube-scheduler                 Trivy     95s
```

same for clusterinfraassessmentreports:
```
> k get clusterinfraassessmentreports.aquasecurity.github.io -A
NAME                                      SCANNER   AGE
node-k8s-cp-01.<redact>       Trivy     86s
node-k8s-cp-02.<redact>       Trivy     2m33s
node-k8s-cp-03.<redact>       Trivy     2m9s
node-k8s-worker-01.<redact>   Trivy     102s
node-k8s-worker-02.<redact>   Trivy     2m27s
node-k8s-worker-03.<redact>   Trivy     119s
```

And best thing is, the CIS scan has proper results:
```
status:
  summary:
    failCount: 36
    passCount: 80
```

I am going to check if there is any difference on the trivy-operator deployment / configmaps / secrets that I can find that explains the different behaviour.

**Comment by tibuntu** [comment]
Ok so here is the final result.

I kept deleting the Helm-Release via ArgoCD, also always deleted the CRDs, and then re-deployed with several, adapted values.

Got it working now with the following values:

```
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
        excludeNamespaces: "kube-system,kube-public,kube-node-lease,ingress-nginx"
        trivy:
          ignoreUnfixed: true
          serverURL: https://some-url
          mode: ClientServer
        operator:
          configAuditScannerEnabled: true
          vulnerabilityScannerReportTTL: "86400s"
          vulnerabilityScannerScanOnlyCurrentRevisions: true
          rbacAssessmentScannerEnabled: false
          infraAssessmentScannerEnabled: true
          exposedSecretScannerEnabled: false
        compliance:
          reportType: all
          cron: "* * * * *"
        serviceMonitor:
          enabled: true
```

Setting `configAuditScannerEnabled: false` was the key factor here.

I am unsure if the current documentation reflects that requirement for proper clustercompliancereports?

Anyways, big thanks for your help and fast replies!
