### ISSUE TITLE
Possibility to set the ImagePullPolicy for scan-vulnerabilities Jobs

### ISSUE THREAD

**Issue by yanehi** [aquasecurity/trivy-operator#1339]
## Description
I would like to run my trivy-operator instance in standalone mode in an air-gapped environment, so I don't have to run a trivy-server in my cluster. For this I build my own trivy-image and download the necessary DBs with the vulnerabilities.

I host this image in my registry, build it in regular intervals and reference it in my trivy-operator config.

The `scan-vulnerabilities-<random-string>` jobs in my cluster then use my own trivy-images, which contains the databases.

## Problem
However, I have no way in the trivy-operator config to set the ImagePullPolicy to Always. This is always set to PullIfNotPresent according to my research so far. So I can build my trivy-image with the vulnerability databases regularly, but my jobs always use the present version of the image on the machine.

## Possible solution
I would like to be able to control the ImagePullPolicy for the trivy-image via the values of the trivy-operator.
```
trivy:
  # -- createConfig indicates whether to create config objects
  createConfig: true
  image:
    registry: <custom-registry>
    repository: <custom-trivy-image>
    tag: 0.42.0
    imagePullPolicy: Always # <-- Option to set the  imagePullPolicy
```

I guess that the changes have to be added to the following files. However, I am not completely sure:

- https://github.com/aquasecurity/trivy-operator/blob/main/pkg/plugins/trivy/plugin.go#L48
- https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/templates/config.yaml#L93
- https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L245
