### ISSUE TITLE
Ignorelist should work for (Cluster)RbacAssessmentReport

### ISSUE THREAD

**Issue by m-hofmann** [aquasecurity/trivy-operator#1366]
As described in [this discussion](https://github.com/aquasecurity/trivy-operator/discussions/1305), trivy-operator does not support ignorelisting vulnerabilities for resources of type ClusterRbacAssessmentReport or RbacAssessmentReport. 

Ideally, as a user I want to configure vulnerability IDs related to roles and rolebindings similar to how it works for other resource types: 

```
ignoreFile: |
    # allow management of secrets for admin roles
    KSV041
    AVD-KSV-0041
    # some default roles in our cluster use wildcards verbs
    KSV044
    AVD-KSV-0044
```
This is necessary for us, as our clusters (using VMWare TKGI) come with some pre-installed roles that violate the above rulesets; however we cannot modify these default roles. Therefore we'd like to suppress the alerts. 

Until the feature is implemented, this limitation could be published in the [relevant documentation](https://aquasecurity.github.io/trivy/v0.19.2/vulnerability/examples/filter/).

**Comment by chen-keinan** [comment]
@m-hofmann thanks for this input

**Comment by schuman0** [comment]
Related: https://github.com/aquasecurity/trivy-operator/issues/1517

**Comment by Kouzi99** [comment]
Is there any plan for that. We are trying to ignore some misconfiguration check for some namespace, but we dont want to tunr off all kind of snacs for this namespaces

**Comment by erhhung** [comment]
Just for the record, the ignoreFile also doesn't work for (Cluster)InfraAssessmentReport. For example:

```yaml
trivy:
  ignoreFileName: .trivyignore.yaml
  ignoreFile: |
    misconfigurations:
      - id: AVD-KCV-0086 # Do not override node hostnames.
        statement: RKE2 sets node-name equal to hostname.
```
