### ISSUE TITLE
SBOM Report: wrong type of SpecVersion field

### ISSUE THREAD

**Issue by takumakume** [aquasecurity/trivy-operator#1377]
**What steps did you take and what happened:**

The type of the SpecVersion field in the CycloneDX SBOM is `string` .

https://cyclonedx.org/docs/1.4/json/#specVersion

Currently it is `int`.

```yaml
apiVersion: aquasecurity.github.io/v1alpha1
kind: SbomReport
(snip)
    specVersion: 5
    version: 1
  scanner:
    name: Trivy
    vendor: Aqua Security
    version: 0.42.0
(snip)
```
> specVersion: 5

https://github.com/CycloneDX/cyclonedx-go/blob/v0.7.1/cyclonedx.go#L479

```go
const (
	SpecVersion1_0 SpecVersion = iota + 1 // 1.0
	SpecVersion1_1                        // 1.1
	SpecVersion1_2                        // 1.2
	SpecVersion1_3                        // 1.3
	SpecVersion1_4                        // 1.4
)
```

This is the reason why the SBOM format cannot be interpreted when the SBOM is sent to a third-party system via webhook.

**What did you expect to happen:**

**Anything else you would like to add:**

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.15.0
- Kubernetes version (use `kubectl version`): 1.26
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
