### ISSUE TITLE
Scan jobs are failing with "FATAL multiple targets cannot be specified" if scanJobCompressLogs is false

### ISSUE THREAD

**Issue by Ingradi** [aquasecurity/trivy-operator#1504]
**What steps did you take and what happened:**

After installing trivy operator via helm with `--set "trivyOperator.scanJobCompressLogs=false"` no vulnerability reports are generated in cluster. The reported problem is `FATAL   multiple targets cannot be specified`. 
Installing same chart in same cluster without the mentioned option fixes the problem.

**What did you expect to happen:**

Vulnerability reports are generated regardless of `scanJobCompressLogs` setting.

**Anything else you would like to add:**

After checking the job template we found the following:
```yaml
containers:
  - args:
    - --cache-dir
    - /tmp/trivy/.cache
    - --quiet
    - image
    - --scanners
    - vuln,secret
    - ""
    - ""
    - --format
    - json
    - --server
    - <TRIVY SERVER URI>
    - <IMAGE TO BE SCANNED>
    - --slow
    - --image-config-scanners
    - secret
    - --list-all-pkgs
    command:
    - trivy
```
We tried to run the trivy command via cli with exactly the same arguments `trivy --cache-dir /tmp/trivy/.cache --quiet image --scanners vuln,secret "" "" --format json --server <TRIVY SERVER URI> <IMAGE TO BE SCANNED> --slow --image-config-scanners secret --list-all-pkgs` and did get the same error as specified above. It seems that the two empty string args are causing this issue.

Without scanJobCompressLogs flag the job definition is like:
```yaml
containers:
  - args:
    - -c
    - trivy image --slow '<IMAGE TO BE SCANNED>'
      --scanners vuln,secret --image-config-scanners secret     --cache-dir
      /tmp/trivy/.cache --quiet --list-all-pkgs --format json --server '<TRIVY SERVER URI>'
      > /tmp/scan/<CONTAINER>.json &&  bzip2 -c /tmp/scan/<CONTAINER>.json
      | base64
    command:
    - /bin/sh
```
which does not contain these empty strings as arguments. And this configuration seems to work just fine.

**Environment:**

- Trivy-Operator version: 0.16.0
- Kubernetes version: v1.24.16
- OS: not applikable
