### ISSUE TITLE
0.16.0 - scan error: unable to initialize a scanner

### ISSUE THREAD

**Issue by rtalipov** [aquasecurity/trivy-operator#1524]
**What steps did you take and what happened:**

Vulnerability scans are failing with the error:

```
2023-09-19T09:10:30Z	ERROR	reconciler.scan job	Scan job container	{"job": "trivy-operator/scan-vulnerabilityreport-55c54c8f5d", "container": "setting-cfg", "status.reason": "Error", "status.message": "2023-09-19T09:10:26.311Z\t\u001b[31mFATAL\u001b[0m\timage scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:\n\t* unable to inspect the image (12345678910.dkr.ecr.eu-west-1.amazonaws.com/base/infra/busybox:1.34): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\t* containerd socket not found: /run/containerd/containerd.sock\n\t* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory\n\t* GET https://12345678910.dkr.ecr.eu-west-1.amazonaws.com/v2/base/infra/busybox/manifests/1.34: unexpected status code 401 Unauthorized: Not Authorized\n\n\n\n"}
github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob
	/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:299
github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).reconcileJobs.func1
	/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:81
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/reconcile/reconcile.go:103
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:118
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:314
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:265
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:226
```
Trivy-operator was upgraded from 0.15.1 to 0.16.0. After downgrage to 0.15.1 getting the same errors. All scan jobs are failing

**What did you expect to happen:**
Vulnerability scans should be successful 

**Anything else you would like to add:**
Tried the actions in #1400 by removing crd's and re-installing the operator but hitting the same problem
Helm values:
```
                targetWorkloads: "pod,replicationcontroller,statefulset,daemonset,cronjob,job"
                image:
                  registry: "{{values.imageRegistry}}"
                  repository: "aquasecurity/trivy-operator"
                operator:
                  logDevMode: true
                  sbomGenerationEnabled: false
                  configAuditScannerEnabled: false
                  rbacAssessmentScannerEnabled: false
                  infraAssessmentScannerEnabled: false
                  clusterComplianceEnabled: false
                  exposedSecretScannerEnabled: false
                  webhookBroadcastURL: "http://postee:8082"
                  image:
                    registry: "{{values.imageRegistry}}"
                    repository: "aquasecurity/trivy-operator"
                trivyOperator:
                  skipInitContainers: true
                trivy:
                  image:
                    registry: "{{values.imageRegistry}}"
                    repository: "aquasecurity/trivy"
                   additionalVulnerabilityReportFields: CVSS, Class, PackageType
                  ignoreUnfixed: true
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 500m
                    memory: 512Mi
```

**Environment:**

- Trivy-Operator version: 0.16.0
- Kubernetes version (use `kubectl version`): EKS v1.24.16
