### ISSUE TITLE
Vulnerability report is missing a few CVEs that Trivy normally detects

### ISSUE THREAD

**Issue by d-mankowski-synerise** [aquasecurity/trivy-operator#1528]
**What steps did you take and what happened:**

VulnerabilityReport produced by trivy-operator is missing a few CVEs compared to the output from locally executed `trivy image xxx`.

Vulnerability Report made by Trivy Operator: [https://pastebin.com/r6ArgyDG](https://pastebin.com/r6ArgyDG)

Scan output from locally executed Trivy: [https://pastebin.com/VrcuSx6f](https://pastebin.com/VrcuSx6f)

Sorry for pastebin, reports are too long to post them on GH (max 65k chars)

For example, these vulnerabilities from the application layer are missing in the report:
<img width="1474" alt="image" src="https://github.com/aquasecurity/trivy-operator/assets/101267779/594e2a95-63dc-4f34-8d59-09c1321d0ee0">

trivy-operator config:

```yaml
---
targetWorkloads: "replicaset,replicationcontroller,statefulset,daemonset,cronjob,pod"

trivy:
  mode: ClientServer
  serverURL: http://trivy-service.trivy-operator:4954
  serverInsecure: true
  ignoreUnfixed: true
  additionalVulnerabilityReportFields: "Target,Class"
  timeout: "5m0s"
  slow: false
  resources:
    requests:
      cpu: 350m
      memory: 300Mi
    limits:
      cpu: 600m
      memory: 512Mi

trivyOperator:
  scanJobCompressLogs: true

resources:
  requests:
    cpu: 300m
    memory: 1536Mi
  limits:
    cpu: 500m
    memory: 2048Mi

operator:
  sbomGenerationEnabled: true
  scanJobTTL: 10m
  scanJobsConcurrentLimit: 5
  rbacAssessmentScannerEnabled: false
  infraAssessmentScannerEnabled: false
  builtInTrivyServer: true
  metricsFindingsEnabled: true
  metricsVulnIdEnabled: false
  metricsExposedSecretInfo: true
  metricsConfigAuditInfo: true
  metricsRbacAssessmentInfo: false
  metricsInfraAssessmentInfo: false
  exposedSecretScannerEnabled: true
  webhookBroadcastURL: "http://postee.trivy-operator:8082"
  logDevMode: false

serviceMonitor:
  enabled: true
  namespace: trivy-operator
  interval: 1m
```

</details>

**What did you expect to happen:**

No diff

**Anything else you would like to add:**

Both scans were execute with trivy 0.44.1

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.16.0
- Kubernetes version (use `kubectl version`): 1.27.3
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS Ventura
