### ISSUE TITLE
Handle dbRepositoryInsecure in client-server trivy scenario

### ISSUE THREAD

**Issue by miecio45** [aquasecurity/trivy-operator#1590]
**What steps did you take and what happened:**

In order to use local zot registry for caching java database I configured trivy operator with helm values
```
operator:
  builtInTrivyServer: true

trivy: 
  javaDbRegistry: "cache:5000"
  javaDbRepository: "trivy-java-db"
  dbRepositoryInsecure: "true"
```

resulting with `trivy-operator-trivy-config` configmap containing

```
 trivy.dbRepositoryInsecure: "true"
 trivy.javaDbRepository: cache:5000/trivy-java-db
 trivy.mode: ClientServer
```
 Unfortunately scanjobs does not have env `TRIVY_INSECURE` set up and tries to use SSL connection to cache

**What did you expect to happen:**

I would like to have `TRIVY_INSECURE` set up on scan jobs

**Anything else you would like to add:**

I believe that adding 

```
		if config.GetDBRepositoryInsecure() {
			env = append(env, corev1.EnvVar{
				Name:  "TRIVY_INSECURE",
				Value: "true",
			})
		}
```

somewhere in https://github.com/aquasecurity/trivy-operator/blob/28e46f29422d815ad1db56f6db952ec0acf772ef/pkg/plugins/trivy/plugin.go#L957 should fix this issue

As a workaround one can use helm `trivy.serverInsecure: true`

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.16.3
- Kubernetes version (use `kubectl version`): not rel
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): not rel
