### ISSUE TITLE
Flag for changing default cache-dir parameter

### ISSUE THREAD

**Issue by ahalay** [aquasecurity/trivy-operator#1603]
This will be useful for using a custom image with existing vulnerability index databases. At the moment the `cache-dir` path is [hardcoded](https://github.com/aquasecurity/trivy-operator/blob/86aacdff2422c72da7c21603008c901f5066cf13/pkg/plugins/trivy/image.go#L536-L537) and the scan job has a next volumes configuration which overwrites anything in `tmp`, so you cannot store DBs there:

```yaml
spec:
  volumes:
    - name: tmp
      emptyDir: {}
    - name: scanresult
      emptyDir: {}
```
