### ISSUE TITLE
Tolerations missing for Node-Collector Jobs

### ISSUE THREAD

**Issue by dschunack** [aquasecurity/trivy-operator#1659]
**What steps did you take and what happened:**

Hi,

looks like the scanJobTolerations is not used for the Node Collector Job. scanJobTolerations is set, but only used for Vulnerability Jobs and not for Node-Collector jobs.

We set the following and it's used for the Scan Jobs but not for the Node-Collector Jobs.
```yaml
  scanJobTolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  - operator: "Exists"
```

**What did you expect to happen:**

scanJobTolerations is also used for the Node Collector Jobs.

**Environment:**

- Trivy-Operator version (use `trivy-operator version`):  0.16.4
- Kubernetes version (use `kubectl version`):  v1.27.3-eks-a5565ad
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): AMZN2
