### ISSUE TITLE
AWS ECR unexpected status code 401 Unauthorized: Not Authorized

### ISSUE THREAD

**Issue by xyfleet** [aquasecurity/trivy-operator#1708]
**What steps did you take and what happened:**

Install trivy-operator by using helm chart. Configured aws IAM role with OIDC and associated it with the policy
`arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly`

(Followed the link: https://aquasecurity.github.io/trivy-operator/v0.5.0/vulnerability-scanning/managed-registries/#amazon-elastic-container-registry-ecr)
In the helm chart, enabled service account with annotation
```

serviceAccount:
  name: trivy-operator-sa
  annotations:
    eks.amazonaws.com/audience: sts.amazonaws.com
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789:role/trivy-system-operator-sa"
```

**What did you expect to happen:**
trivy system can scan image in ECR without problem.

**Anything else you would like to add:**

**Environment:**

- Trivy-Operator version 0.17.1
- Kubernetes version (use `kubectl version`): 1.27
