### ISSUE TITLE
Trivy operator behaviour when containers are injected into deployment pod by admissions controllers

### ISSUE THREAD

**Issue by andriktr** [aquasecurity/trivy-operator#1745]
Hello,
When we run a deployment in k8s trivy-operator looks into the replica set get the images for vulnerability scanning. The problem I see here is in case it's not covers cases when mutating admission controller injects container into the pod. Good example here is a case when we inject service mesh sidecars into our application. Usually then 1 or more containers being added into the pod however replica set normally remains unchanged and contains only the application image in the definition. As result in reality we have pods  with application containers + containers injected by admission controllers and as trivy look on replicaset only the application container will be scanned. 

Here is the image grep for the replica set:

<img width="706" alt="image" src="https://github.com/aquasecurity/trivy-operator/assets/25537180/a57c44b9-3fab-47eb-909a-9e8ea97b9f83">

As you can see we have only 1 image

And here we grep image from the pods controlled by this replica set 
<img width="763" alt="image" src="https://github.com/aquasecurity/trivy-operator/assets/25537180/2d9282ee-574b-4d8b-925a-65319d38a7f9">

As u can see we have  2 additional  images there `consul-dataplane:1.2.3` is consul service mesh sidecar container image and `consul-k8s-control-plane:1.2.3` is an init container image both these images are injected into pod by admission controller and they are not scanned by trivy-operator. 

Any suggestions, opinions ?

Thank you.

**Comment by chen-keinan** [comment]
@andriktr that is a very good point , there is a way to know if the service mesh has added a sidecars , I mean line labels or annotations ?

**Comment by andriktr** [comment]
I believe this depends on mesh solution, but typically u enable service mesh by adding an annotation to deployment/pod. 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-client
  namespace: consul-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-client
  template:
    metadata:
      name: static-client
      labels:
        app: static-client
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
....
```

However it also possible to enable injection by default for all workloads in cluster and I'm not sure if annotations will be added in this case as well, but most probably yes.
