### ISSUE TITLE
Duplicate value sbomvol

### ISSUE THREAD

**Issue by chary1112004** [aquasecurity/trivy-operator#1747]
**What steps did you take and what happened:**

We have installed latest version trivy operator 0.20.0 however we saw there is error with sbom while scanning ebs-csi-controller. And issue also happens for some other resources.

$ helm install my-trivy-operator trivy-operator/trivy-operator --version 0.20.0

values.yaml
```
  operator:
    # scanJobsConcurrentLimit the maximum number of scan jobs create by the operator
    scanJobsConcurrentLimit: 1

  serviceMonitor:
    enabled: true
    labels:
      release: prometheus

  resources:
    # -- We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    requests:
      cpu: 15m
      memory: 250Mi

  trivy:
    # -- resources resource requests and limits for scan job containers
    resources:
      requests:
        cpu: 100m
        memory: 100M
        # ephemeralStorage: "2Gi"
      limits:
        cpu: 500m
        memory: 1000M
        # ephemeralStorage: "2Gi"
```

```
{"level":"error","ts":"2024-01-08T03:21:23Z","msg":"Reconciler error","controller":"replicaset","controllerGroup":"apps","controllerKind":"ReplicaSet","ReplicaSet":{"name":"ebs-csi-controller-8668579db8","namespace":"kube-system"},"namespace":"kube-system","name":"ebs-csi-controller-8668579db8","reconcileID":"1e6ee77f-2c3d-4097-a993-dc6f1d71e323","error":"creating scan job failed: trivy-system/scan-vulnerabilityreport-bf55dc645: Job.batch \"scan-vulnerabilityreport-bf55dc645\" is invalid: [spec.template.spec.volumes[3].name: Duplicate value: \"sbomvol\", spec.template.spec.containers[5].volumeMounts[3].mountPath: Invalid value: \"/sbom\": must be unique]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
```

Any suggestion to resolve this issue would be very much appreciated!

Thanks

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.18.0
- Kubernetes version (use `kubectl version`): 1.25
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
