### ISSUE TITLE
Trivy-operator has stopped exposing `image_digest` label in metric `trivy_image_vulnerabilities`

### ISSUE THREAD

**Issue by d-mankowski-synerise** [aquasecurity/trivy-operator#1763]
**What steps did you take and what happened:**

After upgrading trivy-operator to the latest version (`0.18.1`, chart version: `0.20.1`) from `0.16.4`, label `image_digest` is missing in metric `trivy_image_vulnerabilities` (deployment of a new version was around midnight):

<img width="1511" alt="image" src="https://github.com/aquasecurity/trivy-operator/assets/101267779/4fa007de-dd6d-491f-9872-6cecf84edb7e">

This is problematic, because we can have, for example, two images `alpine:latest`, and one can be a year old, while the other - a recent one. And this makes dashboards regarding CVEs in Grafana difficult to maintain, since there is no convenient way to group images by some label.

I haven't seen this change mentioned anywhere in the changelog, hence this should be considered as a bug.

The problem, I think, is caused by the lack of `digest` field in `vulnerabilityreports`. For example, report created by operator 0.16.4:

```yaml
report:
  artifact:
    digest: sha256:be96fcdb31b3d212dd326fdea33c3577d9a1f4243f428ecf181bcf2a065e32b6
    repository: bitnami/mongodb
    tag: 5.0.9-debian-10-r0
  registry:
    server: index.docker.io
```

while one created by `0.18.1`:

```yaml
report:
  artifact:
    repository: bitnami/redis
    tag: 6.2.7-debian-10-r23
  registry:
    server: index.docker.io
```

**What did you expect to happen:**

`trivy_image_vulnerabilities` exposes `image_digest` label

**Anything else you would like to add:**

I haven't made any changes to the config when upgrading:

```yaml
---
targetWorkloads: "replicaset,replicationcontroller,statefulset,daemonset,cronjob,pod"

trivy:
  image:
    tag: 0.48.2
  mode: ClientServer
  serverURL: http://trivy-service.trivy-operator:4954
  serverInsecure: true
  ignoreUnfixed: true
  additionalVulnerabilityReportFields: "Target,Class"
  timeout: "5m0s"
  slow: false
  # Resources of scan-vulnerabilityreport pods
  resources:
    requests:
      cpu: 350m
      memory: 1024Mi
    limits:
      cpu: 600m
      memory: 2048Mi

trivyOperator:
  scanJobCompressLogs: true
  reportResourceLabels: app,synerise.com/owner.team

# trivy-operator pod resources.
resources:
  requests:
    cpu: 500m
    memory: 3072Mi
  limits:
    cpu: 800m
    memory: 5120Mi

operator:
  sbomGenerationEnabled: true
  scanJobTTL: 10m
  scanJobsConcurrentLimit: 5
  rbacAssessmentScannerEnabled: false
  infraAssessmentScannerEnabled: false
  builtInTrivyServer: true
  metricsFindingsEnabled: true
  metricsVulnIdEnabled: false
  metricsExposedSecretInfo: true
  metricsConfigAuditInfo: true
  metricsRbacAssessmentInfo: false
  metricsInfraAssessmentInfo: false
  exposedSecretScannerEnabled: false
  webhookBroadcastURL: "http://postee.trivy-operator:8082"
  logDevMode: false

serviceMonitor:
  enabled: true
  namespace: trivy-operator
  interval: 1m
```

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.18.1
- Kubernetes version (use `kubectl version`): 1.27.7
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Ubuntu 22
- Trivy version: 0.48.2
