### ISSUE TITLE
Loading error: open trivy.yaml: permission denied

### ISSUE THREAD

**Issue by chary1112004** [aquasecurity/trivy-operator#1777]
**What steps did you take and what happened:**

Hi,

We are checking log and see the error 'loading error: open trivy.yaml: permission denied'

```
{"level":"error","ts":"2024-01-16T12:10:21Z","logger":"reconciler.scan job","msg":"Scan job container","job":"trivy-system/scan-vulnerabilityreport-6968ff98cd","container":"<container name>","status.reason":"Error","status.message":"2024-01-16T12:10:18.307Z\t\u001b[31mFATAL\u001b[0m\tconfig file \"trivy.yaml\" loading error: open trivy.yaml: permission denied\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:346\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).SetupWithManager.(*ScanJobController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:81\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/reconcile/reconcile.go:111\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
```

$ kubectl get cm trivy-operator-trivy-config -n trivy-system -o yaml
```
apiVersion: v1
data:
  trivy.additionalVulnerabilityReportFields: ""
  trivy.command: filesystem
  trivy.dbRepository: ghcr.io/aquasecurity/trivy-db
  trivy.dbRepositoryInsecure: "false"
  trivy.filesystemScanCacheDir: /var/trivyoperator/trivy-db
  trivy.imagePullPolicy: IfNotPresent
  trivy.imageScanCacheDir: /tmp/trivy/.cache
  trivy.includeDevDeps: "false"
  trivy.javaDbRepository: ghcr.io/aquasecurity/trivy-java-db
  trivy.mode: Standalone
  trivy.repository: ghcr.io/aquasecurity/trivy
  trivy.resources.limits.cpu: 500m
  trivy.resources.limits.memory: 2000M
  trivy.resources.requests.cpu: 100m
  trivy.resources.requests.memory: 1000M
  trivy.sbomSources: ""
  trivy.severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
  trivy.skipJavaDBUpdate: "false"
  trivy.slow: "false"
  trivy.supportedConfigAuditKinds: Workload,Service,Role,ClusterRole,NetworkPolicy,Ingress,LimitRange,ResourceQuota
  trivy.tag: 0.48.1
  trivy.timeout: 10m0s
  trivy.useBuiltinRegoPolicies: "true"
kind: ConfigMap
```

Any suggestion to resolve this issue would be very much appreciated!

Thanks!

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.20.1
- Kubernetes version (use `kubectl version`): 1.25
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by chen-keinan** [comment]
@chary1112004 have you set [privileges](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L247)

**Comment by chary1112004** [comment]
@chen-keinan yes, I already enable privileges

Here is value file

```
operator:
  # scanJobsConcurrentLimit the maximum number of scan jobs create by the operator
  scanJobsConcurrentLimit: 1

  # -- scanJobTimeout the length of time to wait before giving up on a scan job
  scanJobTimeout: 20m
  
  # -- infraAssessmentScannerEnabled the flag to enable infra assessment scanner
  infraAssessmentScannerEnabled: false

  # -- controllerCacheSyncTimeout the duration to wait for controller resources cache sync (default: 5m).
  controllerCacheSyncTimeout: "10m"

serviceMonitor:
  enabled: true
  labels:
    release: prometheus

resources:
  # -- We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 15m
    memory: 250Mi

trivyOperator:
  # -- scanJobPodTemplateContainerSecurityContext SecurityContext the user wants the scanner and node collector containers (and their
  # initContainers) to be amended with.
  scanJobPodTemplateContainerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true
    # -- For filesystem scanning, Trivy needs to run as the root user
    runAsUser: 0

trivy:
  # -- slow this flag is to use less CPU/memory for scanning though it takes more time than normal scanning. It fits small-footprint
  slow: false

  # -- timeout is the duration to wait for scan completion.
  timeout: "20m0s"

  # -- command. One of `image`, `filesystem` or `rootfs` scanning, depending on the target type required for the scan.
  # For 'filesystem' and `rootfs` scanning, ensure that the `trivyOperator.scanJobPodTemplateContainerSecurityContext` is configured
  # to run as the root user (runAsUser = 0).
  command: filesystem
  
  # -- resources resource requests and limits for scan job containers
  resources:
    requests:
      cpu: 100m
      memory: 1000M
      # ephemeralStorage: "2Gi"
    limits:
      cpu: 500m
      memory: 2000M
      # ephemeralStorage: "2Gi"
```

**Comment by chen-keinan** [comment]
@chary1112004 are vuln, misconfig, and other reports get generated ?

**Comment by chary1112004** [comment]
> @chary1112004 are vuln, misconfig, and other reports get generated ?

Reports are generated however I do not see report for this container is generated in dashboard.

**Comment by chen-keinan** [comment]
> > @chary1112004 are vuln, misconfig, and other reports get generated ?
> 
> Reports are generated however I do not see report for this container is generated in dashboard.

@chary1112004 this is strange, could you restart the operator and see if it get scanned again ?

**Comment by chary1112004** [comment]
> > > @chary1112004 are vuln, misconfig, and other reports get generated ?
> > 
> > 
> > Reports are generated however I do not see report for this container is generated in dashboard.
> 
> @chary1112004 this is strange, could you restart the operator and see if it get scanned again ?

@chen-keinan I have restarted the operator and it still appears the error

**Comment by chen-keinan** [comment]
> > > > @chary1112004 are vuln, misconfig, and other reports get generated ?
> > > 
> > > 
> > > Reports are generated however I do not see report for this container is generated in dashboard.
> > 
> > 
> > @chary1112004 this is strange, could you restart the operator and see if it get scanned again ?
> 
> @chen-keinan I have restarted the operator and it still appears the error

the `scan-job`  `pod` and `job` for specific container need to be deleted and then restarted  operator. the error is old one

**Comment by chary1112004** [comment]
> > @chen-keinan I have restarted the operator and it still appears the error
> 
> the `scan-job` `pod` and `job` for specific container need to be deleted and then restarted operator. the error is old one
> 
> btw: is this happening only for this specific pod ?

Yes, I did delete scan-job pod and trivy-operator pod as well.
I saw there are 2 pods (kube-rbac-proxy and kafka-client) that appear in the log.

**Comment by chary1112004** [comment]
Error is keeping appear and here is the log as we see:
```
{"level":"error","ts":"2024-02-15T20:05:55Z","logger":"reconciler.scan job","msg":"Scan job container","job":"trivy-system/scan-vulnerabilityreport-767b9b9dcb","container":"kube-rbac-proxy","status.reason":"Error","status.message":"2024-02-15T20:05:42.739Z\t\u001b[31mFATAL\u001b[0m\tconfig file \"trivy.yaml\" loading error: open trivy.yaml: permission denied\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:346\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).SetupWithManager.(*ScanJobController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:81\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/reconcile/reconcile.go:111\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":"2024-02-16T02:42:38Z","logger":"reconciler.scan job","msg":"Scan job container","job":"trivy-system/scan-vulnerabilityreport-5bf559c778","container":"kafka-client","status.reason":"Error","status.message":"2024-02-16T02:42:34.418Z\t\u001b[31mFATAL\u001b[0m\tconfig file \"trivy.yaml\" loading error: open trivy.yaml: permission denied\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:346\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).SetupWithManager.(*ScanJobController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:81\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/reconcile/reconcile.go:111\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":"2024-02-16T02:43:08Z","logger":"reconciler.scan job","msg":"Scan job container","job":"trivy-system/scan-vulnerabilityreport-f9fbb4bcd","container":"kafka-client","status.reason":"Error","status.message":"2024-02-16T02:43:04.601Z\t\u001b[31mFATAL\u001b[0m\tconfig file \"trivy.yaml\" loading error: open trivy.yaml: permission denied\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:346\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).SetupWithManager.(*ScanJobController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:81\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/reconcile/reconcile.go:111\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
```

**Comment by chary1112004** [comment]
@chen-keinan 

For what we have done to make it works that changing scan job security context into **allowPrivilegeEscalation: true # default is false**. However I think this is just work around because scan job is given more power.

```
trivyOperator:
  scanJobPodTemplateContainerSecurityContext:
    allowPrivilegeEscalation: true # default is false
    capabilities:
     drop:
       - ALL
    privileged: false
    readOnlyRootFilesystem: true
```
