### ISSUE TITLE
x509 certificate signed by unknown authority with builtInTrivyServer

### ISSUE THREAD

**Issue by seekermarcel** [aquasecurity/trivy-operator#1799]
**What steps did you take and what happened:**

When trying to pull from a private registry via the builtInTrivyServer option the self-signed TLS certificate fails.
We already tested: 
- insecure registry and server option
- mounted certificates (which won't get mounted in the server only in the operator)

Steps:

1. configure trivy-operator helm chart to use insecure db repository & builtInServer mode
2. at startup the trivy-server tries to download the db and gets rejected

```
INFO    Downloading DB...
FATAL    failed to download vulnerability DB: database download error: OCI repository error: 1 error occurred:
	* Get "https://harbor...../v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

**What did you expect to happen:**

The server pulls the trivy database successfully.

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.17.1
- Kubernetes version (use `kubectl version`): 1.26.9

**Comment by chen-keinan** [comment]
@seekermarcel can you please share your configmaps

**Comment by seekermarcel** [comment]
**trivy-operator-trivy-config**
```
data:
  TRIVY_CACHE_DIR: /home/scanner/.cache/trivy
  TRIVY_DB_REPOSITORY: harbor....../ghcr.io/aquasecurity/trivy-db
  TRIVY_DEBUG: "false"
  TRIVY_LISTEN: 0.0.0.0:4954
  TRIVY_SKIP_DB_UPDATE: "false"
  trivy.additionalVulnerabilityReportFields: ""
  trivy.command: image
  trivy.dbRepository: harbor....../ghcr.io/aquasecurity/trivy-db
  trivy.dbRepositoryInsecure: "true"
  trivy.filesystemScanCacheDir: /var/trivyoperator/trivy-db
  trivy.imagePullPolicy: IfNotPresent
  trivy.imageScanCacheDir: /tmp/trivy/.cache
  trivy.insecureRegistry.test-harbor: harbor......
  trivy.javaDbRepository: harbor....../ghcr.io/aquasecurity/trivy-java-db
  trivy.mode: ClientServer
  trivy.repository: harbor....../ghcr.io/aquasecurity/trivy
  trivy.resources.limits.cpu: 500m
  trivy.resources.limits.memory: 500M
  trivy.resources.requests.cpu: 100m
  trivy.resources.requests.memory: 100M
  trivy.serverInsecure: "true"
  trivy.serverURL: http://trivy-service.trivy-operator:4954
  trivy.severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
  trivy.skipJavaDBUpdate: "false"
  trivy.slow: "true"
  trivy.supportedConfigAuditKinds: Workload,Service,Role,ClusterRole,NetworkPolicy,Ingress,LimitRange,ResourceQuota
  trivy.tag: 0.47.0
  trivy.timeout: 5m0s
  trivy.useBuiltinRegoPolicies: "true"
```

we also tried not using the `trivy.insecureRegistry.test-harbor`parameter comming from the `trivy.insecureRegistries` helm chart option as well as mounting valid certificates but nothing reaches the built in trivy server.

**Comment by chen-keinan** [comment]
@seekermarcel  not sure it supported on trivy server,  are you able to see the following envvar on trivy server statfulset ? 
```
Name:  "TRIVY_INSECURE",
Value: "true"
```

**Comment by seekermarcel** [comment]
in the statefulset i can only see:
```
envFrom:
  - configMapRef:
    name: trivy-operator-trivy-config
  - secretRef:
    name: trivy-operator-trivy-config
```

and in the corresponding cm or secret are no envvars with the name "TRIVY_INSECURE" only "serverInsecure" and "dbRepositoryInsecure" as seen above.
