### ISSUE TITLE
job/node-collector - Job has reached the specified backoff limit

### ISSUE THREAD

**Issue by ebCrypto** [aquasecurity/trivy-operator#1803]
**What steps did you take and what happened:**

Fresh install of trivy-operator using helm. My nodeCollector config:
```
nodeCollector:
      # -- useNodeSelector determine if to use nodeSelector (by auto detecting node name) with node-collector scan job
      useNodeSelector: false
      # -- registry of the node-collector image
      registry: ghcr.io
      # -- repository of the node-collector image
      repository: aquasecurity/node-collector
      # -- tag version of the node-collector image
      tag: 0.1.1
      # -- imagePullSecret is the secret name to be used when pulling node-collector image from private registries example : reg-secret
      # It is the user responsibility to create the secret for the private registry in `trivy-operator` namespace
      imagePullSecret: ~
      # -- excludeNodes comma-separated node labels that the node-collector job should exclude from scanning (example kubernetes.io/arch=arm64,team=dev)
      excludeNodes:
      # -- node-collector pod volume mounts definition for collecting config files information
      volumeMounts:
        - name: var-lib-etcd
          mountPath: /var/lib/etcd
          readOnly: true
        - name: var-lib-kubelet
          mountPath: /var/lib/kubelet
          readOnly: true
        - name: var-lib-kube-scheduler
          mountPath: /var/lib/kube-scheduler
          readOnly: true
        - name: var-lib-kube-controller-manager
          mountPath: /var/lib/kube-controller-manager
          readOnly: true
        #  - name: etc-systemd
        #    mountPath: /etc/systemd
        #    readOnly: true
        # - name: lib-systemd
        #   mountPath: /lib/systemd/
        #   readOnly: true
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
          readOnly: true
        - name: etc-cni-netd
          mountPath: /etc/cni/net.d/
          readOnly: true
```

**What did you expect to happen:**

node-collector not to error out. yet the job/node collector runs every 30sec, and errors out. 

**Anything else you would like to add:**

```
{
  "level": "error",
  "ts": "2024-01-29T03:49:24Z",
  "logger": "node-collectorontroller",
  "msg": "Scan job container",
  "job": "trivy-system/node-collector-7d5d4d8866",
  "container": "node-collector",
  "status.reason": "Error",
  "status.message": "",
  "stacktrace": "github.com/aquasecurity/trivy-operator/pkg/configauditreport/controller.(*NodeCollectorJobController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/configauditreport/controller/nodecollector.go:194\ngithub.com/aquasecurity/trivy-operator/pkg/configauditreport/controller.(*NodeCollectorJobController).SetupWithManager.(*NodeCollectorJobController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/configauditreport/controller/nodecollector.go:76\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/reconcile/reconcile.go:111\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"
}
```

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.20.2
- Kubernetes version (use `kubectl version`): 1.29.0
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): talos 1.6.3
