### ISSUE TITLE
Support affinities for scan jobs

### ISSUE THREAD

**Issue by maxbrunet** [aquasecurity/trivy-operator#1835]
Hello! 👋 

I would like to allow node-level jobs to run on any node with taints, except some. Currently, a config with the exhaustive list of acceptable taints is required, and every time a new taint is added to the cluster, it also needs to be added to the scan job tolerations:

```yaml
nodeCollector.excludeNodes: type=virtual-kubelet
scanJob.tolerations: '[ many many many taints ]'
```

Ideally, I would like to tolerate all taints, but exclude some nodes with a node anti-affinity instead: 

```yaml
nodeCollector.excludeNodes: type=virtual-kubelet
scanJob.affinity: '{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"virtual-kubelet.io/provider","operator":"DoesNotExist"}]}]}}}'
scanJob.tolerations: '[{"operator":"Exists"}]'
```

A `scanJob.affinity` option would be nice for this purpose.

Please let me know if there is already a way to achieve that or if I am missing something.
