### ISSUE TITLE
For any version newer than chart-version 0.19.0 (appVersion 0.17.0) we get "OOMKilled" errors.

### ISSUE THREAD

**Issue by bhmdtv** [aquasecurity/trivy-operator#1848]
**What steps did you take and what happened:**

For any version newer than helm-chart 0.19.0 (appVersion 0.17.0) we get "OOMKilled" errors.
We already tried adding more CPU and RAM. Even 10 times as much doesn't help.

Here some example errors:

```
{"level":"error","ts":"2024-02-07T14:35:30Z","logger":"reconciler.scan job","msg":"Scan job container","job":"trivy-operator/scan-vulnerabilityreport-66f6f9cf45","container":"mongodb-backup-daemon","status.reason":"OOMKilled","status.message":"Killed\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:346\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).SetupWithManager.(*ScanJobController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:81\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/reconcile/reconcile.go:111\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":"2024-02-07T14:36:35Z","logger":"reconciler.scan job","msg":"Scan job container","job":"trivy-operator/scan-vulnerabilityreport-55f67d495b","container":"mongod","status.reason":"OOMKilled","status.message":"Killed\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:346\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).SetupWithManager.(*ScanJobController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:81\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/reconcile/reconcile.go:111\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":"2024-02-09T06:41:10Z","logger":"reconciler.scan job","msg":"Scan job container","job":"trivy-operator/scan-vulnerabilityreport-6cd56549f","container":"webhook","status.reason":"OOMKilled","status.message":"Killed\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:346\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).SetupWithManager.(*ScanJobController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:81\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/reconcile/reconcile.go:113\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":"2024-02-09T06:41:10Z","logger":"reconciler.scan job","msg":"Scan job container","job":"trivy-operator/scan-vulnerabilityreport-5d79967575","container":"cert-controller","status.reason":"OOMKilled","status.message":"Killed\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:346\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).SetupWithManager.(*ScanJobController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:81\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/reconcile/reconcile.go:113\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:227"}
```

**What did you expect to happen:**

No "OOMKilled" errors.

**Anything else you would like to add:**

We do not get any of these by using helm-chart 0.19.0 (appVersion 0.17.0). 
 
How we deploy the trivy operator:

```
apiVersion: v1
kind: Namespace
metadata:
  name: trivy-operator

---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: trivy-operator-repo
  namespace: trivy-operator
spec:
  interval: 1m0s
  url: https://aquasecurity.github.io/helm-charts/

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-operator
spec:
  releaseName: trivy-operator
  chart:
    spec:
      chart: "trivy-operator"
      version: "0.19.0"
      sourceRef:
        kind: HelmRepository
        name: trivy-operator-repo
  interval: 15m0s
  install:
    remediation:
      retries: 15
  values:
    slow: true
    resources:
      limits:
        cpu: "500m" 
        memory: "2048Mi" 
      requests:
        cpu: "200m"
        memory: "1024Mi"
    excludeNamespaces: "kube-system,pks-system,kube-node-lease,kube-public,nsx-system,pks-system-host-monitoring,vmware-system-csi,trivy-operator"
    operator:
      infraAssessmentScannerEnabled: false
    trivy:
      offlineScan: true
```

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): see above
- Kubernetes version (use `kubectl version`): v1.26
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): N/A

**Comment by chen-keinan** [comment]
@bhmdtv can you please share your configmaps ?

**Comment by bhmdtv** [comment]
I guess I made it. I added the following definition to our deployment:

```
(...)
spec:
  values:
    trivy:
      resources:
        limits:
          cpu: "0.5" 
          memory: "1024M" 
        requests:
          cpu: "0.25"
          memory: "512M"  
```

No more No "OOMKilled" errors for the last 24h. 

The only question that remains is why more resources are now needed.

**Comment by chen-keinan** [comment]
@bhmdtv do you mind doing a simple test return back to prev. mem and cpu and disable [sbom flag](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L71) and let me know if it make any different

**Comment by bhmdtv** [comment]
I've commented out the definitions above and added the following yesterday at ~7pm:

```
(...)
spec:
  values:
    operator:
      sbomGenerationEnabled: false
```
Over night I got several "OOMKilled" errors.
And yes, I can see the modification in the description of the pod (this was true before the change):
```
(...)
    - name: OPERATOR_SBOM_GENERATION_ENABLED
      value: "false"
(...)
```

**Comment by chen-keinan** [comment]
@bhmdtv I see , thanks for trying , could be increasing the memory is the solution in your case

**Comment by bhmdtv** [comment]
No more "OOMKilled" errors so far on the adjusted operator deployments.

**Comment by nmarchini** [comment]
I have the same issue, i adjusted the limits to 1Gi for Memory and still seeing OOM errros

**Comment by bhmdtv** [comment]
Please double check that you have defined the memory in the correct Line?

https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L419
https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L515
https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L587

For me the first one did it. Have you tried assigning 10240M as a test?

**Comment by jon-rei** [comment]
I'm hitting the same issue with the node-collector job. I already raised resources in `trivy.resources` but the it seems like that the node-collector pods are still starting with different resources:

```
...
spec:
    command:
    - node-collector
    image: ghcr.io/aquasecurity/node-collector:0.1.1
    imagePullPolicy: IfNotPresent
    name: node-collector
    resources:
      limits:
        cpu: 100m
        memory: 100M
      requests:
        cpu: 50m
        ephemeral-storage: 50Mi
        memory: 50M
```

Unfortunately I didn't found any hint where those resources are actually configured.

**Comment by chen-keinan** [comment]
@jon-rei can you share your values.yaml with resources part , I would like to test it (I can't get it to reproduce)

**Comment by jon-rei** [comment]
Sure:
```
trivy-operator:
  excludeNamespaces: "xyz-*,xyz"

  resources:
    requests:
      cpu: 500m
      memory: 4Gi
    limits:
      cpu: 8
      memory: 10Gi

  operator:
    replicas: 1
    scanJobsConcurrentLimit: 10
    scanJobTTL: "5m"
    scannerReportTTL: "72h"
    builtInTrivyServer: true 
    sbomGenerationEnabled: false
    podLabels:
      xyz: xyz

  trivyOperator:
    scanJobPodTemplateLabels: "xyz=xyz"
    scanJobPodPriorityClassName: xyz
    scanJobPodTemplatePodSecurityContext:
      runAsGroup: 65534
      runAsUser: 65534
      runAsNonRoot: true
    scanJobTolerations:
      - key: "xyz"
        operator: "Exists"
        effect: "NoSchedule"

  serviceMonitor:
    enabled: true

  trivy:
    storageSize: 64Gi
    image:
      registry: xyz
      repository: trivy
      tag: 0.49.1
      imagePullSecret: xyz
    podLabels:
      xyz: xyz
    resources:
      requests:
        cpu: 100m
        memory: 100M
      limits:
        cpu: 8
        memory: 8Gi
    server:
      replicas: 1
      resources:
        limits:
          memory: 8Gi
```

I removed some of our securityContext settings because I think they are unrelated.
