### ISSUE TITLE
Vulnerability Type library is ignored

### ISSUE THREAD

**Issue by rgarcia89** [aquasecurity/trivy-operator#1886]
**What steps did you take and what happened:**

Deploy helm chart using the following values.yaml

```
operator:
  accessGlobalSecretsAndServiceAccount: false
  batchDeleteDelay: 10s
  batchDeleteLimit: 10
  builtInServerRegistryInsecure: false
  builtInTrivyServer: false
  clusterComplianceEnabled: false
  clusterSbomCacheEnabled: false
  configAuditScannerEnabled: false
  configAuditScannerScanOnlyCurrentRevisions: false
  controllerCacheSyncTimeout: 5m
  exposedSecretScannerEnabled: false
  infraAssessmentScannerEnabled: false
  rbacAssessmentScannerEnabled: false
  sbomGenerationEnabled: false
  scannerReportTTL: 4h
  vulnerabilityScannerEnabled: true
  vulnerabilityScannerScanOnlyCurrentRevisions: true
serviceMonitor:
  enabled: true
targetWorkloads: pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,job
trivy:
  command: filesystem
  ignoreUnfixed: true
  resources:
    limits:
      cpu: 500m
      memory: 500M
    requests:
      cpu: 100m
      memory: 100M
  severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
  slow: true
  timeout: 5m0s
  vulnType: os,library
trivyOperator:
  scanJobPodTemplateContainerSecurityContext:
    runAsUser: 0
```

Scan an image with vulnerabilities in libraries.

`trivy image --ignore-unfixed bitnami/keycloak:22.0.1-debian-11-r22`

results:
OS
![image](https://github.com/aquasecurity/trivy-operator/assets/4134730/aa3fd78e-cd07-4ba0-8c15-ea8acd7a15c4)
Library
![image](https://github.com/aquasecurity/trivy-operator/assets/4134730/379bf5c2-ebb7-4bcb-9eef-3d55025ac064)

results using trivy operator:
![image](https://github.com/aquasecurity/trivy-operator/assets/4134730/45058738-83fc-44d4-9582-198fe6bd5103)

**What did you expect to happen:**
I would expect to see vulnerabilities for os and libraries.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.18.5
- Helm Chart version: 0.20.6
- Kubernetes version (use `kubectl version`): 1.27.7
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): arch
