### ISSUE TITLE
[Bug] Trivy operator fails to evaluate resource after update

### ISSUE THREAD

**Issue by storctom** [aquasecurity/trivy-operator#1946]
After upgrading trivy-operator from version 0.18.2 to 0.19.1 we see errors like this:
controller: "cronjob"
controllerGroup: "batch"
controllerKind: "CronJob"
error: "evaluating resource: no policies found for kind: CronJob"
level: "error"
msg: "Reconciler error"
name: "send-messages"
namespace: "classified"
reconcileID: "277d55a2-347c-40c4-9f26-81bd3805f389"
stacktrace: "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"
ts: "2024-03-26T09:09:15Z"

We are running GKE clusters. Trivy is installed using manifest files. Before upgrade we have removed all CRDs related to Trivy. Errors are not limited to CronJob only other resources, for example Ingress, NetworkPolicy, are affected as well. 

Some reports are generated after upgrade but it would be useful to get rid if those messages.

- Trivy-Operator version (use `trivy-operator version`): 0.19.1
- Kubernetes version (use `kubectl version`): v1.26.14-gke.1006000
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):  linux/amd64"

**Comment by chen-keinan** [comment]
@storctom are you using air-gapped env. ?

**Comment by storctom** [comment]
@chen-keinan Network policies exists in cluster. However trivy-system namespace, where trivy-operator is running, does have all egress traffic allowed.

**Comment by chen-keinan** [comment]
> @chen-keinan Network policies exists in cluster. However trivy-system namespace, where trivy-operator is running, does have all egress traffic allowed.

you mean that you are using policies configmap to run your own policies ?

**Comment by chen-keinan** [comment]
@storctom regarding my 1st question, are you using air-gapped env ?

**Comment by chen-keinan** [comment]
> Sorry, could please expand a little bit what you mean by this question? I trough that you were asking to network policies.

Does your kubernetes cluster has access to public internet (as trivy-operator need to download policies from `ghcr.io/aquasecurity/trivy-policies:0`)

**Comment by storctom** [comment]
Cluster cannot connect to internet directly. Proxy must be used. Is there a way to tell trivy-operator to use proxy to download policies? This is possible for trivy-db and trivy-java-db.

**Comment by chen-keinan** [comment]
> Cluster cannot connect to internet directly. Proxy must be used. Is there a way to tell trivy-operator to use proxy to download policies? This is possible for trivy-db and trivy-java-db.

have you tried setting this [params](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L614-L624)

**Comment by storctom** [comment]
I see one misconfiguration on my side as we are using static files for deployment i forgot to update configmap. I see there is a new entry
  policies.bundle.oci.ref: "ghcr.io/aquasecurity/trivy-policies:0"
 I will add it to kubernetes manifest and let you know.

**Comment by chen-keinan** [comment]
> I see one misconfiguration on my side as we are using static files for deployment i forgot to update configmap. I see there is a new entry policies.bundle.oci.ref: "ghcr.io/aquasecurity/trivy-policies:0" I will add it to kubernetes manifest and let you know.

note that if it is private then you'll have to set credentials as well

**Comment by storctom** [comment]
I have been able to solve the issue however trivy is now stuck with following message
 2024/03/27 14:59:20 maxprocs: Updating GOMAXPROCS=1: using minimum allowed GOMAXPROCS                                    ││ {"level":"info","ts":"2024-03-27T14:59:22Z","logger":"main","msg":"Starting operator","buildInfo":{"Version":"0.19.1","C ││ {"level":"info","ts":"2024-03-27T14:59:22Z","logger":"operator","msg":"Resolved install mode","install mode":"AllNamespa ││ {"level":"info","ts":"2024-03-27T14:59:22Z","logger":"operator","msg":"Watching all namespaces"}   
 Unfortunately there are no errors now.

**Comment by chen-keinan** [comment]
> I have been able to solve the issue however trivy is now stuck with following message 2024/03/27 14:59:20 maxprocs: Updating GOMAXPROCS=1: using minimum allowed GOMAXPROCS ││ {"level":"info","ts":"2024-03-27T14:59:22Z","logger":"main","msg":"Starting operator","buildInfo":{"Version":"0.19.1","C ││ {"level":"info","ts":"2024-03-27T14:59:22Z","logger":"operator","msg":"Resolved install mode","install mode":"AllNamespa ││ {"level":"info","ts":"2024-03-27T14:59:22Z","logger":"operator","msg":"Watching all namespaces"} Unfortunately there are no errors now.

have you restarted the operator?
can you check is any configaudit report are generated:
```
kubectl get configauditreports --all-namespaces -o wide
```

**Comment by storctom** [comment]
I have restarted the operator i do not see any reports.

**Comment by chen-keinan** [comment]
Are you using the default settings ? or you customize the scanners, can you share `trivy-opertator` config maps

**Comment by storctom** [comment]
Sure, i will just classify some values
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-operator
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/version: "0.19.1"
    app.kubernetes.io/managed-by: kubectl
data:
  nodeCollector.volumes: '[{"hostPath":{"path":"/var/lib/etcd"},"name":"var-lib-etcd"},{"hostPath":{"path":"/var/lib/kubelet"},"name":"var-lib-kubelet"},{"hostPath":{"path":"/var/lib/kube-scheduler"},"name":"var-lib-kube-scheduler"},{"hostPath":{"path":"/var/lib/kube-controller-manager"},"name":"var-lib-kube-controller-manager"},{"hostPath":{"path":"/etc/systemd"},"name":"etc-systemd"},{"hostPath":{"path":"/lib/systemd"},"name":"lib-systemd"},{"hostPath":{"path":"/etc/kubernetes"},"name":"etc-kubernetes"},{"hostPath":{"path":"/etc/cni/net.d/"},"name":"etc-cni-netd"}]'
  nodeCollector.volumeMounts: '[{"mountPath":"/var/lib/etcd","name":"var-lib-etcd","readOnly":true},{"mountPath":"/var/lib/kubelet","name":"var-lib-kubelet","readOnly":true},{"mountPath":"/var/lib/kube-scheduler","name":"var-lib-kube-scheduler","readOnly":true},{"mountPath":"/var/lib/kube-controller-manager","name":"var-lib-kube-controller-manager","readOnly":true},{"mountPath":"/etc/systemd","name":"etc-systemd","readOnly":true},{"mountPath":"/lib/systemd/","name":"lib-systemd","readOnly":true},{"mountPath":"/etc/kubernetes","name":"etc-kubernetes","readOnly":true},{"mountPath":"/etc/cni/net.d/","name":"etc-cni-netd","readOnly":true}]'
  scanJob.podTemplateContainerSecurityContext: '{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":true}'
  scanJob.compressLogs: "true"
  vulnerabilityReports.scanner: "Trivy"
  configAuditReports.scanner: "Trivy"
  compliance.failEntriesLimit: "10"
  report.recordFailedChecksOnly: "true"
  node.collector.imageRef: "ghcr.io/aquasecurity/node-collector:0.1.2"
  policies.bundle.oci.ref: "ghcr.io/aquasecurity/trivy-policies:0"
  node.collector.nodeSelector: "false"
---
# Source: trivy-operator/templates/configmaps/policies.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-operator-policies-config
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/version: "0.19.1"
    app.kubernetes.io/managed-by: kubectl
data: {}
---
# Source: trivy-operator/templates/configmaps/trivy.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-operator-trivy-config
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/version: "0.19.1"
    app.kubernetes.io/managed-by: kubectl
data:
  trivy.repository: "repourl/aquasecurity/trivy"
  trivy.tag: "0.50.1"
  trivy.imagePullPolicy: "IfNotPresent"
  trivy.additionalVulnerabilityReportFields: ""
  trivy.severity: "HIGH,CRITICAL"
  trivy.slow: "true"
  trivy.skipJavaDBUpdate: "false"
  trivy.includeDevDeps: "false"
  trivy.imageScanCacheDir: "/tmp/trivy/.cache"
  trivy.filesystemScanCacheDir: "/var/trivyoperator/trivy-db"
  trivy.dbRepository: "ghcr.io/aquasecurity/trivy-db"
  trivy.javaDbRepository: "ghcr.io/aquasecurity/trivy-java-db"
  trivy.command: "image"
  trivy.sbomSources: ""
  trivy.dbRepositoryInsecure: "false"
  trivy.useBuiltinRegoPolicies: "true"
  trivy.supportedConfigAuditKinds: "Workload,Service,Role,ClusterRole,NetworkPolicy,Ingress,LimitRange,ResourceQuota"
  trivy.timeout: "15m0s"
  trivy.mode: "Standalone"
  trivy.resources.requests.cpu: "100m"
  trivy.resources.requests.memory: "100M"
  trivy.resources.limits.cpu: "2"
  trivy.resources.limits.memory: "2048M"
  trivy.httpProxy: "proxy"
  trivy.httpsProxy: "proxy"
  trivy.noProxy: "repo url"
  trivy.imagePullSecret: "nexus"

**Comment by storctom** [comment]
I will also add env variables 
```apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-operator-env-values
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/version: "0.19.1"
    app.kubernetes.io/managed-by: kubectl
data:
  OPERATOR_NAMESPACE: "trivy-system"
  OPERATOR_TARGET_NAMESPACES: ""
  OPERATOR_EXCLUDE_NAMESPACES: "kube-system"
  OPERATOR_TARGET_WORKLOADS: "pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,job"
  OPERATOR_SERVICE_ACCOUNT: "trivy-operator"
  OPERATOR_LOG_DEV_MODE: "false"
  OPERATOR_SCAN_JOB_TTL: ""
  OPERATOR_SCAN_JOB_TIMEOUT: "10m"
  OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT: "4"
  OPERATOR_CONCURRENT_NODE_COLLECTOR_LIMIT: "0"
  OPERATOR_SCAN_JOB_RETRY_AFTER: "30s"
  OPERATOR_BATCH_DELETE_LIMIT: "10"
  OPERATOR_BATCH_DELETE_DELAY: "10s"
  OPERATOR_METRICS_BIND_ADDRESS: ":8080"
  OPERATOR_METRICS_FINDINGS_ENABLED: "true"
  OPERATOR_METRICS_VULN_ID_ENABLED: "false"
  OPERATOR_HEALTH_PROBE_BIND_ADDRESS: ":9090"
  OPERATOR_VULNERABILITY_SCANNER_ENABLED: "true"
  OPERATOR_SBOM_GENERATION_ENABLED: "false"
  OPERATOR_CLUSTER_SBOM_CACHE_ENABLED: "false"
  OPERATOR_VULNERABILITY_SCANNER_SCAN_ONLY_CURRENT_REVISIONS: "true"
  OPERATOR_SCANNER_REPORT_TTL: "24h"
  OPERATOR_CACHE_REPORT_TTL: "120h"
  CONTROLLER_CACHE_SYNC_TIMEOUT: "5m"
  OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED: "true"
  OPERATOR_RBAC_ASSESSMENT_SCANNER_ENABLED: "true"
  OPERATOR_INFRA_ASSESSMENT_SCANNER_ENABLED: "false"
  OPERATOR_CONFIG_AUDIT_SCANNER_SCAN_ONLY_CURRENT_REVISIONS: "true"
  OPERATOR_EXPOSED_SECRET_SCANNER_ENABLED: "true"
  OPERATOR_METRICS_EXPOSED_SECRET_INFO_ENABLED: "false"
  OPERATOR_METRICS_CONFIG_AUDIT_INFO_ENABLED: "false"
  OPERATOR_METRICS_RBAC_ASSESSMENT_INFO_ENABLED: "false"
  OPERATOR_METRICS_INFRA_ASSESSMENT_INFO_ENABLED: "false"
  OPERATOR_METRICS_IMAGE_INFO_ENABLED: "false"
  OPERATOR_METRICS_CLUSTER_COMPLIANCE_INFO_ENABLED: "false"
  OPERATOR_WEBHOOK_BROADCAST_URL: ""
  OPERATOR_WEBHOOK_BROADCAST_TIMEOUT: "30s"
  OPERATOR_SEND_DELETED_REPORTS: "false"
  OPERATOR_PRIVATE_REGISTRY_SCAN_SECRETS_NAMES: "{}"
  OPERATOR_ACCESS_GLOBAL_SECRETS_SERVICE_ACCOUNTS: "true"
  OPERATOR_BUILT_IN_TRIVY_SERVER: "false"
  TRIVY_SERVER_HEALTH_CHECK_CACHE_EXPIRATION: "10h"
  OPERATOR_MERGE_RBAC_FINDING_WITH_CONFIG_AUDIT: "false"
  OPERATOR_CLUSTER_COMPLIANCE_ENABLED: "true"
```
Those variables are referenced in deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-operator
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/version: "0.19.1"
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: trivy-operator
      app.kubernetes.io/instance: trivy-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: trivy-operator
        app.kubernetes.io/instance: trivy-operator
    spec:
      serviceAccountName: trivy-operator
      automountServiceAccountToken: true
      imagePullSecrets:
        - name: nexus
      containers:
        - name: "trivy-operator"
          image: "repourl/aquasecurity/trivy-operator:0.19.1"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "150m"
              memory: "100M"
            limits:
              cpu: "2"
              memory: "1024M"
          envFrom:
            - configMapRef:
                name: trivy-operator-env-values
          ports:
            - name: metrics
              containerPort: 8080
            - name: probes
              containerPort: 9090
          readinessProbe:
            httpGet:
              path: /readyz/
              port: probes
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz/
              port: probes
            initialDelaySeconds: 5
            periodSeconds: 11
            successThreshold: 1
            failureThreshold: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: cache-policies
              readOnly: false
      volumes:
        - emptyDir: {}
          name: cache-policies
```
