### ISSUE TITLE
NodeCollector Pod Not starting

### ISSUE THREAD

**Issue by rukender** [aquasecurity/trivy-operator#1965]
**What steps did you take and what happened:**
When I upgrade trivy to v0.19.1 after this I start seeing nodecollector pods are not running and the status is showing Error. When try to see the logs or describe the pod it is not showing any information. 

As far as I can see there is nothing change in the nodecollector module in values.yaml file. It was working before with my old version after the upgrade it is giving this error. 

```
kubectl get pods -n trivy
NAME                                                              READY   STATUS    RESTARTS   AGE
node-collector-8659c6984c-8ddql                                   0/1     Error     0          104s
node-collector-8659c6984c-c6cdk                                   0/1     Error     0          3m8s
node-collector-8659c6984c-crrrr                                   0/1     Error     0          2m53s
node-collector-8659c6984c-ftmjs                                   0/1     Error     0          20s
node-collector-8659c6984c-jc4nr                                   0/1     Error     0          2m28s
ops-k8s-secops-trivy-operator-trivy-operator-shared-dfsdkfl   1/1     Running   0          4d

#kubectl describe node-collector-8659c6984c-jc4nr -n trivy
error: the server doesn't have a resource type "node-collector-8659c6984c-jc4nr"

``` 

```
# kubectl logs node-collector-8659c6984c-jc4nr -n trivy
Error: unknown
Usage:
  node-collector k8s [flags]

Flags:
  -h, --help   help for k8s

Global Flags:
  -n, --node string      node name.  default: minikube (default "minikube")
  -o, --output string    Output format. One of table|json (default "json")
  -s, --spec string       spec name.  default: cis (default "cis")
  -v, --version string   spec version.  default: 1.23 (default "1.23")
unknown
``` 

Valus.yaml

```
nodeCollector:
    # -- useNodeSelector determine if to use nodeSelector (by auto detecting node name) with node-collector scan job
    # useNodeSelector: true
    # -- registry of the node-collector image
    registry: registry.example.com
    # -- repository of the node-collector image
    repository: aquasecurity/node-collector
    # -- tag version of the node-collector image
    tag: 0.1.2
    securityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
      supplementalGroups: [2000]

    # -- imagePullSecret is the secret name to be used when pulling node-collector image from private registries example : reg-secret
    # It is the user responsibility to create the secret for the private registry in `trivy-operator` namespace
    # imagePullSecret: ~
    # -- excludeNodes comma-separated node labels that the node-collector job should exclude from scanning (example kubernetes.io/arch=arm64,team=dev)
    # excludeNodes:
    # -- node-collector pod volume mounts definition for collecting config files information
    volumeMounts:
      - name: var-lib-etcd
        mountPath: /var/lib/etcd
        readOnly: true
      - name: var-lib-kubelet
        mountPath: /var/lib/kubelet
        readOnly: true
      - name: var-lib-kube-scheduler
        mountPath: /var/lib/kube-scheduler
        readOnly: true
      - name: var-lib-kube-controller-manager
        mountPath: /var/lib/kube-controller-manager
        readOnly: true
      - name: etc-systemd
        mountPath: /etc/systemd
        readOnly: true
      - name: lib-systemd
        mountPath: /lib/systemd/
        readOnly: true
      - name: etc-kubernetes
        mountPath: /etc/kubernetes
        readOnly: true
      - name: etc-cni-netd
        mountPath: /etc/cni/net.d/
        readOnly: true

    # -- node-collector pod volumes definition for collecting config files information
    volumes:
      - name: var-lib-etcd
        hostPath:
          path: /var/lib/etcd
      - name: var-lib-kubelet
        hostPath:
          path: /var/lib/kubelet
      - name: var-lib-kube-scheduler
        hostPath:
          path: /var/lib/kube-scheduler
      - name: var-lib-kube-controller-manager
        hostPath:
          path: /var/lib/kube-controller-manager
      - name: etc-systemd
        hostPath:
          path: /etc/systemd
      - name: lib-systemd
        hostPath:
          path: /lib/systemd
      - name: etc-kubernetes
        hostPath:
          path: /etc/kubernetes
      - name: etc-cni-netd
        hostPath:
          path: /etc/cni/net.d/
``` 

**What did you expect to happen:**
Nodecollector pod should run properly and it should not show an error. 

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): v0.19.1
- Kubernetes version (use `kubectl version`): 1.27.9
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Rocky linux 8.5

**Comment by chen-keinan** [comment]
@rukender configuration looks on are you using helm install ? 
if so , can you please completely remove installation via helm and re-install again

**Comment by rukender** [comment]
> @rukender configuration looks on are you using helm install ? if so , can you please completely remove installation via helm and re-install again

I'm using ArgoCD to deploy these helm charts in k8s cluster.

**Comment by chen-keinan** [comment]
> > @rukender configuration looks on are you using helm install ? if so , can you please completely remove installation via helm and re-install again
> 
> I'm using ArgoCD to deploy these helm charts in k8s cluster.

nothing was changed in term of ` node-collector` could some kind of corruption.
Are you able to completely uninstall and re-install trivy-operator ?

**Comment by rukender** [comment]
> > > @rukender configuration looks on are you using helm install ? if so , can you please completely remove installation via helm and re-install again
> > 
> > 
> > I'm using ArgoCD to deploy these helm charts in k8s cluster.
> 
> nothing was changed in term of ` node-collector` could some kind of corruption. Are you able to completely uninstall and re-install trivy-operator ?

ok, let me check this once

**Comment by rukender** [comment]
It looks like the node-collector tag is creating this issue.
```
  nodeCollector:
    # -- useNodeSelector determine if to use nodeSelector (by auto detecting node name) with node-collector scan job
    # useNodeSelector: true
    # -- registry of the node-collector image
    registry: registry.example.com
    # -- repository of the node-collector image
    repository: aquasecurity/node-collector
    # -- tag version of the node-collector image
    tag: 0.1.2
``` 

I changed this tag to the old tag which was 0.0.6 then node-collector pods ran successfully. 
Is there any issue with this new tag?

I tried to reply before I changed the tag but it was giving same error.
