### ISSUE TITLE
ErrImageNeverPull with trivy.command = filesystem or rootfs

### ISSUE THREAD

**Issue by chary1112004** [aquasecurity/trivy-operator#1978]
**What steps did you take and what happened:**

Hi,

We saw there is issue when we configure `trivy.command = filesystem` or `trivy.command = rootfs` then sometimes `scan job` appear status `ErrImageNeverPull`.

Here is log of `scan job`
```
kubectl logs scan-vulnerabilityreport-755cd9546-k7wz6 -n trivy-system
Defaulted container "k8s-cluster" out of: k8s-cluster, 9797c3dc-a05b-4d8c-9e03-537c5348af40 (init), 4c278c3b-6eb8-449d-be86-2111c6f58d38 (init)
Error from server (BadRequest): container "k8s-cluster" in pod "scan-vulnerabilityreport-755cd9546-k7wz6" is waiting to start: ErrImageNeverPull
```

And this is message when we describe scan pod
```
  containerStatuses:
  - image: k8s.io/kubernetes:1.25.16-eks-508b6b3
    imageID: ""
    lastState: {}
    name: k8s-cluster
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Container image "k8s.io/kubernetes:1.25.16-eks-508b6b3" is not present
          with pull policy of Never
        reason: ErrImageNeverPull
```

Any suggestion to resolve this issue would be very much appreciated!

Thanks!

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.18.3
- Kubernetes version (use `kubectl version`): 1.25
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by chen-keinan** [comment]
@chary1112004 thanks for reporting this issue, I have never experienced it and I'll have to investigate it and update you

**Comment by chen-keinan** [comment]
@chary1112004 tried to investigate this, however no luck , I'm unable to reproduce it.

**Comment by chary1112004** [comment]
@chen-keinan you have tried to reproduce when deploy trivy to eks?

**Comment by chen-keinan** [comment]
@chary1112004 nope, but I do not think its related to cloud provider setting, its look like cluster config in a way.

**Comment by chary1112004** [comment]
@chen-keinan sorry, I just mean kubernetes

**Comment by rknightion** [comment]
I also get this on EKS when using Bottlerocket nodes (no idea if normal AL23 nodes also have it).

**Comment by rickymulder** [comment]
Also happens in a disconnected openshift environment.
What I specifically see is the hash matches the tag of the kubelet version...so it's trying to pull a matching image, I just don't understand where it's getting the idea to pull from k8s.io - that's nowhere in my config.

**Comment by titansmc** [comment]
I am also seeing this, let me know if I can provide any configuration details:

```
helm upgrade --install trivy-operator aqua/trivy-operator \
  --namespace trivy-system \
  --create-namespace \
  -f values.yaml \
  --version 0.21.4
  ```

```
nodeCollector:
  useNodeSelector: false
#  excludeNodes: node-role.kubernetes.io/control-plane=true
trivy:
  ignoreUnfixed: true
  command: filesystem
operator:
  controllerCacheSyncTimeout: 25m
trivyOperator:
  scanJobPodTemplateContainerSecurityContext:
    runAsUser: 0
```

**Comment by ondrejmo** [comment]
I have the same issue. The cluster is running `v1.29.5+k3s1` on Ubuntu 22.04 and Trivy-operator is deployed using:

```yaml
---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trivy-system

resources:
  - trivy-operator.yml
  - https://raw.githubusercontent.com/aquasecurity/trivy-operator/v0.21.1/deploy/static/trivy-operator.yaml

patches:
  - patch: |-
      - op: replace
        path: /data/OPERATOR_METRICS_EXPOSED_SECRET_INFO_ENABLED
        value: "false"
      - op: replace
        path: /data/OPERATOR_METRICS_CONFIG_AUDIT_INFO_ENABLED
        value: "false"
      - op: replace
        path: /data/OPERATOR_METRICS_RBAC_ASSESSMENT_INFO_ENABLED
        value: "false"
      - op: replace
        path: /data/OPERATOR_METRICS_INFRA_ASSESSMENT_INFO_ENABLED
        value: "false"
      - op: replace
        path: /data/OPERATOR_METRICS_IMAGE_INFO_ENABLED
        value: "false"
      - op: replace
        path: /data/OPERATOR_METRICS_CLUSTER_COMPLIANCE_INFO_ENABLED
        value: "false"
      - op: replace
        path: /data/OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT
        value: "3"
    target:
      kind: ConfigMap
      name: trivy-operator-config
  - patch: |-
      - op: replace
        path: /data/trivy.command
        value: "rootfs"
    target:
      kind: ConfigMap
      name: trivy-operator-trivy-config
  - patch: |-
      - op: replace
        path: /data/scanJob.podTemplateContainerSecurityContext
        value: "{\"allowPrivilegeEscalation\":false,\"capabilities\":{\"drop\":[\"ALL\"]},\"privileged\":false,\"readOnlyRootFilesystem\":true,\"runAsUser\":0}"
    target:
      kind: ConfigMap
      name: trivy-operator
```

**Comment by ondrejmo** [comment]
> I have the same issue. The cluster is running `v1.29.5+k3s1` on Ubuntu 22.04 and Trivy-operator is deployed using:
> 
> ```yaml
> ---
> 
> apiVersion: kustomize.config.k8s.io/v1beta1
> kind: Kustomization
> 
> namespace: trivy-system
> 
> resources:
>   - trivy-operator.yml
>   - https://raw.githubusercontent.com/aquasecurity/trivy-operator/v0.21.1/deploy/static/trivy-operator.yaml
> 
> patches:
>   - patch: |-
>       - op: replace
>         path: /data/OPERATOR_METRICS_EXPOSED_SECRET_INFO_ENABLED
>         value: "false"
>       - op: replace
>         path: /data/OPERATOR_METRICS_CONFIG_AUDIT_INFO_ENABLED
>         value: "false"
>       - op: replace
>         path: /data/OPERATOR_METRICS_RBAC_ASSESSMENT_INFO_ENABLED
>         value: "false"
>       - op: replace
>         path: /data/OPERATOR_METRICS_INFRA_ASSESSMENT_INFO_ENABLED
>         value: "false"
>       - op: replace
>         path: /data/OPERATOR_METRICS_IMAGE_INFO_ENABLED
>         value: "false"
>       - op: replace
>         path: /data/OPERATOR_METRICS_CLUSTER_COMPLIANCE_INFO_ENABLED
>         value: "false"
>       - op: replace
>         path: /data/OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT
>         value: "3"
>     target:
>       kind: ConfigMap
>       name: trivy-operator-config
>   - patch: |-
>       - op: replace
>         path: /data/trivy.command
>         value: "rootfs"
>     target:
>       kind: ConfigMap
>       name: trivy-operator-trivy-config
>   - patch: |-
>       - op: replace
>         path: /data/scanJob.podTemplateContainerSecurityContext
>         value: "{\"allowPrivilegeEscalation\":false,\"capabilities\":{\"drop\":[\"ALL\"]},\"privileged\":false,\"readOnlyRootFilesystem\":true,\"runAsUser\":0}"
>     target:
>       kind: ConfigMap
>       name: trivy-operator
> ```

I did a hard-restart of the cluster (rebooted all nodes, deleted & re-created all pods) and it seems to have fixed the issue for me.

**Comment by chary1112004** [comment]
@chen-keinan do you have any update for this. We also face this issue with latest version trivy operator.

Trivy-Operator version (use trivy-operator version): 0.24.0
Kubernetes version (use kubectl version): 1.31

**Comment by afdesk** [comment]
> [@chen-keinan](https://github.com/chen-keinan) do you have any update for this. We also face this issue with latest version trivy operator.
> 
> Trivy-Operator version (use trivy-operator version): 0.24.0 Kubernetes version (use kubectl version): 1.31

@chary1112004 thanks for the report!
Unfortunately, Chen is out of the team now.

could you share more details how to reproduce it on minikube/kind demo clusters? thanks

**Comment by chary1112004** [comment]
> > [@chen-keinan](https://github.com/chen-keinan) do you have any update for this. We also face this issue with latest version trivy operator.
> > Trivy-Operator version (use trivy-operator version): 0.24.0 Kubernetes version (use kubectl version): 1.31
> 
> [@chary1112004](https://github.com/chary1112004) thanks for the report! Unfortunately, Chen is out of the team now.
> 
> could you share more details how to reproduce it on minikube/kind demo clusters? thanks

@afdesk sorry for miss your message. Here is our value file:

```
fullnameOverride: "trivy-operator"

operator:
  # scanJobsConcurrentLimit the maximum number of scan jobs create by the operator
  scanJobsConcurrentLimit: 3

  # -- scanJobTimeout the length of time to wait before giving up on a scan job
  scanJobTimeout: 20m

  # -- infraAssessmentScannerEnabled the flag to enable infra assessment scanner
  infraAssessmentScannerEnabled: false

  # -- controllerCacheSyncTimeout the duration to wait for controller resources cache sync (default: 5m).
  controllerCacheSyncTimeout: "10m"

serviceMonitor:
  enabled: true
  labels:
    release: prometheus

resources:
  # -- We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 15m
    memory: 250Mi

trivyOperator:
  # -- scanJobPodTemplateContainerSecurityContext SecurityContext the user wants the scanner and node collector containers (and their
  # initContainers) to be amended with.
  scanJobPodTemplateContainerSecurityContext:
    allowPrivilegeEscalation: true
    capabilities:
     drop:
       - ALL
    privileged: true
    readOnlyRootFilesystem: true
    # -- For filesystem scanning, Trivy needs to run as the root user
    runAsUser: 0

trivy:
  # -- slow this flag is to use less CPU/memory for scanning though it takes more time than normal scanning. It fits small-footprint
  slow: false

  # -- offlineScan is the flag to enable the offline scan functionality in Trivy
  # This will prevent outgoing HTTP requests, e.g. to search.maven.org
  offlineScan: false

  # -- ignoreUnfixed is the flag to show only fixed vulnerabilities in
  # vulnerabilities reported by Trivy. Set to true to enable it.
  #
  ignoreUnfixed: true

  # -- timeout is the duration to wait for scan completion.
  timeout: "20m0s"

  # -- command. One of `image`, `filesystem` or `rootfs` scanning, depending on the target type required for the scan.
  # For 'filesystem' and `rootfs` scanning, ensure that the `trivyOperator.scanJobPodTemplateContainerSecurityContext` is configured
  # to run as the root user (runAsUser = 0).
  command: rootfs

  # -- resources resource requests and limits for scan job containers
  resources:
    requests:
      cpu: 100m
      memory: 500M
      # ephemeralStorage: "2Gi"
    limits:
      cpu: 500m
      memory: 2000M
      # ephemeralStorage: "2Gi"

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: assetfactory.nttdata.com/asset
              operator: In
              values:
                - assetfactory

nodeCollector:
  # -- useNodeSelector determine if to use nodeSelector (by auto detecting node name) with node-collector scan job
  useNodeSelector: false
```

$ kubectl get pods -n trivy-system
![Image](https://github.com/user-attachments/assets/7a5379ad-f0b1-479e-a0c4-3f0f2b1407e6)

Error message while describe pod
$ kubectl describe pod scan-vulnerabilityreport-b69b648f4-dbfs5 -n trivy-system
![Image](https://github.com/user-attachments/assets/77bbf3f7-c231-4dfe-ab0a-88de2e37f175)

For reproduce: we deploy olm -> gitlab runner operator (include cert manager)

**Comment by chary1112004** [comment]
> > [@chen-keinan](https://github.com/chen-keinan) do you have any update for this. We also face this issue with latest version trivy operator.
> > Trivy-Operator version (use trivy-operator version): 0.24.0 Kubernetes version (use kubectl version): 1.31
> 
> [@chary1112004](https://github.com/chary1112004) thanks for the report! Unfortunately, Chen is out of the team now.
> 
> could you share more details how to reproduce it on minikube/kind demo clusters? thanks

@afdesk sorry for miss your message. Here is our value file:

```
fullnameOverride: "trivy-operator"

operator:
  # scanJobsConcurrentLimit the maximum number of scan jobs create by the operator
  scanJobsConcurrentLimit: 3

  # -- scanJobTimeout the length of time to wait before giving up on a scan job
  scanJobTimeout: 20m

  # -- infraAssessmentScannerEnabled the flag to enable infra assessment scanner
  infraAssessmentScannerEnabled: false

  # -- controllerCacheSyncTimeout the duration to wait for controller resources cache sync (default: 5m).
  controllerCacheSyncTimeout: "10m"

serviceMonitor:
  enabled: true
  labels:
    release: prometheus

resources:
  # -- We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 15m
    memory: 250Mi

trivyOperator:
  # -- scanJobPodTemplateContainerSecurityContext SecurityContext the user wants the scanner and node collector containers (and their
  # initContainers) to be amended with.
  scanJobPodTemplateContainerSecurityContext:
    allowPrivilegeEscalation: true
    capabilities:
     drop:
       - ALL
    privileged: true
    readOnlyRootFilesystem: true
    # -- For filesystem scanning, Trivy needs to run as the root user
    runAsUser: 0

trivy:
  # -- slow this flag is to use less CPU/memory for scanning though it takes more time than normal scanning. It fits small-footprint
  slow: false

  # -- offlineScan is the flag to enable the offline scan functionality in Trivy
  # This will prevent outgoing HTTP requests, e.g. to search.maven.org
  offlineScan: false

  # -- ignoreUnfixed is the flag to show only fixed vulnerabilities in
  # vulnerabilities reported by Trivy. Set to true to enable it.
  #
  ignoreUnfixed: true

  # -- timeout is the duration to wait for scan completion.
  timeout: "20m0s"

  # -- command. One of `image`, `filesystem` or `rootfs` scanning, depending on the target type required for the scan.
  # For 'filesystem' and `rootfs` scanning, ensure that the `trivyOperator.scanJobPodTemplateContainerSecurityContext` is configured
  # to run as the root user (runAsUser = 0).
  command: rootfs

  # -- resources resource requests and limits for scan job containers
  resources:
    requests:
      cpu: 100m
      memory: 500M
      # ephemeralStorage: "2Gi"
    limits:
      cpu: 500m
      memory: 2000M
      # ephemeralStorage: "2Gi"

nodeCollector:
  # -- useNodeSelector determine if to use nodeSelector (by auto detecting node name) with node-collector scan job
  useNodeSelector: false
```

$ kubectl get pods -n trivy-system
![Image](https://github.com/user-attachments/assets/7a5379ad-f0b1-479e-a0c4-3f0f2b1407e6)

Error message while describe pod
$ kubectl describe pod scan-vulnerabilityreport-b69b648f4-dbfs5 -n trivy-system
![Image](https://github.com/user-attachments/assets/77bbf3f7-c231-4dfe-ab0a-88de2e37f175)

For reproduce: we deploy olm -> gitlab runner operator (include cert manager)
