### ISSUE TITLE
Add option to add annotations to the trivy-operator deployment with the helm chart values

### ISSUE THREAD

**Issue by martijnvdp** [aquasecurity/trivy-operator#1982]
Would be nice to have an option to add annotations for the trivy-operator deployment with the helm chart values
https://github.com/aquasecurity/trivy-operator/blob/a14724dd79433222348213723810cd6bbe48214a/deploy/helm/templates/deployment.yaml#L6

example use case:
to set a reloader annotation on the deploymen tso it restarts automaticaly after trivy-operator-trivy-config configmap changes
```
kind: Deployment
metadata:
  name: trivy-operator
  namespace: trivy-operator
  annotations:
    configmap.reloader.stakater.com/reload: "trivy-operator-trivy-config"
```

https://github.com/stakater/Reloader
