### ISSUE TITLE
Operator metrics endpoint doesnt's show trivy_image metrics

### ISSUE THREAD

**Issue by networkandcode** [aquasecurity/trivy-operator#2007]
### Discussed in https://github.com/aquasecurity/trivy-operator/discussions/1960

<div type='discussions-op-text'>

<sup>Originally posted by **networkandcode** March 29, 2024</sup>
Hi I tried installing trivy operator with helm with the values:
```
trivy:
  ignoreUnfixed: true
```

When I tried port fowarding the pod and access the metrics I could not see metrics that start with. trivy_image*... could you pl. tell where I could access this. I tried joining the slack channel, but it only allows specific email domains.

<img width="1298" alt="image" src="https://github.com/aquasecurity/trivy-operator/assets/30622440/fdfb9298-eee4-4084-bed7-0dfe198e8457"></div>

**Comment by Starttoaster** [comment]
Read the chart values. There's a few to enable to get various vulnerability reports from the exporter.

```
operator:
  # Enable all the metrics exporters
  # be aware that metrics cardinality is significantly increased with these features enabled
  # but these are what power the dashboard.
  metricsVulnIdEnabled: true
  metricsExposedSecretInfo: true
  metricsConfigAuditInfo: true
  metricsRbacAssessmentInfo: true
  metricsInfraAssessmentInfo: true
  metricsImageInfo: true
  metricsClusterComplianceInfo: true
```
