### ISSUE TITLE
When a resource is deleted, a delete report of some other resource is sent instead of the deleted resource. 

### ISSUE THREAD

**Issue by tokyowizard** [aquasecurity/trivy-operator#2110]
**What steps did you take and what happened:**

When setting `operator.webhookSendDeletedReports: true` and deleting a kubernetes resource, a delete report of some other resource, which **still exists**, is sent instead of a report of the deleted resource. 

Here's a summary of the commands:
1. Start up a kubernetes cluster using Docker Desktop. Install Docker Desktop and check "Enable Kubernetes" in the settings.
2. Install the trivy-operator using the [helm chart](https://github.com/aquasecurity/trivy-operator/tree/main/deploy/helm).
   * In the `values.yaml`, enable the webhook and sending deleted reports. And just enable getting the Vulnerability reports.
      <details><summary>values.yaml</summary>
      
      * Replace `LOCAL_IP` with your local IP address. (e.g. On MacOS: `ifconfig -l | xargs -n 1 ipconfig getifaddr`)

      ```yaml
      operator:
        namespace: "trivy-system"
        configAuditScannerEnabled: false
        rbacAssessmentScannerEnabled: false
        infraAssessmentScannerEnabled: false
        clusterComplianceEnabled: false
        exposedSecretScannerEnabled: false
        metricsVulnIdEnabled: false
        webhookBroadcastURL: http://LOCAL_IP:8080
        webhookSendDeletedReports: true
      trivy:
        mode: ClientServer
        ignoreUnfixed: true
      ```
      
      </details>
   trivy-server is running separately as [standalone](https://github.com/aquasecurity/trivy/tree/main/helm/trivy) in the cluster.

4. Start up a webhook server to receive and view the payload of the deleted reports that were sent.

   ```bash
   python3 -m mock_server.py
   ```
   <details><summary>mock_server.py. Python code for the webhook server (tested with Python 3.11 and 3.12)</summary>

   ```python
   import http.server
   import json
   import socketserver

   class WebhookHandler(http.server.BaseHTTPRequestHandler):
       def do_POST(self):
           content_length = int(self.headers['Content-Length'])
           post_data = self.rfile.read(content_length)
           payload = json.loads(post_data.decode('utf-8'))

           print("Received Webhook Payload:")
           print(json.dumps(payload, indent=4, sort_keys=True))

           self.send_response(200)
           self.send_header('Content-type', 'text/plain')
           self.end_headers()
           self.wfile.write(b'Webhook received successfully')

   PORT = 8080

   with socketserver.TCPServer(("", PORT), WebhookHandler) as httpd:
       print(f"Serving at port {PORT}")
       httpd.serve_forever()
   ```
   </details>

5. Apply a couple of jobs to the cluster.

   ```bash
   kubectl apply -f jobs.yaml
   ```
   
   <details><summary>jobs.yaml</summary>
   
   ```yaml
   ---
   apiVersion: batch/v1
   kind: Job
   metadata:
     name: pod-with-vulnerabilities1
   spec:
     template:
       spec:
         containers:
           - name: agent
             image: datadog/agent:7.50.3
             imagePullPolicy: IfNotPresent
             command:
               - /bin/sh
               - -c
             args:
               - date; echo " do nothing..."
         restartPolicy: Never
   ---
   apiVersion: batch/v1
   kind: Job
   metadata:
     name: pod-with-vulnerabilities2
   spec:
     template:
       spec:
         containers:
           - name: agent
             image: datadog/agent:7.40.0
             imagePullPolicy: IfNotPresent
             command:
               - /bin/sh
               - -c
             args:
               - date; echo " do nothing..."
         restartPolicy: Never
   ```
   
   </details>

6. Delete one of the jobs.

   ```bash
    kubectl delete job pod-with-vulnerabilities1
    ```

7. Check the logs of the webhook server to see the payload of the deleted report.

A payload of the deleted report was for some other pod instead of the `pod-with-vulnerabilities1` job.

**What did you expect to happen:**

I expected a report of the deleted job to have been sent.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): `0.21.1`
- Kubernetes version (use `kubectl version`): `v1.29.2`
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):  macOS `14.4.1`
