### ISSUE TITLE
Vulnerability scan job unable to pull from private dockerhub container registry

### ISSUE THREAD

**Issue by sidpalas** [aquasecurity/trivy-operator#2120]
**What steps did you take and what happened:**

Install latest version of helm chart:
```
        helm upgrade --install trivy-operator aqua/trivy-operator \
          --namespace trivy-system \
          --create-namespace \
          --version 0.23.1
```

Deploy a workload using a private image from dockerhub:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator-python
  template:
    metadata:
      labels:
        app: load-generator-python
    spec:
      containers:
        - name: load-generator
          image: docker.io/sidpalas/devops-directive-kubernetes-course-load-generator-python:foobarbaz
      imagePullSecrets:
        - name: dockerconfigjson
```

The Deployment successfully uses the imagePullSecret, but the corresponding scan job for private image fails.

**What did you expect to happen:**

Trivy to use imagePullSecret as described here:
- https://aquasecurity.github.io/trivy-operator/v0.21.1/docs/vulnerability-scanning/private-registries/
- https://aquasecurity.github.io/trivy-operator/v0.21.1/tutorials/private-registries/

**Anything else you would like to add:**

- The repo being used is: https://hub.docker.com/repository/docker/sidpalas/devops-directive-kubernetes-course-load-generator-python/ (but its private so I'm not sure that will help)
- I temporarily made the dockerhub repo public and the scan job was able to succeed.
- I tried setting [`vulnerabilityReports.scanJobsInSameNamespace: true`](https://github.com/aquasecurity/trivy-operator/blob/b4bab3568480c5cbb3393dec5542ee694cf4263f/docs/getting-started/installation/configuration.md?plain=1#L72) but the job still failed
- I tried setting [privateRegistryScanSecretsNames: {mynamespace: mydockersecret}](https://github.com/aquasecurity/trivy-operator/blob/b4bab3568480c5cbb3393dec5542ee694cf4263f/deploy/helm/values.yaml#L167)

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): ghcr.io/aquasecurity/trivy-operator:0.21.1
- Kubernetes version (use `kubectl version`): ` v1.28.7+k3s1`

**Comment by sidpalas** [comment]
I enabled log dev mode (`--set operator.logDevMode=true` in my helm install command) and see the following error in the operator pod logs:
```
2024-06-04T01:26:17Z    ERROR   reconciler.scan job     Scan job container      {"job": "trivy-system/scan-vulnerabilityreport-7b5bf85fb9", "container": "load-generator", "status.reason": "Error", "status.message": ""}
github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).completedContainers
        /home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:353
github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).SetupWithManager.(*ScanJobController).reconcileJobs.func1
        /home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:80
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.2/pkg/reconcile/reconcile.go:113
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.2/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.2/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.2/pkg/internal/controller/controller.go:261
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.2/pkg/internal/controller/controller.go:222
2024-06-04T01:26:17Z    DEBUG   reconciler.scan job     Job complete    {"job": "trivy-system/scan-vulnerabilityreport-7b5bf85fb9", "kind": "ReplicaSet", "name": "load-generator-python-76468d599c", "namespace": "demo-app", "podSpecHash": "846497f7b8"}
2024-06-04T01:26:17Z    DEBUG   reconciler.scan job     VulnerabilityReports already exist      {"job": "trivy-system/scan-vulnerabilityreport-7b5bf85fb9", "kind": "ReplicaSet", "name": "load-generator-python-76468d599c", "namespace": "demo-app", "podSpecHash": "846497f7b8", "owner": {"apiVersion": "apps/v1", "kind": "ReplicaSet", "namespace": "demo-app", "name": "load-generator-python-76468d599c"}}
2024-06-04T01:26:17Z    DEBUG   reconciler.scan job     Deleting complete scan job      {"job": "trivy-system/scan-vulnerabilityreport-7b5bf85fb9", "kind": "ReplicaSet", "name": "load-generator-python-76468d599c", "namespace": "demo-app", "podSpecHash": "846497f7b8", "owner": {"apiVersion": "apps/v1", "kind": "ReplicaSet", "namespace": "demo-app", "name": "load-generator-python-76468d599c"}}
```

Interesting that it is claiming a `VulnerabilityReports already exist` 🤔

**Comment by sidpalas** [comment]
Looking at the generated k8s scan job I also don't see a `TRIVY_USERNAME` or `TRIVY_PASSWORD` environment variable like I would expect based on: https://github.com/aquasecurity/trivy-operator/blob/b4bab3568480c5cbb3393dec5542ee694cf4263f/pkg/plugins/trivy/image.go#L208-L239

```
      containers:
      - args:
        - -c
        - trivy image --slow 'docker.io/sidpalas/devops-directive-kubernetes-course-load-generator-python:foobarbaz'
          --scanners vuln,secret --image-config-scanners secret   --skip-db-update  --cache-dir
          /tmp/trivy/.cache --quiet --list-all-pkgs --format json > /tmp/scan/result_load-generator.json
          &&  bzip2 -c /tmp/scan/result_load-generator.json | base64
        command:
        - /bin/sh
        env:
        - name: TRIVY_SEVERITY
          valueFrom:
            configMapKeyRef:
              key: trivy.severity
              name: trivy-operator-trivy-config
              optional: true
        - name: TRIVY_IGNORE_UNFIXED
          valueFrom:
            configMapKeyRef:
              key: trivy.ignoreUnfixed
              name: trivy-operator-trivy-config
              optional: true
        - name: TRIVY_OFFLINE_SCAN
          valueFrom:
            configMapKeyRef:
              key: trivy.offlineScan
              name: trivy-operator-trivy-config
              optional: true
        - name: TRIVY_JAVA_DB_REPOSITORY
          valueFrom:
            configMapKeyRef:
              key: trivy.javaDbRepository
              name: trivy-operator-trivy-config
              optional: true
        - name: TRIVY_TIMEOUT
          valueFrom:
            configMapKeyRef:
              key: trivy.timeout
              name: trivy-operator-trivy-config
              optional: true
        - name: TRIVY_SKIP_FILES
          valueFrom:
            configMapKeyRef:
              key: trivy.skipFiles
              name: trivy-operator-trivy-config
              optional: true
        - name: TRIVY_SKIP_DIRS
          valueFrom:
            configMapKeyRef:
              key: trivy.skipDirs
              name: trivy-operator-trivy-config
              optional: true
        - name: HTTP_PROXY
          valueFrom:
            configMapKeyRef:
              key: trivy.httpProxy
              name: trivy-operator-trivy-config
              optional: true
        - name: HTTPS_PROXY
          valueFrom:
            configMapKeyRef:
              key: trivy.httpsProxy
              name: trivy-operator-trivy-config
              optional: true
        - name: NO_PROXY
          valueFrom:
            configMapKeyRef:
              key: trivy.noProxy
              name: trivy-operator-trivy-config
              optional: true
        image: ghcr.io/aquasecurity/trivy:0.51.2
        imagePullPolicy: IfNotPresent
        name: load-generator
        resources:
          limits:
            cpu: 500m
            memory: 500M
          requests:
            cpu: 100m
            memory: 100M
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /tmp/scan
          name: scanresult
```
