### ISSUE TITLE
Metrics Report Only One Finding for Multiple Binaries with Same Vulnerability ID

### ISSUE THREAD

**Issue by kersten** [aquasecurity/trivy-operator#2139]
**What steps did you take and what happened:**

I encountered an issue while building a dashboard in Grafana. In the `collectVulnerabilityIdReports` method, the operator collects metrics. When there is a finding in two binaries within the same image that share the same Vulnerability ID, only one metric is reported. This appears to be due to the following code block:

```go
if vulnList[vuln.VulnerabilityID] {
    continue
}
```

I discovered this while analyzing the [podinfo](https://hub.docker.com/layers/stefanprodan/podinfo/6.6.0/images/sha256-5f9da9d97c0ca78c8ce28f87e4b0c27109d9baa7ecfab7050bf3ad897d30d557?context=explore) image. The VulnerabilityReport shows multiple findings, but the metrics endpoint reports only one:

Example VulnerabilityReport:

```yaml
- class: lang-pkgs
  description: >-
    The various Is methods (IsPrivate, IsLoopback, etc) did not work as
    expected for IPv4-mapped IPv6 addresses, returning false for addresses
    which would return true in their traditional IPv4 forms.
  fixedVersion: '1.21.11, 1.22.4'
  installedVersion: 1.21.7
  lastModifiedDate: '2024-06-10T18:15:26Z'
  links:
    - 'http://www.openwall.com/lists/oss-security/2024/06/04/1'
    - 'https://go.dev/cl/590316'
    - 'https://go.dev/issue/67680'
    - >-
      https://groups.google.com/g/golang-announce/c/XbxouI9gY7k/m/TuoGEhxIEwAJ
    - 'https://pkg.go.dev/vuln/GO-2024-2887'
  packageType: gobinary
  primaryLink: 'https://avd.aquasec.com/nvd/cve-2024-24790'
  publishedDate: '2024-06-05T16:15:10Z'
  resource: stdlib
  severity: UNKNOWN
  target: home/app/podinfo
  title: >-
    The various Is methods (IsPrivate, IsLoopback, etc) did not work as expected for IPv4-mapped IPv6 addresses.
  vulnerabilityID: CVE-2024-24790
- class: lang-pkgs
  description: >-
    The various Is methods (IsPrivate, IsLoopback, etc) did not work as
    expected for IPv4-mapped IPv6 addresses, returning false for addresses
    which would return true in their traditional IPv4 forms.
  fixedVersion: '1.21.11, 1.22.4'
  installedVersion: 1.21.7
  lastModifiedDate: '2024-06-10T18:15:26Z'
  links:
    - 'http://www.openwall.com/lists/oss-security/2024/06/04/1'
    - 'https://go.dev/cl/590316'
    - 'https://go.dev/issue/67680'
    - >-
      https://groups.google.com/g/golang-announce/c/XbxouI9gY7k/m/TuoGEhxIEwAJ
    - 'https://pkg.go.dev/vuln/GO-2024-2887'
  packageType: gobinary
  primaryLink: 'https://avd.aquasec.com/nvd/cve-2024-24790'
  publishedDate: '2024-06-05T16:15:10Z'
  resource: stdlib
  severity: UNKNOWN
  target: usr/local/bin/podcli
  title: >-
    The various Is methods (IsPrivate, IsLoopback, etc) did not work as expected for IPv4-mapped IPv6 addresses.
  vulnerabilityID: CVE-2024-24790
```

Example metrics output:

```
trivy_vulnerability_id{class="lang-pkgs", cluster="kind", container="trivy-operator", container_name="podinfo", endpoint="metrics", fixed_version="1.21.11, 1.22.4", image_digest="sha256:2f2114578fffba77022df832b4caffc11583a3c4dbeeef8dec07290a3bb20dec", image_registry="xxx", image_repository="images/podinfo", image_tag="6.6.0", installed_version="1.21.7", instance="10.10.131.52:8080", job="trivy-operator", last_modified_date="2024-06-10T18:15:26Z", name="replicaset-7cbff676d8", namespace="default", package_type="gobinary", pod="trivy-operator-669dcf559d-kglfs", prometheus="kube-prometheus-stack/kube-prometheus-stack-prometheus", published_date="2024-06-05T16:15:10Z", resource="stdlib", resource_kind="ReplicaSet", resource_name="podinfo-568f8d95b", service="trivy-operator", severity="Unknown", target="home/app/podinfo", vuln_id="CVE-2024-24790", vuln_title="The various Is methods (IsPrivate, IsLoopback, etc) did not work as expected for IPv4-mapped IPv6 addresses."}
```

My ConfigMap:

```yaml
apiVersion: v1
data:
  CONTROLLER_CACHE_SYNC_TIMEOUT: 5m
  OPERATOR_ACCESS_GLOBAL_SECRETS_SERVICE_ACCOUNTS: "true"
  OPERATOR_BATCH_DELETE_DELAY: 10s
  OPERATOR_BATCH_DELETE_LIMIT: "10"
  OPERATOR_BUILT_IN_TRIVY_SERVER: "true"
  OPERATOR_CACHE_REPORT_TTL: 120h
  OPERATOR_CLUSTER_COMPLIANCE_ENABLED: "true"
  OPERATOR_CLUSTER_SBOM_CACHE_ENABLED: "false"
  OPERATOR_CONCURRENT_NODE_COLLECTOR_LIMIT: "1"
  OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT: "10"
  OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED: "true"
  OPERATOR_CONFIG_AUDIT_SCANNER_SCAN_ONLY_CURRENT_REVISIONS: "true"
  OPERATOR_EXPOSED_SECRET_SCANNER_ENABLED: "true"
  OPERATOR_HEALTH_PROBE_BIND_ADDRESS: :9090
  OPERATOR_INFRA_ASSESSMENT_SCANNER_ENABLED: "true"
  OPERATOR_LOG_DEV_MODE: "false"
  OPERATOR_MERGE_RBAC_FINDING_WITH_CONFIG_AUDIT: "false"
  OPERATOR_METRICS_BIND_ADDRESS: :8080
  OPERATOR_METRICS_CLUSTER_COMPLIANCE_INFO_ENABLED: "false"
  OPERATOR_METRICS_CONFIG_AUDIT_INFO_ENABLED: "false"
  OPERATOR_METRICS_EXPOSED_SECRET_INFO_ENABLED: "false"
  OPERATOR_METRICS_FINDINGS_ENABLED: "true"
  OPERATOR_METRICS_IMAGE_INFO_ENABLED: "false"
  OPERATOR_METRICS_INFRA_ASSESSMENT_INFO_ENABLED: "false"
  OPERATOR_METRICS_RBAC_ASSESSMENT_INFO_ENABLED: "false"
  OPERATOR_METRICS_VULN_ID_ENABLED: "true"
  OPERATOR_PRIVATE_REGISTRY_SCAN_SECRETS_NAMES: '{}'
  OPERATOR_RBAC_ASSESSMENT_SCANNER_ENABLED: "true"
  OPERATOR_SBOM_GENERATION_ENABLED: "true"
  OPERATOR_SCAN_JOB_RETRY_AFTER: 30s
  OPERATOR_SCAN_JOB_TIMEOUT: 5m
  OPERATOR_SCAN_JOB_TTL: ""
  OPERATOR_SCANNER_REPORT_TTL: 24h
  OPERATOR_SEND_DELETED_REPORTS: "false"
  OPERATOR_VULNERABILITY_SCANNER_ENABLED: "true"
  OPERATOR_VULNERABILITY_SCANNER_SCAN_ONLY_CURRENT_REVISIONS: "true"
  OPERATOR_WEBHOOK_BROADCAST_CUSTOM_HEADERS: ""
  OPERATOR_WEBHOOK_BROADCAST_TIMEOUT: 30s
  OPERATOR_WEBHOOK_BROADCAST_URL: ""
  TRIVY_SERVER_HEALTH_CHECK_CACHE_EXPIRATION: 10h
kind: ConfigMap
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/version: 0.21.3
    argocd.argoproj.io/instance: trivy-operator
    helm.sh/chart: trivy-operator-0.23.3
  name: trivy-operator-config
  namespace: trivy-operator
```

trivy config
```yaml
apiVersion: v1
data:
  TRIVY_CACHE_DIR: /home/scanner/.cache/trivy
  TRIVY_DB_REPOSITORY: my.registry.com/aquasecurity/trivy-db
  TRIVY_DEBUG: "false"
  TRIVY_INSECURE: "false"
  TRIVY_LISTEN: 0.0.0.0:4954
  TRIVY_SKIP_DB_UPDATE: "false"
  trivy.additionalVulnerabilityReportFields: Description,Links,CVSS,Target,Class,PackagePath,PackageType
  trivy.command: image
  trivy.dbRepository: my.registry.com/aquasecurity/trivy-db
  trivy.dbRepositoryInsecure: "false"
  trivy.filesystemScanCacheDir: /var/trivyoperator/trivy-db
  trivy.imagePullPolicy: IfNotPresent
  trivy.imageScanCacheDir: /tmp/trivy/.cache
  trivy.includeDevDeps: "false"
  trivy.javaDbRepository: my.registry.com/aquasecurity/trivy-java-db
  trivy.mode: ClientServer
  trivy.offlineScan: "true"
  trivy.repository: my.registry.com/aquasecurity/trivy
  trivy.resources.limits.cpu: 500m
  trivy.resources.limits.memory: 500M
  trivy.resources.requests.cpu: 100m
  trivy.resources.requests.memory: 100M
  trivy.sbomSources: ""
  trivy.serverURL: http://trivy-service.trivy-operator:4954
  trivy.severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
  trivy.skipJavaDBUpdate: "false"
  trivy.slow: "true"
  trivy.supportedConfigAuditKinds: Workload,Service,Role,ClusterRole,NetworkPolicy,Ingress,LimitRange,ResourceQuota
  trivy.tag: 0.52.0
  trivy.timeout: 5m0s
  trivy.useBuiltinRegoPolicies: "true"
  trivy.useEmbeddedRegoPolicies: "false"
kind: ConfigMap
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/version: 0.21.3
    argocd.argoproj.io/instance: trivy-operator
    helm.sh/chart: trivy-operator-0.23.3
  name: trivy-operator-trivy-config
  namespace: trivy-operator
```

**What did you expect to happen:**

I expected two entries in the metrics: one for `home/app/podinfo` and another for `usr/local/bin/podcli`. This issue likely affects images with multiple binaries and applications with many dependencies (e.g., Java applications), where a CVE could be present in multiple libraries but only reported for the first finding. Including more detailed information in the grouping key, such as `target` and `pkg_path`, could help capture all occurrences accurately.

**Anything else you would like to add:**

To address this, I propose changing the grouping logic in the collector to include additional information in the key, such as `target` and `pkg_path`.

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.21.3
- Kubernetes version (use `kubectl version`): v1.29.4
