### ISSUE TITLE
Ressource creation of k8s-cis-1.23 fails with Helm chart v0.24.0

### ISSUE THREAD

**Issue by kimdre** [aquasecurity/trivy-operator#2178]
I updated the operator Helm chart from 0.23.3 to 0.24.0 and now the clustercompliancereport `k8s-cis-1.23` sync/re-creation fails.

It seems the following two lines are responsible, which were added with a change in the 0.24.0 release:

https://github.com/aquasecurity/trivy-operator/blob/df12b1ee866c233f3a896b9e3558a22a1aa4a15c/deploy/helm/templates/specs/k8s-cis-1.23.yaml#L6-L7

![image](https://github.com/aquasecurity/trivy-operator/assets/27567533/fc2db9a3-c32d-46bf-8171-9c404e41e3d8)

**Comment by chen-keinan** [comment]
you are using argocd ? is the clusterCompliance crd is updated with 2 fields ?

**Comment by kimdre** [comment]
Yes I use argocd and no, the fields are not in the CRD:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: clustercompliancereports.aquasecurity.github.io
spec:
...
```

The `k8s-cis-1.23` is also the only one that has these two fields.
