### ISSUE TITLE
trivyOperator.scanJobCustomVolumesMount and scanJobCustomVolumes helm values don't work as expected

### ISSUE THREAD

**Issue by vrevelas** [aquasecurity/trivy-operator#2263]
**What steps did you take and what happened:**

Installed trivy-operator 0.22.0 with helm chart version 0.24.1 with the following set in my values.yaml (copy-pasted and uncommented from the [chart's default values](https://github.com/aquasecurity/trivy-operator/blob/18e40db60a957cf233afeb442bddca62a03e45e9/deploy/helm/values.yaml#L259-L268))
```
trivyOperator:
  scanJobCustomVolumesMount:
   - name: var-lib-etcd
     mountPath: /var/lib/etcd
     readOnly: true
  scanJobCustomVolumes:
   - name: var-lib-etcd
     hostPath:
     path: /var/lib/etcd
```
The scan-vulnerabilityreport-* Jobs created do contain the custom volume, but it's been converted to an emptyDir. the custom volume mount is missing from both the container and the initContainer:
```
apiVersion: batch/v1
kind: Job
...
spec:
  template:
    spec:
      containers:
        - args:
...
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /tmp/scan
              name: scanresult
...
      initContainers:
        - args:
...
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      volumes:
        - emptyDir: {}
          name: tmp
        - emptyDir: {}
          name: scanresult
        - emptyDir: {}
          name: var-lib-etcd
```
I don't see any relevant errors or warning in the trivy-operator logs (grepped for "custom", "volume", and "mount", case-insensitive).

**What did you expect to happen:**
I expected the Job's var-lib-etcd volume to be a hostPath, and the container and initContainer volumeMounts to mount the var-lib-etcd volume.

**Anything else you would like to add:**
N/A

**Environment:**
- Trivy-Operator version (use `trivy-operator version`): 0.22.0
- Kubernetes version (use `kubectl version`): 1.28.7
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Ubuntu 20.04
