### ISSUE TITLE
CIS Benchmark k8s-cis-1.23 is empty

### ISSUE THREAD

**Issue by Halogenmake** [aquasecurity/trivy-operator#2285]
**What steps did you take and what happened:**
I’m using the latest version of Trivy Operator, 0.22. All components are functioning as expected, but the k8s-cis-1.23 report is not being generated. Meanwhile, the k8s-pss-baseline-0.1 report is generated without issues.

**What did you expect to happen:**

**Anything else you would like to add:**
The configuration file for the modified settings is as follows:
```
---
trivy:
  command: filesystem

trivyOperator:
  scanJobPodTemplateContainerSecurityContext:
    # For filesystem scanning, Trivy needs to run as the root user
    runAsUser: 0
  scanJobNodeSelector:
    node.kubernetes.io/role: worker

nodeSelector:
  node.kubernetes.io/role: worker

compliance:
  reportType: all

operator:
  scanJobsConcurrentLimit: 5
  scannerReportTTL: "120h"

nodeCollector:
  tolerations:
    - key: ***/control-plane
      operator: "Equal"
      effect: NoSchedule
    - key: ***/dedicated
      value: engineering
      operator: "Equal"
      effect: NoSchedule
    - key: ***/dedicated
      value: s***a
      operator: "Equal"
      effect: NoSchedule     
```

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.22
- Kubernetes version (use `kubectl version`): v1.30.4+rke2r1
