### ISSUE TITLE
Support for extra env vars in Helm chart

### ISSUE THREAD

**Issue by gnadaban** [aquasecurity/trivy-operator#2287]
When running the operator on AWS using IRSA role it would be great if the session name was configurable via env var eg.:

```yaml
extraEnv:
  - name: AWS_ROLE_SESSION_NAME
    value: trivy-operator
```
