### ISSUE TITLE
Trivy Operator crashes large clusters

### ISSUE THREAD

**Issue by bo0ts** [aquasecurity/trivy-operator#2335]
**What steps did you take and what happened:**

We ran trivy operator installed through the Helm chart version `0.25.0` on an OKD 4.15 cluster with ~1200 non-system pods, most of them running with two containers or more. We expected this to create quite some load on the cluster and customized the installation this way:

```
excludeNamespaces: "kube-system,openshift-*"
operator:
  vulnerabilityScannerEnabled: true
  sbomGenerationEnabled: true
  # disable config, rbac, infra and compliance scanner
  configAuditScannerEnabled: false
  rbacAssessmentScannerEnabled: false
  infraAssessmentScannerEnabled: false
  clusterComplianceEnabled: false
```

**What did you expect to happen:**

We expected this to take quite a while to complete and initially results looked good. At some point load on etcd got exceedingly high and leader changes started to occur. This led to a complete crash of the API and the cluster had to be restored from a recent etcd backups. We managed to take a snapshot before starting recovery and the etcd cluster grew from ~380MB to ~1.2Gi

We would need to scale the control-plane significantly to accommodate trivy-operator and also consider deploying it in a production cluster to be too dangerous. 

Are there any options to reduce the footprint of CRs? In general I feel that trivy-operator relies too much on etcd as an actual data storage and that isn't in line with kubernetes design philosophy.
