### ISSUE TITLE
Failed to pull image 0.23

### ISSUE THREAD

**Issue by rkashasl** [aquasecurity/trivy-operator#2336]
**What steps did you take and what happened:**

We upgraded chart from 0.24.1 to 0.25 and then pod can't pull the image.

```
Warning  Failed            5m51s (x4 over 7m23s)   kubelet            Failed to pull image "mirror.gcr.io/ghcr.io/aquasecurity/trivy-operator:0.23.0": rpc error: code = NotFound desc = failed to pull and unpack image "mirror.gcr.io/ghcr.io/aquasecurity/trivy-operator:0.23.0": failed to resolve reference "mirror.gcr.io/ghcr.io/aquasecurity/trivy-operator:0.23.0": mirror.gcr.io/ghcr.io/aquasecurity/trivy-operator:0.23.0: not found                                                                                                                    Warning  Failed            5m51s (x4 over 7m23s)   kubelet            Error: ErrImagePull                                                                                             Warning  Failed            5m39s (x6 over 7m22s)   kubelet            Error: ImagePullBackOff                                                                                         Normal   BackOff           2m14s (x21 over 7m22s)  kubelet            Back-off pulling image "mirror.gcr.io/ghcr.io/aquasecurity/trivy-operator:0.23.0"
``` 
**What did you expect to happen:**

Trivy starts after upgrade
**Anything else you would like to add:**
pod yaml:
```
Name:                 trivy-operator-6bc7447dcd-dj677
Namespace:            security-system
Priority:             50
Priority Class Name:  medium
Service Account:      trivy-operator-oidc
Node:                 ip-10-21-81-38.eu-central-1.compute.internal/10.21.81.38
Start Time:           Mon, 02 Dec 2024 13:53:18 +0200
Labels:               app.kubernetes.io/instance=trivy-operator
                      app.kubernetes.io/name=trivy-operator
                      pod-template-hash=6bc7447dcd
Annotations:          <none>
Status:               Pending
IP:                   10.21.81.251
IPs:
  IP:           10.21.81.251
Controlled By:  ReplicaSet/trivy-operator-6bc7447dcd
Containers:
  trivy-operator:
    Container ID:   
    Image:          mirror.gcr.io/ghcr.io/aquasecurity/trivy-operator:0.23.0
    Image ID:       
    Ports:          8080/TCP, 9090/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  2Gi
    Requests:
      cpu:      800m
      memory:   512Mi
    Liveness:   http-get http://:probes/healthz/ delay=5s timeout=1s period=10s #success=1 #failure=10
    Readiness:  http-get http://:probes/readyz/ delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      trivy-operator-config  ConfigMap  Optional: false
    Environment:
      OPERATOR_NAMESPACE:           security-system
      OPERATOR_TARGET_NAMESPACES:   
      OPERATOR_EXCLUDE_NAMESPACES:  security-system
      OPERATOR_TARGET_WORKLOADS:    pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,job
      OPERATOR_SERVICE_ACCOUNT:     trivy-operator-oidc
      AWS_STS_REGIONAL_ENDPOINTS:   regional
      AWS_DEFAULT_REGION:           eu-central-1
      AWS_REGION:                   eu-central-1
      AWS_ROLE_ARN:                 arn:aws:iam::1120***
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /tmp from cache-policies (rw)
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-lxfn6 (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  aws-iam-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  86400
  cache-policies:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kube-api-access-lxfn6:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 arch=arm64:NoSchedule
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  16m                 default-scheduler  0/7 nodes are available: 7 Insufficient cpu. preemption: 0/7 nodes are available: 2 Insufficient cpu, 5 No preemption victims found for incoming pod.
  Normal   Scheduled         16m                 default-scheduler  Successfully assigned security-system/trivy-operator-6bc7447dcd-dj677 to ip-10-21-81-38.eu-central-1.compute.internal
  Normal   Pulling           14m (x4 over 16m)   kubelet            Pulling image "mirror.gcr.io/ghcr.io/aquasecurity/trivy-operator:0.23.0"
  Warning  Failed            14m (x4 over 16m)   kubelet            Failed to pull image "mirror.gcr.io/ghcr.io/aquasecurity/trivy-operator:0.23.0": rpc error: code = NotFound desc = failed to pull and unpack image "mirror.gcr.io/ghcr.io/aquasecurity/trivy-operator:0.23.0": failed to resolve reference "mirror.gcr.io/ghcr.io/aquasecurity/trivy-operator:0.23.0": mirror.gcr.io/ghcr.io/aquasecurity/trivy-operator:0.23.0: not found
  Warning  Failed            14m (x4 over 16m)   kubelet            Error: ErrImagePull
  Warning  Failed            14m (x6 over 16m)   kubelet            Error: ImagePullBackOff
  Normal   BackOff           64s (x65 over 16m)  kubelet            Back-off pulling image "mirror.gcr.io/ghcr.io/aquasecurity/trivy-operator:0.23.0"

``` 

Trivy release yaml:
```
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: trivy-operator
  namespace: security-system
spec:
  interval: 17m
  url: https://aquasecurity.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: security-system
spec:
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 9m
  chart:
    spec:
      chart: trivy-operator
      version: 0.25.0
      sourceRef:
        kind: HelmRepository
        name: trivy-operator
        namespace: security-system
      interval: 14m
  values:
    excludeNamespaces: "security-system"
    serviceAccount:
      create: false
      name: trivy-operator-oidc
    targetNamespaces: ""
    image:
      repository: ghcr.io/aquasecurity/trivy-operator
    operator:
      configAuditScannerEnabled: true
      vulnerabilityScannerScanOnlyCurrentRevisions: true
      configAuditScannerScanOnlyCurrentRevisions: true
      scanJobsConcurrentLimit: 1
      scannerReportTTL: "24h"
      metricsVulnIdEnabled: true
      infraAssessmentScannerEnabled: false
    trivyOperator:
      # scanJobNodeSelector:
      #   kubernetes.io/arch: arm64
      scanJobTolerations:
      - key: "arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"
    serviceMonitor:
      enabled: true
    trivy:
      repository: ghcr.io/aquasecurity/trivy  # public.ecr.aws/aquasecurity/trivy
      mode: ClientServer
      serverURL: http://trivy-server.security-system:4954
    resources:
      requests:
        cpu: 800m
        memory: 512Mi
      limits:
        memory: 2Gi
    # nodeSelector:
    #   kubernetes.io/arch: arm64
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
          weight: 1
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
    tolerations:
    - key: "arch"
      operator: "Equal"
      value: "arm64"
      effect: "NoSchedule"
``` 

**Environment:**

All our environments are affected as chart been upgraded by renovate-bot

- Trivy-Operator version (use `trivy-operator version`): 0.25
- Kubernetes version (use `kubectl version`): 1.30
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): EKS
