### ISSUE TITLE
scan-vulnerabilityreports being created and are stuck initializing

### ISSUE THREAD

**Issue by Fiskeboat** [aquasecurity/trivy-operator#2343]
**What steps did you take and what happened:**

When running Trivy Operator helmchart 0.25.0 app version 0.23.0 the Trivy-Operator deployment starts and spins up the pod, but it creates endless Jobs that are stuck. They never reach the ready phase.
![image](https://github.com/user-attachments/assets/4665c4fe-8b95-4129-9d7e-38b8d8615a73)
Example of one of the jobs (the message repeats until the job crashes and another takes it place)
![image](https://github.com/user-attachments/assets/f18f6ff9-8ce0-4b48-adf5-13d1cd131bae)

**What did you expect to happen:**

Created jobs finish, and generate the Kind: Vulnerabilityreport as seen missing after it runs for a while
![image](https://github.com/user-attachments/assets/77fc5741-4c39-4b72-a42d-fe53600527a1)

**Anything else you would like to add:**

There are also these two error messages that appear in the trivy-operator pod itself after running around 10 minutes
It times out downloading policies. I think it leads to the `"error":"creating job: no compliance commands found"`

`{"level":"error","ts":"2024-12-03T13:29:40Z","logger":"policyLoader.Get misconfig bundle policies","msg":"failed to load policies","error":"failed to download policies: failed to download built-in policies: download error: OCI repository error: 1 error occurred:\n\t* Get \"https://mirror.gcr.io/v2/\": dial tcp 74.125.205.82:443: connect: connection timed out\n\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/policy.(*policyLoader).GetPoliciesAndBundlePath\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/policy/loader.go:63\ngithub.com/aquasecurity/trivy-operator/pkg/configauditreport/controller.(*NodeReconciler).SetupWithManager.(*NodeReconciler).reconcileNodes.func5\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/configauditreport/controller/node.go:169\nsigs.k8s.io/controller-runtime/pkg/reconcile.TypedFunc[...].Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/reconcile/reconcile.go:124\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:224"}`

`{"level":"error","ts":"2024-12-03T13:29:40Z","msg":"Reconciler error","controller":"node","controllerGroup":"","controllerKind":"Node","Node":{"name":"nodepool01"},"namespace":"","name":"nodepool01","error":"creating job: no compliance commands found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:224"}`

**Environment:**

- Trivy-Operator version: 0.23.0
- Kubernetes version: 1.29.9
- OS: Win 11

Our Helmchart values hosted with Argo. Might there be an issue that our namespace is not called the default trivy-system? Although this has worked before, before trivy-operator began having the TOOMANYREQUESTS errors.
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: trivy-operator
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://aquasecurity.github.io/helm-charts/"
    targetRevision: 0.25.0
    chart: trivy-operator
    helm:
      values: |-
        image:
          registry: "azurecr.io"
        resources:
          requests:
            memory: 1000M
          limits:
            memory: 1000M
        operator:
          sbomGenerationEnabled: false
          clusterSbomCacheEnabled: false
          scannerReportTTL: "24h"
          cacheReportTTL: "120h"
          metricsFindingsEnabled: true
          metricsVulnIdEnabled: true
          exposedSecretScannerEnabled: true
          metricsExposedSecretInfo: true
          metricsConfigAuditInfo: true
          metricsRbacAssessmentInfo: true
          metricsInfraAssessmentInfo: true
          metricsImageInfo: true
          metricsClusterComplianceInfo: true
        serviceMonitor:
          enabled: true
        trivyOperator:
          scanJobPodTemplateContainerSecurityContext:
            runAsUser: 0
          scanJobTolerations:
            - key: "CriticalAddonsOnly"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
        trivy:
          image:
            registry: "azurecr.io"
          resources:
              requests:
                memory: 1000M
              limits:
                memory: 1000M
          command: filesystem
          ignoreUnfixed: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

Thanks for any support :)
