### ISSUE TITLE
Custom volume mounts not applied to containers and init containers

### ISSUE THREAD

**Issue by tom1299** [aquasecurity/trivy-operator#2348]
**What steps did you take and what happened:**
I added customVolumes and customVolumeMounts to the values of the trivy-operator helm-chart:
```yaml
trivyOperator:
    scanJobCustomVolumesMount:
      - name: trivy-cache
        mountPath: /tmp/trivy/.cache
        readOnly: false
    scanJobCustomVolumes:
      - name: trivy-cache
        persistentVolumeClaim:
          claimName: trivy-cache
```
The resulting Pod did include the custom volume but not the volumeMount (neither main nor init container):
```yaml
    volumeMounts:
    - mountPath: /tmp
      name: tmp
    - mountPath: /tmp/scan
      name: scanresult
... 
    volumeMounts:
    - mountPath: /tmp
      name: tmp
...
  volumes:
  - emptyDir: {}
    name: tmp
  - emptyDir: {}
    name: scanresult
  - name: trivy-cache
    persistentVolumeClaim:
      claimName: trivy-cache
```

**What did you expect to happen:**
The volumeMoutns should have been added.

**Anything else you would like to add:**
I created a draft pull request https://github.com/aquasecurity/trivy-operator/pull/2347 Since I am not a golang expert I would appreciate a review

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): Custom build from main branch (dc44a0a7ac50d77394753de6195af8b1fd0c0deb)
- Kubernetes version (use `kubectl version`): Client Version: v1.31.0, Server Version: v1.30.0
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Fedora release 39 (Thirty Nine)
