### ISSUE TITLE
kustomize + argoCD

### ISSUE THREAD

**Issue by Kouzi99** [aquasecurity/trivy-operator#2356]
After using --enable-helm in ArgoCD to resolve #2349 , the ServiceMonitor stopped deploying. I'm not sure if this is related to the release name, which I had to provide during the Kustomize build to avoid the default RELEASE-NAME prefix before the trivy-operator deployment name. I'm curious if anyone has had a similar experience or if you have any solutions. For now, I manually add the ServiceMonitor to the Kustomize file. I would also appreciate any advice on how to remove the release name in ArgoCD, Kustomize, and Helm deployment.

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: trivy-operator
    repo: https://zy.xy.org/repository/epa-helm
    version: 0.25.0
    releaseName: trivy-operator
    namespace: trivy-system
    valuesFile: values.yaml
```
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trivy-operator
  namespace: trivy-system
  labels:
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/version: 0.23.0
    argocd.argoproj.io/instance: trivy-operator
    helm.sh/chart: trivy-operator-0.25.0
    release: kube-prometheus-stack
spec:
  endpoints:
    - honorLabels: true
      interval: 30s
      port: metrics
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: trivy-operator
      app.kubernetes.io/name: trivy-operator
```
