### ISSUE TITLE
bug: custom checks with non built-in namespace are never applied

### ISSUE THREAD

**Issue by nikpivkin** [aquasecurity/trivy-operator#2441]
**What steps did you take and what happened:**
I followed the guide in the documentation on adding custom checks, but there was no way I could get trivy-operator to apply the check. Then I discovered that trivy-operator does not pass check namespaces to trivy. See [docs](https://trivy.dev/latest/docs/scanner/misconfiguration/#passing-namespaces):

> By default, Trivy evaluates checks defined in builtin.*. If you want to evaluate custom checks in other packages, you have to specify package prefixes through --namespaces option. This can be repeated for specifying multiple packages.

Consequently, only those checks that use one of the built-in namespaces from `builtin, defsec, appshield` will be applied.

Solution options:
- Add a new parameter `namespace` to cm `trivy-operator-trivy-config` to specify namespaces of checks and pass it to Trivy
- Automatically extract namepsace from the check using the `opa` package, but I think this is out of `trivy-operator` responsibility.

**What did you expect to happen:**
The custom check will be applied

**Steps to reproduce**
1. Create pod `kubectl apply -f pod.yaml`:
`pod.yaml`
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: default
spec:
  containers:
    - name: my-container
      image: nginx
```

2. Create cm with check `kubectl apply -f configmap-trivy-checks.yaml`:

`configmap-trivy-checks.yaml`
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-operator-policies-config
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/version: "0.23.0"
    app.kubernetes.io/managed-by: kubectl
data:
  policy.recommended_labels.kinds: "*"
  policy.recommended_labels.rego: |
    package trivyoperator.policy.k8s.custom
    import future.keywords.in

    __rego_metadata__ := {
        "id": "test-0001",
        "avd_id": "test-0001",
        "title": "Recommended labels",
        "severity": "LOW",
        "type": "Kubernetes Security Check",
        "description": "A common set of labels allows tools to work interoperably, describing objects in a common manner that all tools can understand.",
        "recommended_actions": "Take full advantage of using recommended labels and apply them on every resource object.",
        "url": "https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/",
    }

    deny[res] {
        input.kind == "Pod"
        some container in input.spec.containers
        res := {"msg": "deny"}
    }
```

3. Check the configuration reports:

```bash
❯ kubectl get configauditreport
No resources found in default namespace.
```

4. Change rego package to `defsec.policy.k8s`
5. Update cm: `kubectl apply -f configmap-trivy-checks.yaml`
6. Check the configuration reports:

```bash
❯ kubectl describe configauditreport/pod-my-pod
Name:         pod-my-pod
Namespace:    default
Labels:       plugin-config-hash=5d9f6f6dbb
              resource-spec-hash=6c4b487bd7
              trivy-operator.resource.kind=Pod
              trivy-operator.resource.name=my-pod
              trivy-operator.resource.namespace=default
Annotations:  trivy-operator.aquasecurity.github.io/report-ttl: 24h0m0s
API Version:  aquasecurity.github.io/v1alpha1
Kind:         ConfigAuditReport
Metadata:
  Creation Timestamp:  2025-02-14T08:52:19Z
  Generation:          1
  Owner References:
    API Version:           v1
    Block Owner Deletion:  false
    Controller:            true
    Kind:                  Pod
    Name:                  my-pod
    UID:                   d9f8a700-993b-4dfd-b1a8-7caf5fc1b66a
  Resource Version:        251672
  UID:                     6bc2a33e-1fd5-412c-abed-992b7e4f0530
Report:
  Checks:
    Category:     Kubernetes Security Check
    Check ID:     test-0001
    Description:  A common set of labels allows tools to work interoperably, describing objects in a common manner that all tools can understand.
    Messages:
      deny
    Remediation:  Take full advantage of using recommended labels and apply them on every resource object.
    Severity:     LOW
    Success:      false
    Title:        Recommended labels
  Scanner:
    Name:     Trivy
    Vendor:   Aqua Security
    Version:  dev
  Summary:
    Critical Count:  0
    High Count:      0
    Low Count:       1
    Medium Count:    0
  Update Timestamp:  2025-02-14T08:52:19Z
Events:              <none>
```

**Environment:**

- Trivy-Operator version 7961baa247ce94d1d06fce4e5dd02f62b85829ba
