### ISSUE TITLE
bug: resources are not rescanned after deleting cm `trivy-operator-policies-config`

### ISSUE THREAD

**Issue by nikpivkin** [aquasecurity/trivy-operator#2443]
**What steps did you take and what happened:**
From the documentation:
> trivy-operator automatically detects policies added to the trivy-operator-policies-config ConfigMap and immediately rescans applicable Kubernetes resources.

Removing `trivy-operator-policies-config` means removing custom checks, so the operator should rescan the resources. However, it doesn't. On the other hand, the operator will rescan resources if I recreate the ConfigMap with empty data

**What did you expect to happen:**

Operator rescan resources after removing `trivy-operator-policies-config`

**Anything else you would like to add:**

1. Create cm `trivy-operator-policies-config`:

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-operator-policies-config
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/version: "0.23.0"
    app.kubernetes.io/managed-by: kubectl
data:
  policy.recommended_labels.kinds: "*"
  policy.recommended_labels.rego: |
    package defsec.policy.k8s.custom
    import future.keywords.in

    __rego_metadata__ := {
        "id": "test-0001",
        "avd_id": "test-0001",
        "title": "Recommended labels",
        "severity": "LOW",
        "type": "Kubernetes Security Check",
        "description": "A common set of labels allows tools to work interoperably, describing objects in a common manner that all tools can understand.",
        "recommended_actions": "Take full advantage of using recommended labels and apply them on every resource object.",
        "url": "https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/",
    }

    deny[res] {
        input.kind == "Pod"
        some container in input.spec.containers
        res := {"msg": "deny"}
    }
```

2. Create pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: default
spec:
  containers:
    - name: my-container
      image: nginx
```

3. Check that the report has been created:
```
❯ kubectl describe configauditreport/pod-my-pod
Name:         pod-my-pod
Namespace:    default
Labels:       plugin-config-hash=5d9f6f6dbb
              resource-spec-hash=6c4b487bd7
              trivy-operator.resource.kind=Pod
              trivy-operator.resource.name=my-pod
              trivy-operator.resource.namespace=default
Annotations:  trivy-operator.aquasecurity.github.io/report-ttl: 24h0m0s
API Version:  aquasecurity.github.io/v1alpha1
Kind:         ConfigAuditReport
Metadata:
  Creation Timestamp:  2025-02-14T10:29:38Z
  Generation:          1
  Owner References:
    API Version:           v1
    Block Owner Deletion:  false
    Controller:            true
    Kind:                  Pod
    Name:                  my-pod
    UID:                   d9f8a700-993b-4dfd-b1a8-7caf5fc1b66a
  Resource Version:        258402
  UID:                     fe5c028e-99cb-4fb6-8c1f-af657c5092e9
Report:
  Checks:
    Category:     Kubernetes Security Check
    Check ID:     test-0001
    Description:  A common set of labels allows tools to work interoperably, describing objects in a common manner that all tools can understand.
    Messages:
      deny
    Remediation:  Take full advantage of using recommended labels and apply them on every resource object.
    Severity:     LOW
    Success:      false
    Title:        Recommended labels
  Scanner:
    Name:     Trivy
    Vendor:   Aqua Security
    Version:  dev
  Summary:
    Critical Count:  0
    High Count:      0
    Low Count:       1
    Medium Count:    0
  Update Timestamp:  2025-02-14T10:29:37Z
Events:              <none>
```

4. Delete cm: `kubectl delete cm/trivy-operator-policies-config -n trivy-system`
5. Check that the report has not changed:
```
❯ kubectl describe configauditreport/pod-my-pod
Name:         pod-my-pod
Namespace:    default
Labels:       plugin-config-hash=5d9f6f6dbb
              resource-spec-hash=6c4b487bd7
              trivy-operator.resource.kind=Pod
              trivy-operator.resource.name=my-pod
              trivy-operator.resource.namespace=default
Annotations:  trivy-operator.aquasecurity.github.io/report-ttl: 24h0m0s
API Version:  aquasecurity.github.io/v1alpha1
Kind:         ConfigAuditReport
Metadata:
  Creation Timestamp:  2025-02-14T10:29:38Z
  Generation:          1
  Owner References:
    API Version:           v1
    Block Owner Deletion:  false
    Controller:            true
    Kind:                  Pod
    Name:                  my-pod
    UID:                   d9f8a700-993b-4dfd-b1a8-7caf5fc1b66a
  Resource Version:        258402
  UID:                     fe5c028e-99cb-4fb6-8c1f-af657c5092e9
Report:
  Checks:
    Category:     Kubernetes Security Check
    Check ID:     test-0001
    Description:  A common set of labels allows tools to work interoperably, describing objects in a common manner that all tools can understand.
    Messages:
      deny
    Remediation:  Take full advantage of using recommended labels and apply them on every resource object.
    Severity:     LOW
    Success:      false
    Title:        Recommended labels
  Scanner:
    Name:     Trivy
    Vendor:   Aqua Security
    Version:  dev
  Summary:
    Critical Count:  0
    High Count:      0
    Low Count:       1
    Medium Count:    0
  Update Timestamp:  2025-02-14T10:29:37Z
Events:              <none>
```

**Environment:**

- Trivy-Operator version 7961baa247ce94d1d06fce4e5dd02f62b85829ba
