### ISSUE TITLE
Invalid interpretation of `trivyOperator.scanJobAffinity` in Helm chart configuration

### ISSUE THREAD

**Issue by t-khr** [aquasecurity/trivy-operator#2456]
## Issue Description
Invalid handling of `trivyOperator.scanJobAffinity` configuration when installing Trivy operator via Helm.

## Expected Behavior
The configuration should accept the affinity settings as shown in the values file.
```yaml
trivyOperator:
  scanJobAffinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: cloud.google.com/gke-spot
                operator: In
                values:
                  - "true"
```

## Actual Behavior
Receiving error: `coalesce.go:223: warning: destination for trivy-operator.trivyOperator.scanJobAffinity is a table. Ignoring non-table value ([])`

## Steps to Reproduce
```bash
tee ./trivy-operator-values.yaml <<EOF
trivyOperator:
  scanJobAffinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: cloud.google.com/gke-spot
                operator: In
                values:
                  - "true"
EOF

helm install trivy-operator aqua/trivy-operator \
 --namespace trivy-system \
 --create-namespace \
 --version 0.26.1 \
 --values ./trivy-operator-values.yaml
 ```

## Additional Notes
The configuration appears to expect `trivyOperator.scanJobTolerations` as a JSON object rather than an array, which conflicts with the documented format.

**Environment:**
- Trivy-Operator version :  0.26.1
