### ISSUE TITLE
[Feature Request] Support for VEX Configurations

### ISSUE THREAD

**Issue by Hacks4Snacks** [aquasecurity/trivy-operator#2468]
Objective: Optionally enable VEX configuration utilizing using an existing configmap in the cluster (no expectation for the trivy-operator to create the object).

Problem Statement: Trivy supports filtering detected vulnerabilities using the [Vulnerability Exploitability eXchange (VEX)](https://www.ntia.gov/files/ntia/publications/vex_one-page_summary.pdf), a standardized format for sharing and exchanging information about vulnerabilities. By providing VEX during scanning, it is possible to filter vulnerabilities based on their status. The trivy-operator should support an optional enablement of the Trivy --vex flag for vulnerability scanning.

Proposed Solution: Add support for the vex flag via Helm chart values.yaml where the flag is disabled by default and when enable requires user to define the configmap to use. By using values.yaml to drive enablement, critical path components for configmap and jobspec creation can be easily updated to account for an enablement flag which signals the need for volume creation, VEX format validation, and job argument appending.

Expected Outcome: The proposed feature should allow greater user flexibility in supporting known False Positive vulnerability suppression scenarios via vex configurations delivered/referenceable via configmap.

Out of scope: Vex configuration creation.

**Comment by agologan** [comment]
Got this working like by mapping two config files:
```yaml
trivyOperator:
  scanJobCustomVolumesMount:
    - name: vex
      mountPath: /tmp/vex
      readOnly: true
    - name: config
      mountPath: /trivy.yaml
      subPath: trivy.yaml

  scanJobCustomVolumes:
    - name: vex
      configMap:
        name: openvex
    - name: config
      configmap:
        name: trivy-config
```
where `trivy-config` is
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-config
data:
  trivy.yaml: |
    vulnerability:
      vex:
        - /tmp/vex/rancher.openvex.json
```
and `openvex` config is something like the rancher merged openvex [rancher.openvex.json](https://github.com/rancher/vexhub/blob/main/reports/rancher.openvex.json)

The `trivy.yaml` workaround is unnecessary if we add a `trivy.vex` option to [config.go](https://github.com/aquasecurity/trivy-operator/blob/main/pkg/plugins/trivy/config.go)

The one thing I didn't understand from the Trivy code (and maybe @knqyf263 can help with) is if in the Client/Server model VEX filtering happens only on the Client end or if we can specify the repo or VEX files for the server to cache and apply.

If there's support for caching the VEX repository server-side then the config would change and you could pass the repo there, otherwise caching a merged VEX file in a config file is the easier option to avoid downloading files on each scan.
