### ISSUE TITLE
Always define TRIVY_USERNAME and TRIVY_PASSWORD environment variables when using custom Java DB repository

### ISSUE THREAD

**Issue by keliansb** [aquasecurity/trivy-operator#2510]
**What steps did you take and what happened:**

Some of our containers are based on images using our private registry as mirror and some are based on images from  public registries.
The scans of images using our private registry are running successfully but the scan of images using public registries give the following error:

```
{
  "level": "error",
  "ts": "2025-04-07T12:17:26Z",
  "logger": "reconciler.scan job",
  "msg": "Scan job container",
  "job": "trivy-system/scan-vulnerabilityreport-7d5cf68548",
  "container": "postgresql",
  "status.reason": "Error",
  "status.message": "2025-04-07T12:17:23Z\tFATAL\tFatal error\timage scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:5c45d471a3ac5959c5eaf85b52eb6d3a4e2c7fa508b279a4804a33db50428411): post analysis error: post analysis error: Unable to initialize the Java DB: Java DB update failed: OCI artifact error: failed to download Java DB: failed to download artifact from registry.example.org/proxy.ghcr.io/aquasecurity/trivy-java-db:1: OCI repository error: 1 error occurred:\n\t* GET https://registry.example.org/v2/proxy.ghcr.io/aquasecurity/trivy-java-db/manifests/1: UNAUTHORIZED: unauthorized to access repository: proxy.ghcr.io/aquasecurity/trivy-java-db, action: pull: unauthorized to access repository: proxy.ghcr.io/aquasecurity/trivy-java-db, action: pull\n\n\n",
  "stacktrace": "github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).completedContainers\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:355\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).SetupWithManager.(*ScanJobController).reconcileJobs.func1\n\t/home/runner/work/trivy-operator/trivy-operator/pkg/vulnerabilityreport/controller/scanjob.go:82\nsigs.k8s.io/controller-runtime/pkg/reconcile.TypedFunc[...[].Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/reconcile/reconcile.go:124\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...[]).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...[]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:328\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...[]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:288\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:249",
}
```

It seems that the variables `TRIVY_USERNAME` and `TRIVY_PASSWORD` are only set when scanning images using the private registry as mirror, so I believe it's the reason why Trivy does not have the credentials to download the Java DB when scanning images from public registries.

**What did you expect to happen:**

Variables `TRIVY_USERNAME` and `TRIVY_PASSWORD` set on scan jobs when the Trivy Java DB repository is a private registry.

**Anything else you would like to add:**

Note that we are running the Trivy Operator in [Client/Server mode](https://trivy.dev/latest/docs/references/modes/client-server/).

Here is the `values.yaml` file I am using:

```
image:
  registry: myregistry.example.org/proxy.mirror.gcr.io
nodeCollector:
  registry: myregistry.example.org/proxy.ghcr.io
operator:
  builtInTrivyServer: true
  metricsVulnIdEnabled: true
  privateRegistryScanSecretsNames: {"trivy-system":"dockerconfigjson-myregistry"}
  scanJobTimeout: 15m
policiesBundle:
  existingSecret: true
  registry: myregistry.example.org/proxy.ghcr.io
  repository: aquasecurity/trivy-checks
service:
  headless: false
serviceMonitor:
  enabled: true
trivy:
  dbRegistry: myregistry.example.org/proxy.ghcr.io
  dbRepository: aquasecurity/trivy-db
  existingSecret: true
  ignoreUnfixed: true
  image:
    registry: myregistry.example.org/proxy.mirror.gcr.io
  javaDbRegistry: myregistry.example.org/proxy.ghcr.io
  javaDbRepository: aquasecurity/trivy-java-db
  registry:
    mirror:
      "docker.io": myregistry.example.org/proxy.docker.io
      "gcr.io": myregistry.example.org/proxy.gcr.io
      "ghcr.io": myregistry.example.org/proxy.ghcr.io
      "index.docker.io": myregistry.example.org/proxy.docker.io
      "mirror.gcr.io": myregistry.example.org/proxy.mirror.gcr.io
      "quay.io": myregistry.example.org/proxy.quay.io
  resources:
    limits:
      cpu: 2
      memory: 1Gi
  slow: false
  sslCertDir: /etc/ssl/certs
  storageClassName: csi-rbd-sc
  timeout: 15m0s
volumeMounts:
  - mountPath: /tmp
    name: cache-policies
    readOnly: false
  - mountPath: /etc/ssl/certs/ca-certificates.crt
    name: ca-certificates
    readOnly: true
    subPath: bundle.pem
volumes:
  - name: cache-policies
    emptyDir: {}
  - configMap:
      name: ca-certificates
    name: ca-certificates
```

And the secrets `trivy-operator` and `trivy-operator-trivy-config` contain the following config:

```
apiVersion: v1
data:
  policies.bundle.oci.password: <redacted>
  policies.bundle.oci.user: <redacted>
kind: Secret
metadata:
  name: trivy-operator
  namespace: trivy-system
type: Opaque
---
apiVersion: v1
data:
  TRIVY_PASSWORD: <redacted>
  TRIVY_USERNAME: <redacted>
  trivy.dbRepositoryPassword: <redacted>
  trivy.dbRepositoryUsername: <redacted>
kind: Secret
metadata:
  name: trivy-operator-trivy-config
  namespace: trivy-system
type: Opaque
```

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.25.0
- Kubernetes version (use `kubectl version`): 1.31.4
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Ubuntu 20.04 LTS
