### ISSUE TITLE
trivy.dbRepositoryUsername/Password not working in ClientServer mode

### ISSUE THREAD

**Issue by peschmae** [aquasecurity/trivy-operator#2536]
**What steps did you take and what happened:**

We are using trivy-operator in an air-gapped environment with a a registry mirror for the vulnerability db and the `ClientServer` mode.

We defined the `trivy.dbRegistryUsername` and `trivy.dbRegistryPassword` credentials using the helm chart, but downloading the vulnerability database fails in the server pod.

```
│ 2025-05-01T10:55:16Z    INFO    [vulndb] Downloading vulnerability DB...                                                                                                        │
│ 2025-05-01T10:55:16Z    INFO    [vulndb] Downloading artifact...    repo="<REGISTRY_MIRROR>/aquasec/trivy-db:2"                                               │
│ 2025-05-01T10:55:16Z    FATAL    Fatal error    failed to download vulnerability DB: OCI artifact error: failed to download vulnerability DB: failed to download artifact from  │
│ <REGISTRY_MIRROR>/aquasec/trivy-db:2: OCI repository error: 1 error occurred:                                                                                 │
│     * GET https://<REGISTRY_MIRROR>/artifactory/api/docker/docker-local/v2/token?scope=repository%3Aaquasec%2Ftrivy-db%3Apull&service=<REGISTRY_MIRROR>: : Authentication is required
```

Debugging it, we figured out that setting the `TRIVY_USERNAME`/`TRIVY_PASSWORD` environment variables was the only way to get it to work, and it wasn't necessary to set `trivy.dbRegistry*` values at all, if we use `trivy.serverUser`/`trivy.serverPassword`

The `TRIVY_*` env vars, are set in a few places in the code, but as it seems only for scan jobs in `Standalone` mode, eg. [here](https://github.com/aquasecurity/trivy-operator/blob/2c362d99ea4ebee01eb1feeed1ad32292253be7e/pkg/plugins/trivy/image.go#L243) 

Our helm values look like this

```yaml
image:
  pullSecrets:
  - name: <PULL_SECRET_REF>
serviceMonitor:
  enabled: true
operator:
  infraAssessmentScannerEnabled: false
  builtInTrivyServer: true
trivy:
  image:
    imagePullSecret: <PULL_SECRET_REF>
  mode: ClientServer
  existingSecret: false
  priorityClassName: medium
  slow: false
  ignoreUnfixed: false
  dbRegistry: <REGISTRY_MIRROR>
  javaDbRegistry: <REGISTRY_MIRROR>
  dbRepositoryUsername: <USERNAME>
  dbRepositoryPassword: <PASSWORD>
priorityClassName: medium
policiesBundle:
  registry: <REGISTRY_MIRROR>
  existingSecret: false
nodeCollector:
  imagePullSecrets:
  - name: <PULL_SECRET_REF>
```

**What did you expect to happen:**

I expected the `trivy.dbRegistryUsername` and `trivy.dbRegistryPassword` to be enough configuration to fetch the database in `ClientServer` mode.

**Anything else you would like to add:**

Based on the discussion [#2344](https://github.com/aquasecurity/trivy-operator/discussions/2344) we've written a kustomize patch that we apply after helm templating, that solves the issue for us.

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trivy-server
spec:
  template:
    spec:
      containers:
      - name: trivy-server
        env:
        - name: TRIVY_USERNAME
          valueFrom:
            secretKeyRef:
              name: trivy-operator-trivy-config
              key: trivy.dbRepositoryUsername
        - name: TRIVY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trivy-operator-trivy-config
              key: trivy.dbRepositoryPassword
```

Using this patch the secrets can be downloaded successfully from the `trivy-server` pod.

I think either the description of the variables should be made more clear, or just combine the `trivy.serverUser`/`trivy.serverPassword` and `trivy.dbRepositoryUsername`/`trivy.dbRepositoryPassword` into  a single field, to avoid misconfigurations. This would also allow just switching the `mode` without having to reconfigure credentials.

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.25.0
- Kubernetes version (use `kubectl version`): 1.32.0
