### ISSUE TITLE
Bare host directory mount on vulnerability report scan pods

### ISSUE THREAD

**Issue by AlvaroMartinezQ** [aquasecurity/trivy-operator#2550]
**What steps did you take and what happened:**

Hello everyone! I installed the Trivy operator on a Kubernetes cluster to run some image checks (currently checking the capabilities of the tool). I deployed it using the Helm chart, here are my values (redacted for readability):

```
extraEnv:
  # Testing out env variables to see which ones are passed correctly
  - name: TRIVY_SSL_CERT_DIR
    value: /etc/ssl/certs
  - name: OPERATOR_SSL_CERT_DIR
    value: /etc/ssl/certs
  - name: SSL_CERT_DIR
    value: /etc/ssl/certs
global:
  image:
    registry: myCustomRegistry.io
trivy:
  ignoreUnfixed: true
  sslCertDir: /etc/ssl/certs
trivyOperator:
  scanJobCustomVolumesMount:
    - mountPath: /etc/ssl/certs
      name: cert-volume
      readOnly: true
  scanJobCustomVolumes:
    - name: cert-volume
      secret:
        secretName: ca-bundle
volumeMounts:
  - mountPath: /etc/ssl/certs
    name: cert-volume
    readOnly: true
volumes:
  - name: cert-volume
    secret:
      secretName: ca-bundle
nodeCollector:
  registry: myCustomRegistry.io
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
policiesBundle:
  registry: myCustomRegistry.io
  repository: aquasec/trivy-checks
operator:
  privateRegistryScanSecretsNames:
    trivy-operator: cr-pull-secret
service:
  headless: false
serviceMonitor:
  enabled: true
```

Trivy operator runs correctly, as well as vulnerability report pods. The trivy operator pod mounts the certificates directory as expected, example with `kubectl describe`:

```
...
Containers:
  trivy-operator:
    ...
    Environment:
      ...
      TRIVY_SSL_CERT_DIR:           /etc/ssl/certs
      TRIVY_OPERATOR_SSL_CERT_DIR:  /etc/ssl/certs
      SSL_CERT_DIR:                 /etc/ssl/certs
    Mounts:
      /etc/ssl/certs from cert-volume (ro)
Volumes:
  cert-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ca-bundle
    Optional:    false
...
```

But this is not the case on the scan-vulnerability report pods, same procedure with `kubectl describe`:

```
...
Containers:
  block-cloud-metadata:
    Environment:
      ...
      SSL_CERT_DIR:              /var/ssl-cert
      ...
    Mounts:
      /etc/ssl/certs from cert-volume (ro)
      /tmp from tmp (rw)
      /tmp/scan from scanresult (rw)
      /var/ssl-cert from ssl-cert-dir (ro)
    ...
Volumes:
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  ssl-cert-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/ssl/certs
    HostPathType:  
  scanresult:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  cert-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ca-bundle
    Optional:    false
...
```

Note the variable `SSL_CERT_DIR` ponting to `/var/ssl-cert`, which shows the certs are taken from the volume `ssl-cert-dir`. This is a direct mount to the host; to one of my Kubernetes nodes.

**What did you expect to happen:**

I would expect to be able to override/change the variable `SSL_CERT_DIR` on the scan-vulnerability report pods which Trivy spins up, to point to the correct folder. Also, I don't know why the scan-vulnerability report pods would need to mount a bare host directory path from my cluster nodes? In my case, some nodes do not have the certificates configured at that level.

**Anything else you would like to add:**

If I manually add the certificate into the correct directory in the Kubernetes nodes, the vulnerability report pods run correctly. I would like to know if maybe I'm missing some configuration on the Helm chart, I could not find any information on the official doc about this.

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): Helm chart version 0.27.0, Trivy image version 0.60.0
- Kubernetes version (use `kubectl version`):
  - Client Version: v1.29.1
  - Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  - Server Version: v1.30.10
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Ubuntu 22.04
