### ISSUE TITLE
additionalReportLabels are not being added to reports

### ISSUE THREAD

**Issue by nicl-dev** [aquasecurity/trivy-operator#2554]
**What steps did you take and what happened:**

Added the following Helm value:
 
```yaml
trivyOperator:
  additionalReportLabels: "env=dev"
```

However, the label is not added to our reports. Even after restarting the `Deployment`.

**What did you expect to happen:**

Our `VulnerabilityReports` should have the label `env: dev` added.

**Anything else you would like to add:**

The config shows up in the `ConfigMap` but for some reason the operator does not add the label. Here is our `ConfigMap`:

```yaml
apiVersion: v1
data:
  compliance.failEntriesLimit: "10"
  configAuditReports.scanner: Trivy
  node.collector.imageRef: ghcr.io/aquasecurity/node-collector:0.3.1
  node.collector.nodeSelector: "true"
  policies.bundle.insecure: "false"
  policies.bundle.oci.ref: mirror.gcr.io/aquasec/trivy-checks:1
  report.additionalLabels: env=dev
  report.recordFailedChecksOnly: "true"
  scanJob.compressLogs: "true"
  scanJob.podTemplateContainerSecurityContext: '{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":true}'
  scanJob.useGCRServiceAccount: "true"
  vulnerabilityReports.scanner: Trivy
kind: ConfigMap
```
And here is a freshly generated `VulnerabilityReport`:

```
k get vulnerabilityreports replicaset-trivy-trivy-operator-69bdc85764-trivy-operator -oyaml
apiVersion: aquasecurity.github.io/v1alpha1
kind: VulnerabilityReport
metadata:
  annotations:
    trivy-operator.aquasecurity.github.io/report-ttl: 30m0s
  creationTimestamp: "2025-05-13T18:33:23Z"
  generation: 2
  labels:
    resource-spec-hash: 7d79fcfccb
    trivy-operator.container.name: trivy-operator
    trivy-operator.resource.kind: ReplicaSet
    trivy-operator.resource.name: trivy-trivy-operator-69bdc85764
    trivy-operator.resource.namespace: trivy
```

**Environment:**

- Trivy-Operator version (use `trivy-operator version`):
`trivy-operator-0.25.0`
- Kubernetes version (use `kubectl version`): 
```
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.32.3-eks-bcf3d70
```
