### ISSUE TITLE
Why is node-collector trying to create a dir in /etc/systemd?

### ISSUE THREAD

**Issue by tijmenvandenbrink** [aquasecurity/trivy-operator#2566]
**What steps did you take and what happened:**

I'm deploying trivy-operator (chart version 0.28.1) using Argocd/Helm on a Talos Linux based cluster. When the node-collector runs I get the following error:

```
Name:             node-collector-5ff8c4887c-6xrnm.1842b0a1bb18b3f5
Namespace:        trivy-system
Labels:           <none>
Annotations:      <none>
API Version:      v1
Count:            1
Event Time:       <nil>
First Timestamp:  2025-05-25T06:16:54Z
Involved Object:
  API Version:       v1
  Field Path:        spec.containers{node-collector}
  Kind:              Pod
  Name:              node-collector-5ff8c4887c-6xrnm
  Namespace:         trivy-system
  Resource Version:  43263354
  UID:               d02aaa26-62b5-49f5-99cc-b9de870187da
Kind:                Event
Last Timestamp:      2025-05-25T06:16:54Z
Message:             Error: failed to generate container "52e92bdcbccd37664c6820410ec7c6a1520474eacab9af3f009ae905ca5e5f9d" spec: failed to apply OCI options: failed to mkdir "/etc/systemd": mkdir /etc/systemd: read-only file system
Metadata:
  Creation Timestamp:  2025-05-25T06:16:54Z
  Resource Version:    43263606
  UID:                 f2a2640c-2260-44fc-a388-08b393fb2dcf
Reason:                Failed
Reporting Component:   kubelet
Reporting Instance:    wazowski-cp-0
Source:
  Component:  kubelet
  Host:       wazowski-cp-0
Type:         Warning
Events:       <none>
```

**What did you expect to happen:**

As the default helm config is mounting this specific volume read only I would not expext node-collector to attempt to write something to that volume:

```
  volumeMounts:
    - name: etc-systemd
      mountPath: /etc/systemd
      readOnly: true
  # -- node-collector pod volumes definition for collecting config files information
  volumes:
    - name: etc-systemd
      hostPath:
        path: /etc/systemd
```

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): trivy-operator:0.26.1
- Helm Chart: 0.28.1 
- Kubernetes version (use `kubectl version`): Server Version: v1.32.2
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Talos v1.9.5
