### ISSUE TITLE
excludeNamespaces does not work

### ISSUE THREAD

**Issue by Tomyce12** [aquasecurity/trivy-operator#2575]
**What steps did you take and what happened:**

I've deployed `trivy-operator` using Helm Chart to my Kubernetes cluster. Before deploying `trivy-operator` I defined `excludeNamespaces:"kube-*,argo*,linkerd*,elastic-system,grafana-*"` and left `targetNamespaces` **blank** as described in docs for correct namespace excluding. After successful Helm deployment `trivy-operator`, vulnerability scan still includes all namespaces even those who were included in `excludeNamespaces` and creates vulnerability reports in Kubernetes.

**What did you expect to happen:**

Exclude namespaces listed in `excludeNamespaces` for scanning vulnerabilities.

**Anything else you would like to add:**
my Helm Chart `values.yaml`:
```
excludeNamespaces: "kube-*,argo*,linkerd*,*elastic-system,grafana-*,gitlab-runner,nats-server,keda,kyverno,redis,tor,ingress-nginx"
targetWorkloads: "pod,replicaset,replicationcontroller"
serviceMonitor:
  enabled: true
  namespace: kube-monitoring
operator:
  sbomGenerationEnabled: false
  configAuditScannerEnabled: false
  rbacAssessmentScannerEnabled: false
  infraAssessmentScannerEnabled: false
  clusterComplianceEnabled: false
  exposedSecretScannerEnabled: false
  metricsVulnIdEnabled: true
trivyOperator:
  skipInitContainers: true
trivy:
  severity: "HIGH,CRITICAL"
  ignoreUnfixed: true
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 100M
resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 10m
    memory: 300Mi
```
Logs from `trivy-operator` pod:
```
{"level":"info","ts":"2025-05-27T14:44:09Z","logger":"operator","msg":"Resolved install mode","install mode":"AllNamespaces","operator namespace":"trivy-operator","target namespaces":[],"exclude namespaces":"kube-*,argo*,linkerd*,*elastic-system,grafana-*,gitlab-runner,nats-server,keda,kyverno,redis,tor,ingress-nginx","target workloads":["pod","replicaset","replicationcontroller"]}
```

Currently I switched to `targetNamespaces` to prevent from scanning unwanted namespaces.
 
**Environment:**

- Trivy-Operator version (use `trivy-operator version`): **0.26.1**
- Kubernetes version (use `kubectl version`): **1.32.3-gke.1927009**
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
