### ISSUE TITLE
Scanner Job fail fs one imagePullSecrets is missing

### ISSUE THREAD

**Issue by cdesaintleger** [aquasecurity/trivy-operator#266]
**What steps did you take and what happened:**

If you have a deployment with one or more imagePullSecrets and one of these does not exists, the scan job fail. 

**What did you expect to happen:**

Exactly As the kubernetes pods controller, just ignore the missing secret. 

**Anything else you would like to add:**

To reproduce, create a deployment with two imagePullSecrets. One existant and valid, the second non-existant

```
spec:
  containers:
  - name: private-reg-container
    image: <your-private-image>
  imagePullSecrets:
  - name: validRegCredSecret
  - name: missingRegCredSecret
```
Check the trivy-operator logs. 

The pod is correctly launched ( up and running ) , but the scanner job fail. 

**Environment:**

- Trivy-Operator version 0.1.0
- Kubernetes version 1.21
