### ISSUE TITLE
ConfigAuditReport get recreated in high frequency

### ISSUE THREAD

**Issue by dirien** [aquasecurity/trivy-operator#361]
**What steps did you take and what happened:**

We see in our cluster following effect, that the `ConfigAuditReports` get recreated every second:

```yaml
apiVersion: aquasecurity.github.io/v1alpha1
kind: ConfigAuditReport
metadata:
  creationTimestamp: "2022-07-19T10:51:17Z"
  generation: 2861
```

Here a screenshot:

![image](https://user-images.githubusercontent.com/38325136/179759193-b14bb5d3-7bd8-46b6-b0d0-5f12ac882ee9.png)

![image](https://user-images.githubusercontent.com/38325136/179759216-678ed9f4-3815-4dc2-a4fd-37837cff029d.png)

**What did you expect to happen:**

Not recreating the `ConfigAuditReports` every second.

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.1.3
- Kubernetes version (use `kubectl version`): 1.20
