### ISSUE TITLE
Unable to set trivy.insecureRegistry via helm chart

### ISSUE THREAD

**Issue by mauricewittek** [aquasecurity/trivy-operator#372]
**What steps did you take and what happened:**

I'm trying to deploy the trivy-operator in an airgapped environment. I got it to work with the static deployment file by setting the following values in the `trivy-operator-trivy-config` configMap:

```yaml
trivy.insecureRegistry.artifactory: "packages.repo.internal.com"
trivy.serverInsecure: true
trivy.dbRepository: "packages.repo.internal.com/docker-github-proxy/aquasecurity/trivy-db"
trivy.dbRepositoryInsecure: "true"
```

However, I'm unable to set `trivy.insecureRegistry` via the trivy-operator helm chart. The helm chart seemingly only allows for the definition of `nonSslRegistries`. I tried using this setting but it doesn't seem to have any effect. 

I can get the helm chart to work by manually patching the configMap after the `helm install`:

```bash
kubectl patch configmap trivy-operator-trivy-config -n trivy-system --type=merge -p='{"data":{"trivy.insecureRegistry.artifactory": "packages.repo.internal.com"}}'
```

**What did you expect to happen:**

I would expect `nonSslRegistries` to have the same effect as `trivy.insecureRegistry` or for the helm chart to allow the configuration of `trivy.insecureRegistry`

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.1.4
- Kubernetes version (use `kubectl version`): 1.23.6
