### ISSUE TITLE
Specify namespace in Helm Chart Values.yaml manifest different to {{ .Release.Namespace }}

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/trivy-operator#487]
When installing Trivy as a Helm Chart dependency, I would like to set the `trivy-system` namespace in the Values.Yaml manifest.

Currently, the namespace is defined with `{{ .Release.Namespace }}` however, that will take the same namespace as the application/the main Chart in the Helm Chart, which reduces the flexibility to use the trivy-operator with other applications/processes.

Here are the manifests used to install the Chart dependency:
Dependency in Chart.Yaml
```
dependencies:
  - name: trivy-operator
    version: "0.1.9"
    repository: "https://aquasecurity.github.io/helm-charts/"
```

Values for the Trivy-operator Helm Chart, to which I would like to add the namespace
```
trivy-operator:
  trivy:
    ignoreUnfixed: true
```
