### ISSUE TITLE
option to only record failed checks in CRD

### ISSUE THREAD

**Issue by jrhunger** [aquasecurity/trivy-operator#495]
Stanzas like the following are generally not adding value.  They add noise that is hard to filter when reviewing manually. I assume they are also consuming storage in the cluster etcd.  It would be nice to have an option to only include failed checks.  A report that only includes failed checks would be very concise and easy to review/action.
```
  - category: Kubernetes Security Check
    checkID: KSV105
    description: Containers should be forbidden from running with a root UID.
    messages:
    - ""
    severity: LOW
    success: true
    title: Containers must not set runAsUser to 0
```
