### ISSUE TITLE
Got error "unable to run trivy operator: starting controllers manager"

### ISSUE THREAD

**Issue by GregoryLazarev** [aquasecurity/trivy-operator#654]
**What steps did you take and what happened:**

I deployed trivy-operator via Helm. After deploy it works for some time, then crashes. Last message in operator logs is 

`unable to run trivy operator: starting controllers manager: [failed to wait for ingress caches to sync: timed out waiting for cache to be synced, failed waiting for all runnables to end within grace period of 30s: context deadline exceeded]
`

Operator fails with this error when just part of cluster is scanned and new scan jobs not starts after operator restart. 

**What did you expect to happen:**

Operator should work stable, without crashes.

**Anything else you would like to add:**

I used next values:
```
operator:
  scanJobTimeout: 30m
  scanJobsRetryDelay: 1m
  scannerReportTTL: 48h
trivy:
  additionalVulnerabilityReportFields: Description, Links, Target, Class
  githubToken: GH_token
  ignoreUnfixed: true
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 750m
      memory: 500Mi
  timeout: 15m0s
```

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.5.0
- Kubernetes version (use `kubectl version`): 1.18.6
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 13
