### ISSUE TITLE
UNAUTHORIZED: authentication required when using multiple imagePullSecrets

### ISSUE THREAD

**Issue by sfhl** [aquasecurity/trivy-operator#790]
**What steps did you take and what happened:**

Hi there, i am using the trivy-operator to scan my workloads on K8s. This seems not to work if a pod consists of multiple containers, whose images are pulled from different private registries.
So there are multiple containers (inside this pod) and multiple `imagePullSecrets` within the spec of the deployment definiton.
Trivy fails to pull those images.

**What did you expect to happen:**
Trivy succeeds to pull those images and scans them.

**Environment:**

- Trivy-Operator version: `0.8.0`
- Kubernetes version: `v1.23`

**Comment by chen-keinan** [comment]
@sfhl thanks you for reporting this issue , can you please add an example of pod manifest with multi containers and multi imagePullSecret

**Comment by sfhl** [comment]
@chen-keinan 

sure, so here is a shortened manifest containing this configuration:


```
...
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret-1
  namespace: appstack
data:
  .dockerconfigjson: "XXXXXXXXXXXXXXXXX"
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret-2
  namespace: appstack
data:
  .dockerconfigjson: "XXXXXXXXXXXXXXXXX"
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "deployment"
  namespace: appstack
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app: "deployment"
  template:
    metadata:
      labels:
        app: "deployment"
        workload: "deployment"
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        {}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      automountServiceAccountToken: True
      imagePullSecrets:
        - name: "registry-secret-1"
        - name: "registry-secret-2"
      containers:
        - name: "container-1"
          image: "git-images.registry.de/path/to/first/image/images/image-1:tag"
        - name: "container-2"
          image: "git-images.registry.de/path/to/second/image/images/image-2:tag"
...
```

kubernetes is pulling both images, the workload/pod is running, but trivy fails to pull with `UNAUTHORIZED: authentication required;`
