### ISSUE TITLE
Can not create Vulnerability report if there are no links for vulnerability

### ISSUE THREAD

**Issue by GregoryLazarev** [aquasecurity/trivy-operator#792]
**What steps did you take and what happened:** 
During operator work I checked its logs and noticed interesting error. As I can see, there are some vulnerabilities in Trivy database, that have no links. Looks like trivy returns `null` in this case, but vulnerabilityreports crd expects `list (even empty)`, but not `null`

**What did you expect to happen:**
If there are no links, vulnerability report with empty links list should be created

**Anything else you would like to add:**
Screenshot of error in log:
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/39768466/207770306-552746f7-12cf-4c15-ae17-561b82870054.png">
Error text from operator's log:
```json
{
   "level":"error",
   "ts":1671076674.467651,
   "msg":"Reconciler error",
   "controller":"job",
   "controllerGroup":"batch",
   "controllerKind":"Job",
   "Job":{
      "name":"scan-vulnerabilityreport-5d44b99c85",
      "namespace":"trivy-system"
   },
   "namespace":"trivy-system",
   "name":"scan-vulnerabilityreport-5d44b99c85",
   "reconcileID":"e128e792-31c2-4237-8db7-3ea09d3795f6",
   "error":"VulnerabilityReport.aquasecurity.github.io \"cronjob-546d7f7c64\" is invalid: report.vulnerabilities.links: Invalid value: \"null\": report.vulnerabilities.links in body must be of type array: \"null\"",
   "stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"
}
```

Custom values:
```yaml
operator:
  configAuditScannerEnabled: false
  exposedSecretScannerEnabled: false
  infraAssessmentScannerEnabled: false
  rbacAssessmentScannerEnabled: false
  scanJobTimeout: 30m
  scanJobsRetryDelay: 1m
  scannerReportTTL: ""
trivy:
  additionalVulnerabilityReportFields: Description,Links,Class,PackageType
  githubToken: <secret 😏 >
  ignoreUnfixed: true
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 750m
      memory: 500Mi
  timeout: 15m0s
```

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.8.0-rc
- Kubernetes version (use `kubectl version`): v1.18.6
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 13.0.1
