### ISSUE TITLE
Add resource kind deployment to targetWorkloads

### ISSUE THREAD

**Issue by GregoryLazarev** [aquasecurity/trivy-operator#799]
As I can see, now it's impossible to add `deployment` to `targetWorkloads`
https://github.com/aquasecurity/trivy-operator/blob/6068398547598f571ca608ce8e354eca50947d68/pkg/kube/object.go#L674:L694

Please, add ability to set `deployment` as targetWorkload

**Comment by chen-keinan** [comment]
@GregoryLazarev `trivy-operator` reconcile  and produce reports for  `replicaSets` of  deployment so its already covered .
Let me know if this is not sufficient.

**Comment by GregoryLazarev** [comment]
Deployment has `revisionHistoryLimit`. If this parameter not equals to 1, there are several `replicasets` (with different images) and one `deployment`. Due this there are several vulnerability reports for one active resource. We are trying to monitor vulnerabilities of active resources only.

**Comment by chen-keinan** [comment]
@GregoryLazarev we have added an enhancement where we do not keep historical reports at all we only keep one copy
which `trivy-operator ` version are you using ?

**Comment by GregoryLazarev** [comment]
@chen-keinan now 0.8.0-rc is installed.

As I understand, report exist while resource exist.
In this case, if `revisionHistoryLimit`=10, 10 replicasets exists in cluster at the same time, so we have 10 reports (one report for each replicaset).

**Comment by chen-keinan** [comment]
> @chen-keinan now 0.8.0-rc is installed.
> 
> As I understand, report exist while resource exist. In this case, if `revisionHistoryLimit`=10, 10 replicasets exists in cluster at the same time, so we have 10 reports (one report for each replicaset).

we keep only report for active `replicaSet` so if it is not not active then it will be deleted.
can you please share your ConfigMaps

**Comment by chen-keinan** [comment]
@GregoryLazarev I tried it with latest Trivy-operator (which should be the same in term of functionality to `0.8.0-rc`)
and find that once it scan a deployment /upgrade it keeps only the active replicaSet report (as desired).

could you please try this quick simple test :

1. run : `kubectl apply -f https://k8s.io/examples/controllers/nginx-deployment.yaml`

2. after image has been  scanned :
run `kubectl get vulnerabilityreports -o wide` 
```
NAME                                           REPOSITORY      TAG      SCANNER   AGE   CRITICAL   HIGH   MEDIUM   LOW   UNKNOWN
replicaset-nginx-deployment-66b6c48dd5-nginx   library/nginx   1.14.2   Trivy     52s   27         49     46       4     7
```
3. let update the deployment with :
`kubectl set image deployment.v1.apps/nginx-deployment nginx=nginx:1.16.1`

4. after the image has been scanned , we should expect to see only one report (for active replicaSet) without any historical reports:
run `kubectl get vulnerabilityreports -o wide` 

```
NAME                                           REPOSITORY      TAG      SCANNER   AGE   CRITICAL   HIGH   MEDIUM   LOW   UNKNOWN
replicaset-nginx-deployment-559d658b74-nginx   library/nginx   1.16.1   Trivy     24s   38         61     43       10    4
```

***Please do let me know if this is not the case in you env.***

***Note***: the [scannerReportTTL](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L53) must not be empty string

**Comment by GregoryLazarev** [comment]
@chen-keinan 
This is my values for operator
```yaml
operator:
  configAuditScannerEnabled: false
  exposedSecretScannerEnabled: false
  infraAssessmentScannerEnabled: false
  rbacAssessmentScannerEnabled: false
  scanJobTimeout: 30m
  scanJobsRetryDelay: 1m
  scannerReportTTL: ""
trivy:
  additionalVulnerabilityReportFields: Description,Target,Class,PackageType
  githubToken: <Heh, secret 😏>
  ignoreUnfixed: true
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 750m
      memory: 500Mi
  timeout: 15m0s
```

`scannerReportTTL` is empty due I'm generating tasks for developers to fix vulnerabilities each month and need this reports
