### ISSUE TITLE
What are difference between `trivyoperator-trivy-config` and `trivy-operator-trivy-config`

### ISSUE THREAD

**Issue by ahmet2mir** [aquasecurity/trivy-operator#83]
Hello,

With Trivy-Operator v0.0.3, when I use httproxy or alternative dbrepository from helm values, they are ignored as I see on operator logs which is expected without proxy.

```
1.654187065028448e+09   ERROR   reconciler.vulnerabilityreport  Scan job container  {"job": "trivy-operator/scan-vulnerabilityreport-75f4d75dc", "container": "de973285-8e3f-485d-aed4-5dfd7ee210fb", "status.reason": "Error", "status.message": "2022-06-02T16:24:21.651Z\t\u001b[34mINFO\u001b[0m\tNeed to update DB\n2022-06-02T16:24:21.651Z\t\u001b[34mINFO\u001b[0m\tDB Repository: ghcr.io/aquasecurity/trivy-db\n2022-06-02T16:24:21.651Z\t\u001b[34mINFO\u001b[0m\tDownloading DB...\n2022-06-02T16:24:21.659Z\t\u001b[31mFATAL\u001b[0m\tDB error: failed to download vulnerability DB: OCI artifact error: OCI artifact error: OCI repository error: Get \"https://ghcr.io/v2/\": dial tcp: lookup ghcr.io on 172.16.0.1:53: no such host\n"}
```

Helm values `helm get values -n ns-trivy ns-trivy`

```yaml
image:
  pullSecrets:
  - name: myregistry
  repository: myregistry.lan/aquasec/trivy-operator
operator:
  logDevMode: true
trivy:
  dbRepository: myregistry.lan/aquasecurity/trivy-db
  httpProxy: http://proxy.mydomain.lan:3128
  httpsProxy: http://proxy.mydomain.lan:3128
  noProxy: myregistry.lan
  ignoreUnfixed: false
```

On CM side, `trivy-operator-trivy-config` contains what I defined on helm side

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: trivy-operator-trivy-config
  namespace: ns-trivy
  labels:
    app.kubernetes.io/instance: ns-trivy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/version: 0.0.3
    helm.sh/chart: trivy-operator-0.0.3
  annotations:
    meta.helm.sh/release-name: ns-trivy
    meta.helm.sh/release-namespace: ns-trivy
data:
  trivy.mode: Standalone
  trivy.timeout: 5m0s
  trivy.resources.requests.memory: 100M
  trivy.httpsProxy: 'http://proxy.mydomain.lan:3128'
  trivy.httpProxy: 'http://proxy.mydomain.lan:3128'
  trivy.resources.requests.cpu: 100m
  trivy.dbRepository: myregistry.lan/aquasecurity/trivy-db
  trivy.noProxy: myregistry.lan
  trivy.resources.limits.memory: 500M
  trivy.imageRef: 'docker.io/aquasec/trivy:0.25.2'
  trivy.resources.limits.cpu: 500m
  trivy.severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
```

But containers named `scan-vulnerabilityreport-xxx` contains

```
    initContainers:
    - args:
      - --cache-dir
      - /tmp/trivy/.cache
      - image
      - --download-db-only
      - --db-repository
      - ghcr.io/aquasecurity/trivy-db
      command:
      - trivy
      env:
      - name: HTTP_PROXY
        valueFrom:
          configMapKeyRef:
            key: trivy.httpProxy
            name: trivyoperator-trivy-config
            optional: true
```

Note the CM name without dash `trivyoperator-trivy-config`

This CM doesn't contains my overrides

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: trivyoperator-trivy-config
  namespace: ns-trivy
data:
  trivy.timeout: 5m0s
  trivy.resources.requests.memory: 100M
  trivy.mode: Standalone
  trivy.resources.requests.cpu: 100m
  trivy.dbRepository: ghcr.io/aquasecurity/trivy-db
  trivy.resources.limits.memory: 500M
  trivy.imageRef: 'docker.io/aquasec/trivy:0.25.2'
  trivy.resources.limits.cpu: 500m
  trivy.severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
```

They are quite similar and looks like a bug as on code side I could found both names.

If it's expected, I don't get it, how I could set thoses values and what are differences ?

Also when I uninstall the cm without dash is not removed.
