### ISSUE TITLE
Allow skipping of files and directories through annotations

### ISSUE THREAD

**Issue by MattiasAng** [aquasecurity/trivy-operator#830]
Currently it is only possible to skip files and directories on a per-installation level, which means that if you want to exclude something for a specific image/pod it will be excluded for all of them.

My suggestion is that the operator allow skipping of these two on a per-pod level.

Operator looks for `trivy-operator.aquasecurity.github.io/skip-dirs` and `trivy-operator.aquasecurity.github.io/skip-files` (or similar) on the pod with comma separated list of what to skip, and appends to the correct environment variables that are already set. 

Took a quick look at the code and I should be able to implement it if the suggestion is something that aligns with the roadmap.

**Comment by chen-keinan** [comment]
@MattiasAng thanks you for your suggestion , could you propose how the config for it will look like ?

**Comment by MattiasAng** [comment]
In terms of code changes needed, I think we should only need to change `pkg/trivy plugin.go` and functions `getPodSpecForClientServerMode`/`getPodSpecForStandaloneMode`.

I am quite new to Trivy so there might be other CLI arguments that exclude CVE's or similar, so we should try to make this flexible and iterate over a constant which specifies which arguments can be overridden by annotations.

Example pod specification:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    trivy-operator.aquasecurity.github.io/skip-dirs: "/tmp,/home"
    trivy-operator.aquasecurity.github.io/skip-files: "/src/Gemfile.lock,/examplebinary"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
```

Would create a scan job with the following environment variables:
`TRIVY_SKIP_DIRS: "/tmp,/home"`
`TRIVY_SKIP_FILES: "/src/Gemfile.lock,/examplebinary"`

If `trivy.skipFiles` is set in the config map for the above example, it would be appended to `TRIVY_SKIP_FILES` as well.
