### ISSUE TITLE
cis and nsa clustercompliancereport : checks in body must be of type array: "null"

### ISSUE THREAD

**Issue by jemag** [aquasecurity/trivy-operator#881]
**What steps did you take and what happened:**

1. Add trivy-operator helm chart to argocd
2. Synchronize with cluster
3. Notice some checks are null and therefore fail to synchronize:
![image](https://user-images.githubusercontent.com/7985687/214650288-4460d265-df95-43cb-99df-e07e06238bb1.png)

**What did you expect to happen:**
No checks are null and therefore failing the validation

**Anything else you would like to add:**
It seems that the spec defines multiple null checks. However, the CRD for `clustercompliancereports.aquasecurity.github.io` specify those checks to be an array with the required `id` property:
```yaml
                      properties:
                        checks:
                          items:
                            description: SpecCheck represent the scanner who perform
                              the control check
                            properties:
                              id:
                                description: id define the check id as produced by
                                  scanner
                                type: string
                            required:
                            - id
                            type: object
                          type: array

```

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): Helm chart, 0.10.1
- Kubernetes version (use `kubectl version`): 1.24.6
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Ubuntu 18.04.6 LTS,            Kernel: Linux 5.4.0-1098-azure (AKS)
