### ISSUE TITLE
NodeCollector job creates thousands of pods on the Control Plane due to mismatched taints and tolerations

### ISSUE THREAD

**Issue by oed-guzym** [aquasecurity/trivy-operator#937]
**What steps did you take and what happened:**
I upgraded to trivy-operator 0.11.0 and after that the NodeCollector job creates thousands of Pods on Control Plane due to mismatched taints and tolerations on RKE (Rancher Kubernetes Engine) cluster.

**What did you expect to happen:**
NodeCollector job run on each node once and get completed.

**Anything else you would like to add:**
My analysis has shown that the tolerations of the Pod do not match the standard taints of the Control Plane. This leads to a loop of ejected and recreated Pods.

Tolerations of the NodeCollector:
```yaml
tolerations:  
  - effect: NoExecute
     key: node.kubernetes.io/not-ready
     operator: Exists
     tolerationSeconds: 300
  - effect: NoExecute
     key: node.kubernetes.io/unreachable
     operator: Exists
    tolerationSeconds: 300
```
Taints of the Control Plane:
```yaml
taints: 
  - effect: NoSchedule
     key: node-role.kubernetes.io/controlplane 
     value: "true"  
  - effect: NoExecute
     key: node-role.kubernetes.io/etcd
     value: "true"
```
**Suggestion:**
I'm not a GO expert, so I can't say how to implement this, but maybe this could be a solution as it is already used by some other operators like "kured".

Tolerations for the NodeCollector:
```yaml
tolerations:  
  - effect: NoSchedule
     operator: Exists  
  - effect: NoExecute
     operator: Exists
  - effect: NoExecute 
     key: node.kubernetes.io/not-ready 
     operator: Exists
     tolerationSeconds: 300 
  - effect: NoExecute
     key: node.kubernetes.io/unreachable 
     operator: Exists
     tolerationSeconds: 300
```
Or we need a value where the Tolerations for the NodeCollector can be configured, like is already done for the Scan jobs.

**Environment:**
- Trivy-Operator version (use `trivy-operator version`): 0.11.0
- Kubernetes version (use `kubectl version`): 1.20.15 / 1.21.14
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Ubuntu 20.04 / 22.04- RKE: 1.3
