### ISSUE TITLE
No more VulnerabilityReport + "illegal base64 data at input byte 4" or "cannot unmarshal number (...)"

### ISSUE THREAD

**Issue by ledroide** [aquasecurity/trivy-operator#942]
## Symptoms

After months running fine, with many VulnerabilityReports in all namespaces, we discovered that there was no more VulnerabilityReport in any namespace, for any of our k8s clusters.
* some jobs/scan-vulnerabilityreport-xxxxx are running sometime, but still no VulnerabilityReport when job is completed
* logs for a random job just outputs base64 - actually binary when decoding base64 :
```bash
$ kubectl get pod,job -l app.kubernetes.io/managed-by=trivy-operator,vulnerabilityReport.scanner=Trivy -n trivy-system
NAME                                            READY   STATUS      RESTARTS   AGE
pod/scan-vulnerabilityreport-67679699c8-ps88m   0/1     Completed   0          39h

NAME                                            COMPLETIONS   DURATION   AGE
job.batch/scan-vulnerabilityreport-67679699c8   1/1           16s        39h
$
$ kubectl logs -l app.kubernetes.io/managed-by=trivy-operator,vulnerabilityReport.scanner=Trivy -n trivy-system
Defaulted container "node-cache" out of: node-cache, e0073c41-3c2f-49ef-a8b3-f84bb4cd143e (init)
y48MKDTFL5nsozxSuwMguemrO+wcbBebJtsrYg2PgsN5CeH++zoinFT/H4EiOsiIx8uT3/xHtyN7
+SUWq1Lfg3nLBiiSRvmtI4jrUtUWuLC6z9/hh+9vpH0avTipY634PJQn0EBWyonPfZ8yc0ierBQj
mRSEKqqkz5nYunMUqVD8RwsmionV59Ob/mbA1DvRef0pWyDvFsXxYRAu1eARqas+Lh2bnNzHXJI4
Yhg3XAuudMYTuhkWi0sui7B9tmWCmn7FtMLaLFlyEOwU7OJp05Yj5DyxosbRAhNgYSIdDs7jPEiE
IdiaE5ooV6Z8+T0Qzllu5MuaZ2hhDNLwPDUXXvMbGbhApMgfCkwbNy42t9Vw23pyGqIWsNZ0YIOS
QVQ8d49h9o65aDo4qJHUY7WpUEOouVn0k9SAW4GAX/DHArnccBG4OUxLQihayABAL6tg68gd2FUM
mIKGEVDhptG4SDtH+NHgk4DpZPoOSCL3kT6al1iMfZP76h/Eb/3vBHpSJVcP9JTxSRR4I2VwtHod
vS6HRSlSEbpO2+520/1PY8vK8XbMpH/B52fKPrGIE+VfN80L0Op7D5wVHbH8MSexaGbTgeofghvM
z/Ygf7qAkRQB/8w+4/sf4h/xkH/r/0qhs2plkCMv/aQiTOQRv+wPWcA8GH/+LuSKcKEh4Z6WzA==
```
* because we observe the same issue for all our clusters, we know that scan jobs run for any kind of image : private registry, docker hub, ghcr.io, etc. ; it's obviously not a question of credentials, or image similarity, or remote registry, or registry quota.
* logs from the trivy-operator controller report lots of `illegal base64 data at input byte 4` errors :
```bash
$ kubectl logs deploy/trivy-operator -n trivy-system
[...]
```
```json
{"level":"error","ts":"2023-02-10T08:12:40Z","msg":"Reconciler error","controller":"job","controllerGroup":"batch","controllerKind":"Job","Job":{"name":"scan-vulnerabilityreport-67679699c8","namespace":"trivy-system"},"namespace":"trivy-system","name":"scan-vulnerabilityreport-67679699c8","reconcileID":"ee597f18-0f67-4c0e-bcf0-c322762002d1","error":"illegal base64 data at input byte 4","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:235"}
```

## What we have tried

* consider issues #731 fixed by #824 ; #509 fixed by #800 -> similar, but claim to be fixed and merged long time ago
* upgrade from trivy-operator 0.10.0 to 0.11.0 -> no effect
* kill eventually remaining scan jobs and pods -> no effect
* increase limits for scan job containers - i.e. to avoid potential OOMkilled - in _ConfigMap/trivy-operator-trivy-config_ -> no effect
* in _configmap/trivy-operator_ turn `scanJob.compressLogs: "true"` to `"false"` and restart _deploy/trivy-operator_ -> no effect on VulnerabilityReports and jobs, however the error reported by trivy-operator is now `json: cannot unmarshal number into Go value of type trivy.ScanReport` - which had been reported by old #206 fixed by #190 for trivy-operator 0.1.0 :
```json
{"level":"error","ts":"2023-02-10T08:55:22Z","msg":"Reconciler error","controller":"job","controllerGroup":"batch","controllerKind":"Job","Job":{"name":"scan-vulnerabilityreport-7c884d4d56","namespace":"trivy-system"},"namespace":"trivy-system","name":"scan-vulnerabilityreport-7c884d4d56","reconcileID":"d4cc7a3f-8d98-4f1e-b250-b4867574cb59","error":"json: cannot unmarshal number into Go value of type trivy.ScanReport","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:235"}
```
* maybe linked to #441 which is not yet solved ?

## Environment

* Trivy-operator 0.11.0 + latest trivy image for image scans
```bash
$ kubectl images -n trivy-system
[Summary]: 1 namespaces, 2 pods, 3 containers and 2 different images
+-------------------------------------------+--------------------------------------+--------------------------------------------+
|                    Pod                    |              Container               |                   Image                    |
+-------------------------------------------+--------------------------------------+--------------------------------------------+
| scan-vulnerabilityreport-67679699c8-ps88m | node-cache                           | ghcr.io/aquasecurity/trivy:latest          |
+                                           +--------------------------------------+                                            +
|                                           | (init)                               |                                            |
|                                           | e0073c41-3c2f-49ef-a8b3-f84bb4cd143e |                                            |
+-------------------------------------------+--------------------------------------+--------------------------------------------+
| trivy-operator-65ddb9675c-pln24           | trivy-operator                       | ghcr.io/aquasecurity/trivy-operator:0.11.0 |
+-------------------------------------------+--------------------------------------+--------------------------------------------+
```
* Kubernetes 1.25.5 ; Calico 3.24.5 ; Cri-o 1.25.1
* base for trivy-operator implementation : [deploy/static/trivy-operator.yaml](https://raw.githubusercontent.com/aquasecurity/trivy-operator/v0.11.0/deploy/static/trivy-operator.yaml) from this repository
* current values from configmap/trivy-operator - before _scanJob.compressLogs_ changed to _"false"_ :
```yaml
data:
  configAuditReports.scanner: Trivy
  report.recordFailedChecksOnly: "true"
  scanJob.compressLogs: "true"
  scanJob.podTemplateContainerSecurityContext: '{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":true}'
  vulnerabilityReports.scanner: Trivy
```
* current values from configmap/trivy-operator-trivy-config :
```yaml
data:
  trivy.additionalVulnerabilityReportFields: ""
  trivy.command: image
  trivy.dbRepository: ghcr.io/aquasecurity/trivy-db
  trivy.dbRepositoryInsecure: "false"
  trivy.imageRef: ghcr.io/aquasecurity/trivy:latest
  trivy.mode: Standalone
  trivy.repository: ghcr.io/aquasecurity/trivy
  trivy.resources.limits.cpu: 3000m
  trivy.resources.limits.memory: 5500M
  trivy.resources.requests.cpu: 100m
  trivy.resources.requests.memory: 200M
  trivy.severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
  trivy.slow: "true"
  trivy.supportedConfigAuditKinds: Workload,Service,Role,ClusterRole,NetworkPolicy,Ingress,LimitRange,ResourceQuota
  trivy.tag: latest
  trivy.timeout: 5m0s
  trivy.useBuiltinRegoPolicies: "true"
```
