### ISSUE TITLE
Duplicate vulnerability in VulnerabilityReport

### ISSUE THREAD

**Issue by dkulchinsky** [aquasecurity/trivy-operator#947]
**What steps did you take and what happened:**

Deployment that runs the image `quay.io/strimzi/kafka:0.32.0-kafka-3.3.1`, which has a known CVE: `CVE-2022-36944`

The produce `VulnerabilityReport` listed this CVE, however it appears twice:

```yaml
  - class: lang-pkgs
    cvss:
      ghsa:
        V3Score: 9.8
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
      nvd:
        V3Score: 9.8
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    fixedVersion: 2.13.9
    installedVersion: 2.13.6
    links: []
    packageType: jar
    primaryLink: https://avd.aquasec.com/nvd/cve-2022-36944
    resource: org.scala-lang:scala-library
    score: 9.8
    severity: CRITICAL
    target: Java
    title: Scala subject to file deletion, code execution due to Java deserialization
      chain with LazyList object deserialization
    vulnerabilityID: CVE-2022-36944
  - class: lang-pkgs
    cvss:
      ghsa:
        V3Score: 9.8
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
      nvd:
        V3Score: 9.8
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    fixedVersion: 2.13.9
    installedVersion: 2.13.8
    links: []
    packageType: jar
    primaryLink: https://avd.aquasec.com/nvd/cve-2022-36944
    resource: org.scala-lang:scala-library
    score: 9.8
    severity: CRITICAL
    target: Java
    title: Scala subject to file deletion, code execution due to Java deserialization
      chain with LazyList object deserialization
    vulnerabilityID: CVE-2022-36944
```

The above also results in an incorrect count for critical CVEs for this image (expected 1, result shows 2):
```
trivy_image_vulnerabilities{container_name="cruise-control", image_registry="quay.io", image_repository="strimzi/kafka", image_tag="0.32.0-kafka-3.3.1",name="replicaset-7c667475fb",resource_kind="ReplicaSet", resource_name="fst-events-kafka-cruise-control-7dc457b66b", severity="Critical"} 2
```

**What did you expect to happen:**

`VulnerabilityReport` to have an entry and only one entry of the above CVE as it is detected in the image.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.10.2
- Kubernetes version (use `kubectl version`): v1.23.10
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): N/A
