### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by githubcdr** [aquasecurity/trivy-operator#963]
After upgrading to v 0.11.0 I got this error in the operator logs

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1973d28]

goroutine 1 [running]:
github.com/aquasecurity/trivy-operator/pkg/operator.Start({_, _}, {{_, _}, {_, _}, {_, _}, {_, _}}, ...)
    /home/runner/work/trivy-operator/trivy-operator/pkg/operator/operator.go:212 +0x1908
main.run()
    /home/runner/work/trivy-operator/trivy-operator/cmd/trivy-operator/main.go:50 +0x230
main.main()
    /home/runner/work/trivy-operator/trivy-operator/cmd/trivy-operator/main.go:34 +0x1c
```

```
  values:
    excludeNamespaces: trivy-system
    operator:
      # scanJobsConcurrentLimit the maximum number of scan jobs create by the operator
      scanJobsConcurrentLimit: 2
      vulnerabilityScannerScanOnlyCurrentRevisions: true
      configAuditScannerScanOnlyCurrentRevisions: true
      configAuditScannerEnabled: false
    serviceMonitor:
      # enabled determines whether a serviceMonitor should be deployed
      enabled: true
      labels:
        release: kube-prometheus-stack
    trivy:
      ignoreUnfixed: true
      timeout: "15m0s"
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 1200Mi
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi
```

- Trivy-Operator version (use `trivy-operator version`): 0.11.0
- Kubernetes version (use `kubectl version`): 1.26.1
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): talos
