### ISSUE TITLE
ExposedSecretReport target attribute is always empty

### ISSUE THREAD

**Issue by dkulchinsky** [aquasecurity/trivy-operator#992]
**What steps did you take and what happened:**

The `target` attribute of found secrets in `ExposedSecretReport` is always empty, although when reviewing the same report produced by trivy cli (using `trivy i --security-checks secret -f json <image>`) the target is specified:

Output from `trivy` cli:
```
  "Results": [
    {
      "Target": "/etc/apt/s3auth.conf",
      "Class": "secret",
      "Secrets": [
        {
          "RuleID": "aws-access-key-id",
          "Category": "AWS",
          "Severity": "CRITICAL",
          "Title": "AWS Access Key ID",
```

`ExposedSecretReport` of same image:

```
  secrets:
  - category: AWS
    match: AccessKeyId = ********************
    ruleID: aws-access-key-id
    severity: CRITICAL
    target: ""
    title: AWS Access Key ID
```

**What did you expect to happen:**

Was expecting to see the value of target to be populated with the path of the file where the secret material was identified. 

**Anything else you would like to add:**

N/A

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.10.2
- Kubernetes version (use `kubectl version`): 1.24.9
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): N/A
